// Generated by CIRCT firtool-1.75.0
module Sodor_SodorInternalTile(	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:178:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:178:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:178:7]
  input         io_debug_port_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input  [63:0] io_debug_port_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input  [63:0] io_debug_port_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_debug_port_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input  [2:0]  io_debug_port_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output        io_debug_port_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [63:0] io_debug_port_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output        io_master_port_0_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [63:0] io_master_port_0_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [63:0] io_master_port_0_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output        io_master_port_0_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [2:0]  io_master_port_0_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_master_port_0_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input  [63:0] io_master_port_0_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output        io_master_port_1_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [63:0] io_master_port_1_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [63:0] io_master_port_1_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output        io_master_port_1_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  output [2:0]  io_master_port_1_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_master_port_1_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input  [63:0] io_master_port_1_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_interrupt_debug,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_interrupt_mtip,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_interrupt_msip,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_interrupt_meip,	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
  input         io_hartid	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:45:14]
);

  wire [31:0] my_commit_exception;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:228:33]
  wire [31:0] my_commit_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:227:28]
  wire [63:0] my_commit_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:226:27]
  wire [63:0] my_commit_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:225:27]
  wire [63:0] my_commit_pc_next;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:224:31]
  wire [63:0] my_commit_pc;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:223:26]
  wire [4:0]  my_commit_target;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:222:30]
  wire [63:0] my_commit_memaddr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:221:31]
  wire [63:0] my_commit_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:220:31]
  wire        my_commit_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:219:31]
  wire        _router_1_io_scratchPort_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [63:0] _router_1_io_scratchPort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [2:0]  _router_1_io_scratchPort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire        _router_1_io_corePort_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [63:0] _router_1_io_corePort_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire        _router_io_scratchPort_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [63:0] _router_io_scratchPort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [63:0] _router_io_scratchPort_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire        _router_io_scratchPort_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [2:0]  _router_io_scratchPort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire        _router_io_corePort_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire [63:0] _router_io_corePort_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  wire        _memory_io_core_ports_0_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
  wire [63:0] _memory_io_core_ports_0_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
  wire        _memory_io_core_ports_1_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
  wire [63:0] _memory_io_core_ports_1_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
  wire        _core_io_imem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire [63:0] _core_io_imem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire        _core_io_dmem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire [63:0] _core_io_dmem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire [63:0] _core_io_dmem_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire        _core_io_dmem_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire [2:0]  _core_io_dmem_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire [63:0] my_mem_addr = _core_io_dmem_req_valid ? _core_io_dmem_req_bits_addr : 64'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22, :218:31, :230:27]
  Sodor_Core core (	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .clock                  (clock),
    .reset                  (reset),
    .io_imem_req_valid      (_core_io_imem_req_valid),
    .io_imem_req_bits_addr  (_core_io_imem_req_bits_addr),
    .io_imem_resp_valid     (_router_1_io_corePort_resp_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_imem_resp_bits_data (_router_1_io_corePort_resp_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_dmem_req_valid      (_core_io_dmem_req_valid),
    .io_dmem_req_bits_addr  (_core_io_dmem_req_bits_addr),
    .io_dmem_req_bits_data  (_core_io_dmem_req_bits_data),
    .io_dmem_req_bits_fcn   (_core_io_dmem_req_bits_fcn),
    .io_dmem_req_bits_typ   (_core_io_dmem_req_bits_typ),
    .io_dmem_resp_valid     (_router_io_corePort_resp_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_dmem_resp_bits_data (_router_io_corePort_resp_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_interrupt_debug     (io_interrupt_debug),
    .io_interrupt_mtip      (io_interrupt_mtip),
    .io_interrupt_msip      (io_interrupt_msip),
    .io_interrupt_meip      (io_interrupt_meip),
    .io_hartid              (io_hartid),
    .io_my_commit_valid     (my_commit_valid),
    .io_my_commit_data      (my_commit_data),
    .io_my_commit_target    (my_commit_target),
    .io_my_commit_pc        (my_commit_pc),
    .io_my_commit_pc_next   (my_commit_pc_next),
    .io_my_commit_memaddr   (my_commit_memaddr),
    .io_my_commit_rs1       (my_commit_rs1),
    .io_my_commit_rs2       (my_commit_rs2),
    .io_my_commit_inst      (my_commit_inst),
    .io_my_commit_exception (my_commit_exception)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  wire        my_mem_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:217:31]
  assign my_mem_valid = _core_io_dmem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22, :217:31]
  Sodor_AsyncScratchPadMemory memory (	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
    .clock                          (clock),
    .reset                          (reset),
    .io_core_ports_0_req_valid      (_router_io_scratchPort_req_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_0_req_bits_addr  (_router_io_scratchPort_req_bits_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_0_req_bits_data  (_router_io_scratchPort_req_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_0_req_bits_fcn   (_router_io_scratchPort_req_bits_fcn),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_0_req_bits_typ   (_router_io_scratchPort_req_bits_typ),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_0_resp_valid     (_memory_io_core_ports_0_resp_valid),
    .io_core_ports_0_resp_bits_data (_memory_io_core_ports_0_resp_bits_data),
    .io_core_ports_1_req_valid      (_router_1_io_scratchPort_req_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_1_req_bits_addr  (_router_1_io_scratchPort_req_bits_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_1_req_bits_typ   (_router_1_io_scratchPort_req_bits_typ),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .io_core_ports_1_resp_valid     (_memory_io_core_ports_1_resp_valid),
    .io_core_ports_1_resp_bits_data (_memory_io_core_ports_1_resp_bits_data),
    .io_debug_port_req_valid        (io_debug_port_req_valid),
    .io_debug_port_req_bits_addr    (io_debug_port_req_bits_addr),
    .io_debug_port_req_bits_data    (io_debug_port_req_bits_data),
    .io_debug_port_req_bits_fcn     (io_debug_port_req_bits_fcn),
    .io_debug_port_req_bits_typ     (io_debug_port_req_bits_typ),
    .io_debug_port_resp_valid       (io_debug_port_resp_valid),
    .io_debug_port_resp_bits_data   (io_debug_port_resp_bits_data)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
  Sodor_SodorRequestRouter router (	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .clock                         (clock),
    .reset                         (reset),
    .io_masterPort_req_valid       (io_master_port_0_req_valid),
    .io_masterPort_req_bits_addr   (io_master_port_0_req_bits_addr),
    .io_masterPort_req_bits_data   (io_master_port_0_req_bits_data),
    .io_masterPort_req_bits_fcn    (io_master_port_0_req_bits_fcn),
    .io_masterPort_req_bits_typ    (io_master_port_0_req_bits_typ),
    .io_masterPort_resp_valid      (io_master_port_0_resp_valid),
    .io_masterPort_resp_bits_data  (io_master_port_0_resp_bits_data),
    .io_scratchPort_req_valid      (_router_io_scratchPort_req_valid),
    .io_scratchPort_req_bits_addr  (_router_io_scratchPort_req_bits_addr),
    .io_scratchPort_req_bits_data  (_router_io_scratchPort_req_bits_data),
    .io_scratchPort_req_bits_fcn   (_router_io_scratchPort_req_bits_fcn),
    .io_scratchPort_req_bits_typ   (_router_io_scratchPort_req_bits_typ),
    .io_scratchPort_resp_valid     (_memory_io_core_ports_0_resp_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
    .io_scratchPort_resp_bits_data (_memory_io_core_ports_0_resp_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
    .io_corePort_req_valid         (_core_io_dmem_req_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_addr     (_core_io_dmem_req_bits_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_data     (_core_io_dmem_req_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_fcn      (_core_io_dmem_req_bits_fcn),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_typ      (_core_io_dmem_req_bits_typ),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_resp_valid        (_router_io_corePort_resp_valid),
    .io_corePort_resp_bits_data    (_router_io_corePort_resp_bits_data),
    .io_respAddress                (_core_io_dmem_req_bits_addr)	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
  Sodor_SodorRequestRouter router_1 (	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
    .clock                         (clock),
    .reset                         (reset),
    .io_masterPort_req_valid       (io_master_port_1_req_valid),
    .io_masterPort_req_bits_addr   (io_master_port_1_req_bits_addr),
    .io_masterPort_req_bits_data   (io_master_port_1_req_bits_data),
    .io_masterPort_req_bits_fcn    (io_master_port_1_req_bits_fcn),
    .io_masterPort_req_bits_typ    (io_master_port_1_req_bits_typ),
    .io_masterPort_resp_valid      (io_master_port_1_resp_valid),
    .io_masterPort_resp_bits_data  (io_master_port_1_resp_bits_data),
    .io_scratchPort_req_valid      (_router_1_io_scratchPort_req_valid),
    .io_scratchPort_req_bits_addr  (_router_1_io_scratchPort_req_bits_addr),
    .io_scratchPort_req_bits_data  (/* unused */),
    .io_scratchPort_req_bits_fcn   (/* unused */),
    .io_scratchPort_req_bits_typ   (_router_1_io_scratchPort_req_bits_typ),
    .io_scratchPort_resp_valid     (_memory_io_core_ports_1_resp_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
    .io_scratchPort_resp_bits_data (_memory_io_core_ports_1_resp_bits_data),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:187:22]
    .io_corePort_req_valid         (_core_io_imem_req_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_addr     (_core_io_imem_req_bits_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
    .io_corePort_req_bits_data     (64'h0),
    .io_corePort_req_bits_fcn      (1'h0),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22, :191:24]
    .io_corePort_req_bits_typ      (3'h7),	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22, :191:24]
    .io_corePort_resp_valid        (_router_1_io_corePort_resp_valid),
    .io_corePort_resp_bits_data    (_router_1_io_corePort_resp_bits_data),
    .io_respAddress                (_core_io_imem_req_bits_addr)	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:181:22]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/sodor_internal_tile.scala:191:24]
endmodule

