// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Sodor_CSRFile(	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
  input         clock,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
  input         reset,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
  input         io_ungated_clock,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_interrupts_debug,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_interrupts_mtip,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_interrupts_msip,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_interrupts_meip,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_hartid,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [11:0] io_rw_addr,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [2:0]  io_rw_cmd,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output [63:0] io_rw_rdata,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [63:0] io_rw_wdata,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output        io_eret,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output [33:0] io_evec,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_exception,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input         io_retire,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [63:0] io_cause,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [33:0] io_pc,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  input  [33:0] io_tval,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output [63:0] io_time,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output        io_interrupt,	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
  output [63:0] io_interrupt_cause	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
);

  wire [63:0] _io_rw_rdata_T_224;	// @[src/main/scala/chisel3/util/Mux.scala:30:73]
  reg         io_status_cease_r;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1170:31]
  wire        io_singleStep;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1008:34]
  reg         reg_mstatus_v;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg         reg_mstatus_mpv;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg         reg_mstatus_gva;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg  [1:0]  reg_mstatus_mpp;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg         reg_mstatus_mpie;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg         reg_mstatus_mie;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
  reg         reg_dcsr_ebreakm;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
  reg  [2:0]  reg_dcsr_cause;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
  reg         reg_dcsr_v;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
  reg         reg_dcsr_step;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
  reg         reg_debug;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26]
  reg  [33:0] reg_dpc;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:489:20]
  reg  [63:0] reg_dscratch0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:490:26]
  reg         reg_singleStepped;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:492:30]
  reg  [63:0] reg_mie;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:501:20]
  reg  [33:0] reg_mepc;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:511:21]
  reg  [63:0] reg_mcause;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:512:27]
  reg  [33:0] reg_mtval;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:513:22]
  reg  [63:0] reg_mscratch;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:515:25]
  reg  [31:0] reg_mtvec;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:518:31]
  reg         reg_wfi;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:581:54]
  reg  [2:0]  reg_mcountinhibit;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34]
  reg  [5:0]  small_0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41]
  reg  [57:0] large_0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
  wire [63:0] value = {large_0, small_0};	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :50:31, :55:30]
  reg  [5:0]  small_1;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41]
  reg  [57:0] large_1;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
  wire [63:0] io_time_0 = {large_1, small_1};	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :50:31, :55:30]
  wire [15:0] read_mip = {4'h0, io_interrupts_meip, 3'h0, io_interrupts_mtip, 3'h0, io_interrupts_msip, 3'h0};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:616:22]
  wire [15:0] _GEN = reg_mie[15:0] & read_mip;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:501:20, :616:22, :620:56]
  wire [15:0] m_interrupts = reg_mstatus_mie ? _GEN : 16'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :620:56, :626:25]
  wire [31:0] _read_mtvec_T_5 = reg_mtvec & {24'hFFFFFF, ~(reg_mtvec[0] ? 8'hFE : 8'h2)};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:518:31, :1682:{39,41}, generators/rocket-chip/src/main/scala/util/package.scala:174:{35,37,41,46}]
  wire [11:0] decoded_addr_decoded_decoded_invInputs = ~io_rw_addr;	// @[src/main/scala/chisel3/util/pla.scala:78:21]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T = {decoded_addr_decoded_decoded_invInputs[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_2 = {decoded_addr_decoded_decoded_invInputs[0], decoded_addr_decoded_decoded_invInputs[1], io_rw_addr[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_3 = {io_rw_addr[0], decoded_addr_decoded_decoded_invInputs[1], io_rw_addr[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [10:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_4 = {decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], io_rw_addr[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_34 = {decoded_addr_decoded_decoded_invInputs[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], io_rw_addr[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_35 = {io_rw_addr[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], io_rw_addr[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_36 = {decoded_addr_decoded_decoded_invInputs[0], io_rw_addr[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], io_rw_addr[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_37 = {io_rw_addr[0], io_rw_addr[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], io_rw_addr[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_43 = {decoded_addr_decoded_decoded_invInputs[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], io_rw_addr[4], io_rw_addr[5], decoded_addr_decoded_decoded_invInputs[6], io_rw_addr[7], io_rw_addr[8], io_rw_addr[9], io_rw_addr[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_44 = {io_rw_addr[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], io_rw_addr[4], io_rw_addr[5], decoded_addr_decoded_decoded_invInputs[6], io_rw_addr[7], io_rw_addr[8], io_rw_addr[9], io_rw_addr[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [10:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_45 = {io_rw_addr[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], io_rw_addr[4], io_rw_addr[5], decoded_addr_decoded_decoded_invInputs[6], io_rw_addr[7], io_rw_addr[8], io_rw_addr[9], io_rw_addr[10], decoded_addr_decoded_decoded_invInputs[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [10:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_46 = {decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], io_rw_addr[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [11:0] _decoded_addr_decoded_decoded_andMatrixOutputs_T_47 = {decoded_addr_decoded_decoded_invInputs[0], io_rw_addr[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], io_rw_addr[11]};	// @[src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:53]
  wire [63:0] _wdata_T_2 = (io_rw_cmd[1] ? _io_rw_rdata_T_224 : 64'h0) | io_rw_wdata;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{9,13,30}, src/main/scala/chisel3/util/Mux.scala:30:73]
  wire [63:0] _wdata_T_6 = ~((&(io_rw_cmd[1:0])) ? io_rw_wdata : 64'h0);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{41,45,49,55}]
  wire        system_insn = io_rw_cmd == 3'h4;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:882:31]
  wire [11:0] _GEN_0 = ~io_rw_addr;	// @[src/main/scala/chisel3/util/pla.scala:78:21]
  wire        insn_call = system_insn & (&{_GEN_0[0], _GEN_0[1], _GEN_0[2], _GEN_0[3], _GEN_0[4], _GEN_0[5], _GEN_0[6], _GEN_0[7], _GEN_0[8], _GEN_0[9], _GEN_0[10], _GEN_0[11]});	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:882:31, :899:83, src/main/scala/chisel3/util/pla.scala:78:21, :91:29, :98:{53,70}]
  wire        insn_break = system_insn & (&{io_rw_addr[0], _GEN_0[1], _GEN_0[2], _GEN_0[3], _GEN_0[4], _GEN_0[5], _GEN_0[6], _GEN_0[7], _GEN_0[8], _GEN_0[9], _GEN_0[10], _GEN_0[11]});	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:882:31, :899:83, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
  wire        insn_ret = system_insn & (|{&{_GEN_0[2], _GEN_0[3], _GEN_0[4], _GEN_0[5], _GEN_0[6], _GEN_0[7], io_rw_addr[8], io_rw_addr[9], _GEN_0[10], _GEN_0[11]}, &{io_rw_addr[10], _GEN_0[11]}});	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:882:31, :899:83, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}, :114:{19,36}]
  wire [63:0] cause = insn_call ? {60'h0, {3'h1, ~reg_mstatus_v} - 4'h8} : insn_break ? 64'h3 : io_cause;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :899:83, :965:{8,40,45}, :966:14]
  wire        _causeIsDebugTrigger_T_2 = cause[7:0] == 8'hE;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:965:8, :967:25, :969:53]
  wire        causeIsDebugInt = cause[63] & _causeIsDebugTrigger_T_2;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:965:8, :969:{30,39,53}]
  wire        causeIsDebugTrigger = ~(cause[63]) & _causeIsDebugTrigger_T_2;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:965:8, :969:{30,53}, :970:{29,44}]
  wire        trapToDebug = reg_singleStepped | causeIsDebugInt | causeIsDebugTrigger | ~(cause[63]) & insn_break & reg_dcsr_ebreakm | reg_debug;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :488:26, :492:30, :899:83, :965:8, :969:{30,39}, :970:44, :971:{27,42,56}, :972:{56,75,98,119}]
  wire        _exception_T = insn_call | insn_break;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:899:83, :1006:24]
  assign io_singleStep = reg_dcsr_step & ~reg_debug;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :488:26, :933:45, :1008:34]
  wire        exception = _exception_T | io_exception;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1006:24, :1027:43]
  `ifndef SYNTHESIS	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
    wire [2:0] _GEN_1 = {1'h0, {1'h0, insn_ret} + {1'h0, insn_call}} + {1'h0, {1'h0, insn_break} + {1'h0, io_exception}};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:899:83, :1028:18]
    always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
      if (~reset & (|(_GEN_1[2:1]))) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:{9,18,79}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
          $error("Assertion failed: these conditions must be mutually exclusive\n    at CSR.scala:1028 assert(PopCount(insn_ret :: insn_call :: insn_break :: io.exception :: Nil) <= 1.U, \"these conditions must be mutually exclusive\")\n");	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1028:9]
      end
      if (~reset & ~(~reg_singleStepped | ~io_retire)) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:492:30, :1028:9, :1037:{9,10,29,42}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1037:9]
          $error("Assertion failed\n    at CSR.scala:1037 assert(!reg_singleStepped || io.retire === 0.U)\n");	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1037:9]
        if (`STOP_COND_)	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1037:9]
          $fatal;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1037:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _GEN_2 = io_rw_addr[10] & io_rw_addr[7];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1141:{43,48,61}]
  wire [63:0] _io_rw_rdata_T_118 = ((&{io_rw_addr[0], decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]}) ? 64'h8000000000001100 : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T) ? {24'h0, reg_mstatus_mpv, reg_mstatus_gva, 25'h0, reg_mstatus_mpp, 3'h0, reg_mstatus_mpie, 3'h0, reg_mstatus_mie, 3'h0} : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_3) ? {32'h0, _read_mtvec_T_5} : 64'h0);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, generators/rocket-chip/src/main/scala/util/package.scala:138:15, :163:13, :174:35, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
  wire [63:0] _io_rw_rdata_T_124 = {_io_rw_rdata_T_118[63:16], _io_rw_rdata_T_118[15:0] | ((&{io_rw_addr[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], io_rw_addr[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], decoded_addr_decoded_decoded_invInputs[10], decoded_addr_decoded_decoded_invInputs[11]}) ? read_mip : 16'h0)} | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_2) ? reg_mie : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_34) ? reg_mscratch : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_35) ? {{30{reg_mepc[33]}}, reg_mepc[33:2], 2'h0} : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_37) ? {{30{reg_mtval[33]}}, reg_mtval} : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_36) ? reg_mcause : 64'h0);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:501:20, :511:21, :512:27, :513:22, :515:25, :616:22, generators/rocket-chip/src/main/scala/util/package.scala:132:{15,20,38}, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
  wire [63:0] _io_rw_rdata_T_128 = {_io_rw_rdata_T_124[63:32], {_io_rw_rdata_T_124[31:1], _io_rw_rdata_T_124[0] | (&{decoded_addr_decoded_decoded_invInputs[0], decoded_addr_decoded_decoded_invInputs[1], io_rw_addr[2], decoded_addr_decoded_decoded_invInputs[3], io_rw_addr[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], io_rw_addr[8], io_rw_addr[9], io_rw_addr[10], io_rw_addr[11]}) & io_hartid} | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_43) ? {16'h4000, reg_dcsr_ebreakm, 6'h0, reg_dcsr_cause, reg_dcsr_v, 2'h0, reg_dcsr_step, 2'h3} : 32'h0)} | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_44) ? {{30{reg_dpc[33]}}, reg_dpc[33:2], 2'h0} : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_45) ? reg_dscratch0 : 64'h0);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :489:20, :490:26, :676:27, generators/rocket-chip/src/main/scala/util/package.scala:132:{15,20,38}, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
  assign _io_rw_rdata_T_224 = {_io_rw_rdata_T_128[63:3], _io_rw_rdata_T_128[2:0] | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_4) ? reg_mcountinhibit : 3'h0)} | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_46) ? io_time_0 : 64'h0) | ((&_decoded_addr_decoded_decoded_andMatrixOutputs_T_47) ? value : 64'h0) | ((&{decoded_addr_decoded_decoded_invInputs[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], decoded_addr_decoded_decoded_invInputs[8], decoded_addr_decoded_decoded_invInputs[9], io_rw_addr[10], io_rw_addr[11]}) ? io_time_0 : 64'h0) | ((&{decoded_addr_decoded_decoded_invInputs[0], io_rw_addr[1], decoded_addr_decoded_decoded_invInputs[2], decoded_addr_decoded_decoded_invInputs[3], decoded_addr_decoded_decoded_invInputs[4], decoded_addr_decoded_decoded_invInputs[5], decoded_addr_decoded_decoded_invInputs[6], decoded_addr_decoded_decoded_invInputs[7], decoded_addr_decoded_decoded_invInputs[8], decoded_addr_decoded_decoded_invInputs[9], io_rw_addr[10], io_rw_addr[11]}) ? value : 64'h0);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, generators/rocket-chip/src/main/scala/util/Counters.scala:55:30, src/main/scala/chisel3/util/Mux.scala:30:73, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
  wire        csr_wen = io_rw_cmd == 3'h6 | (&io_rw_cmd) | io_rw_cmd == 3'h5;	// @[generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  wire [5:0]  _GEN_3 = _wdata_T_2[5:0] & _wdata_T_6[5:0];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{30,39,41}, generators/rocket-chip/src/main/scala/util/Counters.scala:67:11]
  wire [6:0]  nextSmall = {1'h0, small_0} + {6'h0, io_retire};	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :46:33]
  wire        _GEN_4 = ~insn_ret | _GEN_2;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:899:83, :1042:20, :1122:19, :1124:48, :1141:48]
  wire        _GEN_5 = csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1122:19, :1232:18, :1236:39, :1238:23, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
  wire [31:0] _new_dcsr_WIRE = _wdata_T_2[31:0] & _wdata_T_6[31:0];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1293:52, :1659:{30,39,41}]
  wire [63:0] wdata = _wdata_T_2 & _wdata_T_6;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{30,39,41}]
  wire [33:0] epc = {io_pc[33:2], 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14, :1680:31]
  wire        _GEN_6 = exception & trapToDebug & ~reg_debug;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26, :933:45, :972:{56,75,98,119}, :1027:43, :1042:20, :1043:24, :1044:25, :1046:19]
  wire        _GEN_7 = ~exception | trapToDebug;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :972:{56,75,98,119}, :1027:43, :1042:20, :1043:24]
  wire [33:0] _GEN_8 = {wdata[33:2], 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1290:51, :1659:39]
  always @(posedge clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      reg_mstatus_v <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_mpv <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_gva <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_mpp <= 2'h3;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_mpie <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_mie <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_dcsr_ebreakm <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
      reg_dcsr_cause <= 3'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
      reg_dcsr_v <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
      reg_dcsr_step <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25]
      reg_debug <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26]
      reg_mcause <= 64'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:512:27]
      reg_mtvec <= 32'h80000000;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:518:31]
      reg_mcountinhibit <= 3'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34]
      small_0 <= 6'h0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41]
      large_0 <= 58'h0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
      io_status_cease_r <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1170:31]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      reg_mstatus_v <= ~insn_ret & (~exception | trapToDebug & reg_debug) & reg_mstatus_v;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :488:26, :899:83, :972:{56,75,98,119}, :1027:43, :1042:20, :1043:24, :1044:25, :1045:23, :1053:31, :1122:19, :1124:48]
      reg_mstatus_mpv <= _GEN_4 & (_GEN_7 ? reg_mstatus_mpv : reg_mstatus_v);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :1042:20, :1043:24, :1122:19, :1124:48]
      reg_mstatus_gva <= _GEN_7 & reg_mstatus_gva;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :1042:20, :1043:24]
      if (_GEN_4 & _GEN_7) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :1042:20, :1043:24, :1122:19, :1124:48, :1141:66, :1146:65]
      end
      else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :1042:20, :1043:24, :1122:19, :1124:48, :1141:66, :1146:65]
        reg_mstatus_mpp <= 2'h3;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12]
      reg_mstatus_mpie <= _GEN_5 ? wdata[7] : insn_ret & ~_GEN_2 | (_GEN_7 ? reg_mstatus_mpie : reg_mstatus_mie);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :899:83, :1042:20, :1043:24, :1122:19, :1124:48, :1141:{48,66}, :1146:65, :1232:18, :1236:39, :1237:39, :1238:23, :1239:24, :1659:39]
      reg_mstatus_mie <= _GEN_5 ? wdata[3] : _GEN_4 ? _GEN_7 & reg_mstatus_mie : reg_mstatus_mpie;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :1042:20, :1043:24, :1122:19, :1124:48, :1232:18, :1236:39, :1237:39, :1238:23, :1659:39]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_43)) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :1232:18, :1329:38, :1331:23, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        reg_dcsr_ebreakm <= _new_dcsr_WIRE[15];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :1293:52, :1330:38, :1659:39]
        reg_dcsr_step <= _new_dcsr_WIRE[2];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :1293:52, :1330:38, :1659:39]
      end
      if (_GEN_6) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26, :1042:20, :1043:24, :1044:25, :1046:19]
        reg_dcsr_cause <= reg_singleStepped ? 3'h4 : {1'h0, causeIsDebugInt ? 2'h3 : causeIsDebugTrigger ? 2'h2 : 2'h1};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:409:25, :492:30, :969:39, :970:44, :1048:{30,58,90}]
        reg_dcsr_v <= reg_mstatus_v;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :409:25]
      end
      reg_debug <= ~(insn_ret & _GEN_2) & (_GEN_6 | reg_debug);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26, :899:83, :1042:20, :1043:24, :1044:25, :1046:19, :1122:19, :1124:48, :1141:{48,66}, :1144:17]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_36))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1042:20, :1232:18, :1294:{40,53}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        reg_mcause <= wdata & 64'h800000000000000F;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:512:27, :1294:62, :1659:39]
      else if (_GEN_7) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :512:27, :1042:20, :1043:24]
      end
      else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:512:27, :1042:20, :1043:24]
        reg_mcause <= cause;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:512:27, :965:8]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_3))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:518:31, :1232:18, :1293:{40,52}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        reg_mtvec <= _new_dcsr_WIRE;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:518:31, :1293:52, :1659:39]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_4))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :1232:18, :1314:{47,67}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        reg_mcountinhibit <= _wdata_T_2[2:0] & _wdata_T_6[2:0] & 3'h5;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :1314:{67,76}, :1659:{30,39,41}]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_47)) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1232:18, :1677:31, generators/rocket-chip/src/main/scala/util/Counters.scala:47:19, :67:11, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        small_0 <= _GEN_3;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:39, generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :67:11]
        large_0 <= _wdata_T_2[63:6] & _wdata_T_6[63:6];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{30,39,41}, generators/rocket-chip/src/main/scala/util/Counters.scala:50:31, :68:28]
      end
      else begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1232:18, :1677:31, generators/rocket-chip/src/main/scala/util/Counters.scala:47:19, :67:11]
        if (reg_mcountinhibit[2]) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :598:75]
        end
        else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:598:75]
          small_0 <= nextSmall[5:0];	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :46:33, :47:27]
        if (nextSmall[6] & ~(reg_mcountinhibit[2]))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :598:75, generators/rocket-chip/src/main/scala/util/Counters.scala:46:33, :47:9, :51:{20,33}]
          large_0 <= large_0 + 58'h1;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31, :51:55]
      end
      io_status_cease_r <= system_insn & (&{io_rw_addr[2], _GEN_0[3], _GEN_0[4], _GEN_0[5], _GEN_0[6], _GEN_0[7], io_rw_addr[8], io_rw_addr[9], _GEN_0[10], _GEN_0[11]}) | io_status_cease_r;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:882:31, :899:83, :1170:31, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
    end
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_44))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1042:20, :1232:18, :1338:{42,52}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_dpc <= _GEN_8;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:489:20, :1290:51]
    else if (_GEN_6)	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26, :1042:20, :1043:24, :1044:25, :1046:19]
      reg_dpc <= epc;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:489:20, :1680:31]
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_45))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:490:26, :1232:18, :1339:{43,59}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_dscratch0 <= wdata;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:490:26, :1659:39]
    reg_singleStepped <= io_singleStep & (io_retire | exception | reg_singleStepped);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:492:30, :1008:34, :1027:43, :1034:{22,36,56}, :1035:{25,45}]
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_2))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:501:20, :1232:18, :1289:{40,50}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_mie <= {48'h0, _wdata_T_2[15:0] & _wdata_T_6[15:0] & 16'h888};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:501:20, :1289:59, :1659:{30,39,41}]
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_35))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1042:20, :1232:18, :1290:{40,51}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_mepc <= _GEN_8;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:511:21, :1290:51]
    else if (_GEN_7) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :511:21, :1042:20, :1043:24]
    end
    else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:511:21, :1042:20, :1043:24]
      reg_mepc <= epc;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:511:21, :1680:31]
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_37))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1042:20, :1232:18, :1295:{40,52}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_mtval <= _wdata_T_2[33:0] & _wdata_T_6[33:0];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:513:22, :1295:52, :1659:{30,39,41}]
    else if (_GEN_7) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:398:12, :513:22, :1042:20, :1043:24]
    end
    else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:513:22, :1042:20, :1043:24]
      reg_mtval <= insn_break ? epc : io_tval;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:513:22, :899:83, :1040:17, :1680:31]
    if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_34))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:515:25, :1232:18, :1291:{40,55}, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
      reg_mscratch <= wdata;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:515:25, :1659:39]
  end // always @(posedge)
  wire [6:0]  nextSmall_1 = {1'h0, small_1} + {6'h0, ~(reg_wfi | io_status_cease_r)};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:581:54, :600:56, :1169:27, :1170:31, generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :46:33]
  always @(posedge io_ungated_clock) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
    if (reset) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
      reg_wfi <= 1'h0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:581:54]
      small_1 <= 6'h0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41]
      large_1 <= 58'h0;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
    end
    else begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:385:14]
      reg_wfi <= ~((|{_GEN[11], _GEN[7], _GEN[3]}) | io_interrupts_debug | exception) & (system_insn & (&{io_rw_addr[8], _GEN_0[9], _GEN_0[10], _GEN_0[11]}) & ~io_singleStep & ~reg_debug | reg_wfi);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:488:26, :581:54, :620:56, :632:36, :882:31, :899:83, :933:45, :1008:34, :1027:43, :1030:{18,36,51,61}, :1031:{28,32,55,69,79}, src/main/scala/chisel3/util/pla.scala:78:21, :90:45, :91:29, :98:{53,70}]
      if (csr_wen & (&_decoded_addr_decoded_decoded_andMatrixOutputs_T_46)) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1232:18, :1677:31, generators/rocket-chip/src/main/scala/util/Counters.scala:47:19, :67:11, generators/rocket-chip/src/main/scala/util/package.scala:81:59, src/main/scala/chisel3/util/pla.scala:98:{53,70}]
        small_1 <= _GEN_3;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:39, generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :67:11]
        large_1 <= _wdata_T_2[63:6] & _wdata_T_6[63:6];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1659:{30,39,41}, generators/rocket-chip/src/main/scala/util/Counters.scala:50:31, :68:28]
      end
      else begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:1232:18, :1677:31, generators/rocket-chip/src/main/scala/util/Counters.scala:47:19, :67:11]
        if (reg_mcountinhibit[0]) begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :597:40]
        end
        else	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:597:40]
          small_1 <= nextSmall_1[5:0];	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :46:33, :47:27]
        if (nextSmall_1[6] & ~(reg_mcountinhibit[0]))	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:596:34, :597:40, generators/rocket-chip/src/main/scala/util/Counters.scala:46:33, :47:9, :51:{20,33}]
          large_1 <= large_1 + 58'h1;	// @[generators/rocket-chip/src/main/scala/util/Counters.scala:50:31, :51:55]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:84];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
    initial begin	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
        `INIT_RANDOM_PROLOG_	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
        for (logic [6:0] i = 7'h0; i < 7'h55; i += 7'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
        end	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
        reg_mstatus_v = _RANDOM[7'h1][8];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_mstatus_mpv = _RANDOM[7'h2][1];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_mstatus_gva = _RANDOM[7'h2][2];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_mstatus_mpp = _RANDOM[7'h2][29:28];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_mstatus_mpie = _RANDOM[7'h3][1];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_mstatus_mie = _RANDOM[7'h3][5];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12]
        reg_dcsr_ebreakm = _RANDOM[7'h3][25];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :398:12, :409:25]
        reg_dcsr_cause = _RANDOM[7'h4][2:0];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :409:25]
        reg_dcsr_v = _RANDOM[7'h4][3];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :409:25]
        reg_dcsr_step = _RANDOM[7'h4][6];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :409:25]
        reg_debug = _RANDOM[7'h4][9];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :409:25, :488:26]
        reg_dpc = {_RANDOM[7'h4][31:10], _RANDOM[7'h5][11:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :409:25, :489:20]
        reg_dscratch0 = {_RANDOM[7'h5][31:12], _RANDOM[7'h6], _RANDOM[7'h7][11:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :489:20, :490:26]
        reg_singleStepped = _RANDOM[7'h7][12];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :490:26, :492:30]
        reg_mie = {_RANDOM[7'h10][31:22], _RANDOM[7'h11], _RANDOM[7'h12][21:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :501:20]
        reg_mepc = {_RANDOM[7'h17][31:6], _RANDOM[7'h18][7:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :511:21]
        reg_mcause = {_RANDOM[7'h18][31:8], _RANDOM[7'h19], _RANDOM[7'h1A][7:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :511:21, :512:27]
        reg_mtval = {_RANDOM[7'h1A][31:8], _RANDOM[7'h1B][9:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :512:27, :513:22]
        reg_mscratch = {_RANDOM[7'h1C][31:18], _RANDOM[7'h1D], _RANDOM[7'h1E][17:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :515:25]
        reg_mtvec = {_RANDOM[7'h1E][31:18], _RANDOM[7'h1F][17:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :515:25, :518:31]
        reg_wfi = _RANDOM[7'h4D][22];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :581:54]
        reg_mcountinhibit = _RANDOM[7'h4E][3:1];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :596:34]
        small_0 = _RANDOM[7'h4E][9:4];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :596:34, generators/rocket-chip/src/main/scala/util/Counters.scala:45:41]
        large_0 = {_RANDOM[7'h4E][31:10], _RANDOM[7'h4F], _RANDOM[7'h50][3:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :596:34, generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
        small_1 = _RANDOM[7'h50][9:4];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, generators/rocket-chip/src/main/scala/util/Counters.scala:45:41, :50:31]
        large_1 = {_RANDOM[7'h50][31:10], _RANDOM[7'h51], _RANDOM[7'h52][3:0]};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, generators/rocket-chip/src/main/scala/util/Counters.scala:50:31]
        io_status_cease_r = _RANDOM[7'h54][4];	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :1170:31]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_rw_rdata = _io_rw_rdata_T_224;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_eret = _exception_T | insn_ret;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :899:83, :1006:{24,38}]
  assign io_evec = insn_ret ? {_GEN_2 ? reg_dpc[33:2] : reg_mepc[33:2], 2'h0} : trapToDebug ? {22'h0, reg_debug ? {8'h80, ~insn_break, 3'h0} : 12'h800} : {2'h0, _read_mtvec_T_5[0] & cause[63] & cause[7:6] == 2'h0 ? {_read_mtvec_T_5[31:8], cause[5:0]} : _read_mtvec_T_5[31:2], 2'h0};	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :488:26, :489:20, :511:21, :899:83, :965:8, :967:25, :968:31, :969:30, :972:{56,75,98,119}, :975:{22,37}, :986:{27,33}, :987:{24,28,55,70,94}, :988:{8,38}, :1001:17, :1002:11, :1122:19, :1124:48, :1141:{48,66}, :1145:15, :1146:65, generators/rocket-chip/src/main/scala/util/package.scala:174:35]
  assign io_time = io_time_0;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, generators/rocket-chip/src/main/scala/util/Counters.scala:55:30]
  assign io_interrupt = ((io_interrupts_debug | m_interrupts[15] | m_interrupts[14] | m_interrupts[13] | m_interrupts[12] | m_interrupts[11] | m_interrupts[3] | m_interrupts[7] | m_interrupts[9] | m_interrupts[1] | m_interrupts[5] | m_interrupts[10] | m_interrupts[2] | m_interrupts[6] | m_interrupts[8] | m_interrupts[0] | m_interrupts[4]) & ~io_singleStep | reg_singleStepped) & ~(reg_debug | io_status_cease_r);	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :488:26, :492:30, :626:25, :632:{33,36,51,73,76,88}, :1008:34, :1170:31, :1653:{76,90}]
  assign io_interrupt_cause = {60'h0, io_interrupts_debug ? 4'hE : m_interrupts[15] ? 4'hF : m_interrupts[14] ? 4'hE : m_interrupts[13] ? 4'hD : m_interrupts[12] ? 4'hC : m_interrupts[11] ? 4'hB : m_interrupts[3] ? 4'h3 : m_interrupts[7] ? 4'h7 : m_interrupts[9] ? 4'h9 : m_interrupts[1] ? 4'h1 : m_interrupts[5] ? 4'h5 : m_interrupts[10] ? 4'hA : m_interrupts[2] ? 4'h2 : m_interrupts[6] ? 4'h6 : m_interrupts[8] ? 4'h8 : {1'h0, ~(m_interrupts[0]), 2'h0}} - 64'h8000000000000000;	// @[generators/rocket-chip/src/main/scala/rocket/CSR.scala:377:7, :626:25, :631:63, :1653:76, src/main/scala/chisel3/util/Mux.scala:50:70]
endmodule

