// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module Sodor_MemReader(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:13]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:13]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:13]
  input  [18:0] io_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [2:0]  io_size,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input         io_signed,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  output [63:0] io_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  output [15:0] io_mem_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_0,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_1,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_2,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_3,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_4,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_5,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_6,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
  input  [7:0]  io_mem_data_7	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:129:21]
);

  wire [63:0] alignedWord = {io_mem_data_7, io_mem_data_6, io_mem_data_5, io_mem_data_4, io_mem_data_3, io_mem_data_2, io_mem_data_1, io_mem_data_0} >> {58'h0, io_addr[2:0], 3'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:139:46, :150:{31,49}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:151:16]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:151:16]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:151:16]
        $fwrite(32'h80000002, "MemReader: addr %x size %d signed %d mem_addr %x readVec %x alignedWord %x (s_offset << 3) %x\n", io_addr, io_size, io_signed, io_addr[18:3], {io_mem_data_0, io_mem_data_1, io_mem_data_2, io_mem_data_3, io_mem_data_4, io_mem_data_5, io_mem_data_6, io_mem_data_7}, alignedWord, {io_addr[2:0], 3'h0});	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:139:46, :144:32, :150:{49,62}, :151:{16,161}]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _signedOut_T = io_size == 3'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:167:15]
  wire        _signedOut_T_3 = io_size == 3'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:168:15]
  wire        _signedOut_T_6 = io_size == 3'h2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:169:15]
  wire        _signedOut_T_11 = io_size == 3'h3;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:170:43]
  wire [63:0] low = (_signedOut_T ? alignedWord & 64'hFF : 64'h0) | (_signedOut_T_3 ? alignedWord & 64'hFFFF : 64'h0) | (_signedOut_T_6 ? alignedWord & 64'hFFFFFFFF : 64'h0) | (_signedOut_T_11 ? alignedWord : 64'h0);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:49, :167:{15,40}, :168:{15,40}, :169:{15,40}, :170:43, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_data = io_signed ? (_signedOut_T ? {{56{low[7]}}, low[7:0]} : 64'h0) | (_signedOut_T_3 ? {{48{low[15]}}, low[15:0]} : 64'h0) | (_signedOut_T_6 ? {{32{low[31]}}, low[31:0]} : 64'h0) | (_signedOut_T_11 ? low : 64'h0) : low;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:13, :167:15, :168:15, :169:15, :170:43, :174:{27,42}, :175:{27,42}, :187:{36,48}, :188:{36,48}, :189:{64,69,84,94}, :193:24, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_mem_addr = io_addr[18:3];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:13, :144:32]
endmodule

