// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module Sodor_mem_65536x64(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  input  [15:0] R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [15:0] R1_addr,
  input         R1_en,
  input         R1_clk,
  output [63:0] R1_data,
  input  [15:0] R2_addr,
  input         R2_en,
  input         R2_clk,
  output [63:0] R2_data,
  input  [15:0] R3_addr,
  input         R3_en,
  input         R3_clk,
  output [63:0] R3_data,
  input  [15:0] W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data,
  input  [7:0]  W0_mask,
  input  [15:0] W1_addr,
  input         W1_en,
  input         W1_clk,
  input  [63:0] W1_data,
  input  [7:0]  W1_mask
);

  reg [63:0] Memory[0:65535];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  always @(posedge W0_clk) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[0])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h0 +: 8] <= W0_data[7:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[1])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h8 +: 8] <= W0_data[15:8];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[2])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h10 +: 8] <= W0_data[23:16];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[3])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h18 +: 8] <= W0_data[31:24];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[4])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h20 +: 8] <= W0_data[39:32];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[5])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h28 +: 8] <= W0_data[47:40];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[6])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h30 +: 8] <= W0_data[55:48];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W0_en & W0_mask[7])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W0_addr][32'h38 +: 8] <= W0_data[63:56];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[0])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h0 +: 8] <= W1_data[7:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[1])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h8 +: 8] <= W1_data[15:8];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[2])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h10 +: 8] <= W1_data[23:16];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[3])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h18 +: 8] <= W1_data[31:24];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[4])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h20 +: 8] <= W1_data[39:32];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[5])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h28 +: 8] <= W1_data[47:40];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[6])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h30 +: 8] <= W1_data[55:48];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    if (W1_en & W1_mask[7])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      Memory[W1_addr][32'h38 +: 8] <= W1_data[63:56];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    reg [63:0] _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
        for (logic [16:0] i = 17'h0; i < 17'h10000; i += 17'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
          end
          Memory[i[15:0]] = _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  assign R1_data = R1_en ? Memory[R1_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  assign R2_data = R2_en ? Memory[R2_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
  assign R3_data = R3_en ? Memory[R3_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:88:31]
endmodule

