// Generated by CIRCT firtool-1.75.0
module Arbiter1_LineBufferReadReq(	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  output       io_in_0_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input        io_in_0_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input  [2:0] io_in_0_bits_offset,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  input        io_out_ready,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output       io_out_valid,	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
  output [2:0] io_out_bits_offset	// @[src/main/scala/chisel3/util/Arbiter.scala:140:14]
);

  assign io_in_0_ready = io_out_ready;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  assign io_out_valid = io_in_0_valid;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
  assign io_out_bits_offset = io_in_0_bits_offset;	// @[src/main/scala/chisel3/util/Arbiter.scala:133:7]
endmodule

