// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module MemReader(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:103:13]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:103:13]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:103:13]
  input  [19:0] io_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input  [1:0]  io_size,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input         io_signed,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  output [31:0] io_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  output [17:0] io_mem_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input  [7:0]  io_mem_data_0,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input  [7:0]  io_mem_data_1,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input  [7:0]  io_mem_data_2,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
  input  [7:0]  io_mem_data_3	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:104:21]
);

  wire [31:0]     _shiftedVec_T_3 = {io_mem_data_3, io_mem_data_2, io_mem_data_1, io_mem_data_0} >> {27'h0, io_addr[1:0], 3'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:114:46, :122:{40,58}]
  wire [2:0]      bytes = (&io_size) ? 3'h7 : {1'h0, io_size == 2'h2 ? 2'h3 : {1'h0, io_size == 2'h1}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:84:62]
  wire [3:0][7:0] _GEN = {{_shiftedVec_T_3[7:0]}, {_shiftedVec_T_3[15:8]}, {_shiftedVec_T_3[23:16]}, {_shiftedVec_T_3[31:24]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:98:117, :122:58, :126:64]
  wire [14:0]     _masks_mask_T = 15'h1F << bytes;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:84:62, :92:41]
  wire            _maskedVec_T_18 = _GEN[2'h3 - bytes[1:0]][7] & io_signed;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:84:62, :126:{50,64}, :130:22]
  wire [7:0]      _maskedVec_T_4 = {8{_masks_mask_T[7]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:92:{41,56}, :94:25, :130:47]
  wire [7:0]      _maskedVec_T_10 = {8{_masks_mask_T[6]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:92:{41,56}, :94:25, :130:47]
  wire [7:0]      _maskedVec_T_16 = {8{_masks_mask_T[5]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:92:{41,56}, :94:25, :130:47]
  wire [7:0]      _maskedVec_T_22 = {8{_masks_mask_T[4]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:92:{41,56}, :94:25, :130:47]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:132:16]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:132:16]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:132:16]
        $fwrite(32'h80000002, "Read Mem addr %x io.addr %x addrWidth %x size %x \n", io_addr[19:2], io_addr, 5'h14, io_size);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:119:32, :132:16]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_data = {_maskedVec_T_18 ? _shiftedVec_T_3[31:24] | ~_maskedVec_T_4 : _shiftedVec_T_3[31:24] & _maskedVec_T_4, _maskedVec_T_18 ? _shiftedVec_T_3[23:16] | ~_maskedVec_T_10 : _shiftedVec_T_3[23:16] & _maskedVec_T_10, _maskedVec_T_18 ? _shiftedVec_T_3[15:8] | ~_maskedVec_T_16 : _shiftedVec_T_3[15:8] & _maskedVec_T_16, _maskedVec_T_18 ? _shiftedVec_T_3[7:0] | ~_maskedVec_T_22 : _shiftedVec_T_3[7:0] & _maskedVec_T_22};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:98:117, :103:13, :122:58, :130:{16,22,40,42,47,63}, :133:24]
  assign io_mem_addr = io_addr[19:2];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:103:13, :119:32]
endmodule

