// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module SodorRequestRouter(	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  output        io_masterPort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_masterPort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_masterPort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_masterPort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [2:0]  io_masterPort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_masterPort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_masterPort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_scratchPort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_scratchPort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_scratchPort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_scratchPort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [2:0]  io_scratchPort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_scratchPort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_scratchPort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_corePort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_corePort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_corePort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_corePort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [2:0]  io_corePort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_corePort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_corePort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_respAddress	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
);

  wire cache_address_in_range = io_corePort_req_bits_addr[31:21] == 11'h400;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:87:11]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:87:11]
      if ((`PRINTF_COND_) & io_corePort_req_valid & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:87:11]
        $fwrite(32'h80000002, "Address %x is in_range? %x \n", io_corePort_req_bits_addr, cache_address_in_range);	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:87:11, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:59]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire resp_in_range = io_respAddress[31:21] == 11'h400;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}]
  assign io_masterPort_req_valid = io_corePort_req_valid & ~cache_address_in_range;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :96:{52,54}, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:59]
  assign io_masterPort_req_bits_addr = io_corePort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_data = io_corePort_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_fcn = io_corePort_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_typ = io_corePort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_valid = io_corePort_req_valid & cache_address_in_range;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :97:53, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:59]
  assign io_scratchPort_req_bits_addr = io_corePort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_data = io_corePort_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_fcn = io_corePort_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_typ = io_corePort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_corePort_resp_valid = resp_in_range ? io_scratchPort_resp_valid : io_masterPort_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :104:32, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}]
  assign io_corePort_resp_bits_data = resp_in_range ? io_scratchPort_resp_bits_data : io_masterPort_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :103:31, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}]
endmodule

