// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module Vincent_MemReader(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input  [6:0]  io_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [1:0]  io_size,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input         io_signed,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  output [31:0] io_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  output [4:0]  io_mem_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_0,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_1,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_2,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_3	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
);

  wire [31:0] alignedWord = {io_mem_data_3, io_mem_data_2, io_mem_data_1, io_mem_data_0} >> {27'h0, io_addr[1:0], 3'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:138:46, :149:{31,49}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16]
        $fwrite(32'h80000002, "MemReader: addr %x size %d signed %d mem_addr %x readVec %x alignedWord %x (s_offset << 3) %x\n", io_addr, io_size, io_signed, io_addr[6:2], {io_mem_data_0, io_mem_data_1, io_mem_data_2, io_mem_data_3}, alignedWord, {io_addr[1:0], 3'h0});	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:138:46, :143:32, :149:{49,62}, :150:{16,161}]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire        _signedOut_T = io_size == 2'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:166:15]
  wire        _signedOut_T_3 = io_size == 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:167:15]
  wire        _signedOut_T_6 = io_size == 2'h2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:168:15]
  wire [31:0] low = (_signedOut_T ? alignedWord & 32'hFF : 32'h0) | (_signedOut_T_3 ? alignedWord & 32'hFFFF : 32'h0) | (_signedOut_T_6 ? alignedWord : 32'h0);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:149:49, :166:{15,40}, :167:{15,40}, :168:15, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_data = io_signed ? (_signedOut_T ? {{24{low[7]}}, low[7:0]} : 32'h0) | (_signedOut_T_3 ? {{16{low[15]}}, low[15:0]} : 32'h0) | (_signedOut_T_6 ? low : 32'h0) : low;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13, :166:15, :167:15, :168:15, :173:{27,42}, :174:{27,42}, :176:{36,48}, :177:{36,48}, :182:21, src/main/scala/chisel3/util/Mux.scala:30:73]
  assign io_mem_addr = io_addr[6:2];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13, :143:32]
endmodule

