// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module Vincent_SodorRequestRouter(	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  output        io_masterPort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_masterPort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_masterPort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_masterPort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [2:0]  io_masterPort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_masterPort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_masterPort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_scratchPort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_scratchPort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_scratchPort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_scratchPort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [2:0]  io_scratchPort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_scratchPort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_scratchPort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_corePort_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_corePort_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_corePort_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input         io_corePort_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [2:0]  io_corePort_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output        io_corePort_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  output [31:0] io_corePort_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
  input  [31:0] io_respAddress	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:77:14]
);

  wire in_range = (|(io_corePort_req_bits_addr[31:16])) & io_corePort_req_bits_addr < 32'h10080;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:88:{23,32,40}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:91:11]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:91:11]
      if ((`PRINTF_COND_) & io_corePort_req_valid & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:91:11]
        $fwrite(32'h80000002, "SodorRequestRouter: addr %x in_range %d\n", io_corePort_req_bits_addr, in_range);	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:88:32, :91:11]
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire resp_in_range = {io_respAddress[31:17], io_respAddress[16:13] ^ 4'h8} == 19'h0;	// @[generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:138:{31,41,46,59}]
  assign io_masterPort_req_valid = io_corePort_req_valid & ~in_range;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :88:32, :99:{52,54}]
  assign io_masterPort_req_bits_addr = io_corePort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_data = io_corePort_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_fcn = io_corePort_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_masterPort_req_bits_typ = io_corePort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_valid = io_corePort_req_valid & in_range;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :88:32, :100:53]
  assign io_scratchPort_req_bits_addr = io_corePort_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_data = io_corePort_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_fcn = io_corePort_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_scratchPort_req_bits_typ = io_corePort_req_bits_typ;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7]
  assign io_corePort_resp_valid = resp_in_range ? io_scratchPort_resp_valid : io_masterPort_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :107:32, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:138:{41,46,59}]
  assign io_corePort_resp_bits_data = resp_in_range ? io_scratchPort_resp_bits_data : io_masterPort_resp_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/scratchpad_adapter.scala:76:7, :106:31, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:138:{41,46,59}]
endmodule

