// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomWritebackUnit(	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
  output        io_req_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input  [24:0] io_req_bits_tag,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_req_bits_idx,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input  [2:0]  io_req_bits_param,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input  [1:0]  io_req_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_req_bits_voluntary,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_meta_read_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_meta_read_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_meta_read_bits_idx,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [24:0] io_meta_read_bits_tag,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_resp,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_idx_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_idx_bits,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_data_req_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_data_req_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [1:0]  io_data_req_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [6:0]  io_data_req_bits_addr,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input  [63:0] io_data_resp,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_mem_grant,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_release_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_release_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [2:0]  io_release_bits_opcode,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [2:0]  io_release_bits_param,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [31:0] io_release_bits_address,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [63:0] io_release_bits_data,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  input         io_lsu_release_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output        io_lsu_release_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
  output [31:0] io_lsu_release_bits_address	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:25:14]
);

  reg  [24:0]      req_tag;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
  reg              req_idx;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
  reg  [2:0]       req_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
  reg  [1:0]       req_way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
  reg              req_voluntary;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
  reg  [2:0]       state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
  reg              r1_data_req_fired;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:40:34]
  reg              r2_data_req_fired;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34]
  reg  [3:0]       r1_data_req_cnt;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:42:28]
  reg  [3:0]       r2_data_req_cnt;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:43:28]
  reg  [3:0]       data_req_cnt;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29]
  reg  [63:0]      wb_buffer_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_2;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_3;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_4;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_5;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_6;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg  [63:0]      wb_buffer_7;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
  reg              acked;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:48:22]
  wire [31:0]      r_address = {req_tag, req_idx, 6'h0};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16, :64:41]
  wire [7:0][63:0] _GEN = {{wb_buffer_7}, {wb_buffer_6}, {wb_buffer_5}, {wb_buffer_4}, {wb_buffer_3}, {wb_buffer_2}, {wb_buffer_1}, {wb_buffer_0}};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:441:15]
  wire             io_req_ready_0 = state == 3'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :81:15]
  wire             _GEN_0 = state == 3'h1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :89:22]
  wire             io_data_req_valid_0 = ~io_req_ready_0 & _GEN_0 & ~(data_req_cnt[3]);	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :55:22, :81:{15,30}, :89:{22,41}, :90:{24,40}]
  wire             _GEN_1 = r2_data_req_cnt == 4'h7;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:43:28, :111:29]
  wire             _GEN_2 = state == 3'h2;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :117:22]
  wire             io_lsu_release_valid_0 = ~(io_req_ready_0 | _GEN_0) & _GEN_2;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:60:24, :81:{15,30}, :89:{22,41}, :117:{22,41}]
  wire             _GEN_3 = state == 3'h3;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :123:22]
  wire             _GEN_4 = _GEN_0 | _GEN_2;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:52:22, :89:{22,41}, :117:{22,41}, :123:36]
  wire             io_release_valid_0 = ~(io_req_ready_0 | _GEN_4) & _GEN_3 & ~(data_req_cnt[3]);	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :52:22, :81:{15,30}, :89:41, :90:40, :117:41, :123:{22,36}, :124:{22,38}]
  wire             _GEN_5 = io_release_ready & io_release_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:52:22, :81:30, :89:41, :117:41, :123:36, :124:22, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_6 = state == 3'h4;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :136:22]
  wire             _GEN_7 = io_req_ready_0 & io_req_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:81:15, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire             _GEN_8 = io_req_ready_0 | ~_GEN_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :81:{15,30}, :89:{22,41}]
  wire             _GEN_9 = io_data_req_ready & io_data_req_valid_0 & io_meta_read_ready;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:55:22, :81:30, :89:41, :90:24, :104:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
    if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_tag <= io_req_bits_tag;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
      req_idx <= io_req_bits_idx;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
      req_param <= io_req_bits_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
      req_way_en <= io_req_bits_way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
      req_voluntary <= io_req_bits_voluntary;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16]
    end
    if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :81:30, :89:41]
    end
    else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:43:28, :81:30, :89:41]
      r1_data_req_cnt <= _GEN_9 ? data_req_cnt : 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:42:28, :44:29, :101:23, :104:{28,50}, :106:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      r2_data_req_cnt <= r1_data_req_cnt;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:42:28, :43:28]
    end
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h0)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_0 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h1)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_1 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h2)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_2 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h3)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_3 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h4)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_4 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h5)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_5 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & r2_data_req_cnt[2:0] == 3'h6)) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_6 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (io_req_ready_0 | ~(_GEN_0 & r2_data_req_fired & (&(r2_data_req_cnt[2:0])))) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :43:28, :47:22, :81:{15,30}, :89:{22,41}, :109:30, :110:34]
    end
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22, :81:30, :89:41]
      wb_buffer_7 <= io_data_resp;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:47:22]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      state <= 3'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
      r1_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:40:34]
      r2_data_req_fired <= 1'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34]
      data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29]
      acked <= 1'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:48:22]
    end
    else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      if (io_req_ready_0) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:81:15]
        if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
          state <= 3'h1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
          data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29]
        end
        acked <= ~_GEN_7 & acked;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:48:22, :83:24, :87:13, src/main/scala/chisel3/util/Decoupled.scala:51:35]
      end
      else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:81:15]
        if (_GEN_0) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:89:22]
          if (r2_data_req_fired & _GEN_1) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :41:34, :109:30, :111:{29,53}, :113:15]
            state <= 3'h2;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
            data_req_cnt <= 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29]
          end
          else if (_GEN_9)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:104:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
            data_req_cnt <= data_req_cnt + 4'h1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :107:36]
        end
        else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:89:22]
          if (_GEN_2) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:117:22]
            if (io_lsu_release_ready & io_lsu_release_valid_0)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:60:24, :81:30, :89:41, :117:41, src/main/scala/chisel3/util/Decoupled.scala:51:35]
              state <= 3'h3;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
          end
          else if (_GEN_3) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:123:22]
            if (data_req_cnt == 4'h7 & _GEN_5)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :133:{25,49}, src/main/scala/chisel3/util/Decoupled.scala:51:35]
              state <= {req_voluntary, 2'h0};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:37:16, :39:22, :134:19]
          end
          else if (_GEN_6 & acked)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22, :48:22, :136:{22,35}, :140:18, :141:13]
            state <= 3'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:39:22]
          if (_GEN_2 | ~_GEN_5) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :117:{22,41}, :123:36, src/main/scala/chisel3/util/Decoupled.scala:51:35]
          end
          else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :117:41, :123:36]
            data_req_cnt <= data_req_cnt + 4'h1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:44:29, :131:36]
        end
        if (~_GEN_4)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:52:22, :89:41, :117:41, :123:36]
          acked <= _GEN_3 ? io_mem_grant | acked : _GEN_6 & io_mem_grant | acked;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:48:22, :123:{22,36}, :127:25, :128:13, :136:{22,35}, :137:25, :138:13]
      end
      if (_GEN_8) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :81:30, :89:41]
      end
      else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:41:34, :81:30, :89:41]
        r1_data_req_fired <= _GEN_9;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:40:34, :104:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
        r2_data_req_fired <= r1_data_req_fired;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:40:34, :41:34]
      end
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:17];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
    initial begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
        for (logic [4:0] i = 5'h0; i < 5'h12; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
        end	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
        req_tag = _RANDOM[5'h0][24:0];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
        req_idx = _RANDOM[5'h0][25];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
        req_param = _RANDOM[5'h0][30:28];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
        req_way_en = {_RANDOM[5'h0][31], _RANDOM[5'h1][0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
        req_voluntary = _RANDOM[5'h1][1];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
        state = _RANDOM[5'h1][4:2];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :39:22]
        r1_data_req_fired = _RANDOM[5'h1][5];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :40:34]
        r2_data_req_fired = _RANDOM[5'h1][6];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :41:34]
        r1_data_req_cnt = _RANDOM[5'h1][10:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :42:28]
        r2_data_req_cnt = _RANDOM[5'h1][14:11];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :43:28]
        data_req_cnt = _RANDOM[5'h1][18:15];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :44:29]
        wb_buffer_0 = {_RANDOM[5'h1][31:28], _RANDOM[5'h2], _RANDOM[5'h3][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :47:22]
        wb_buffer_1 = {_RANDOM[5'h3][31:28], _RANDOM[5'h4], _RANDOM[5'h5][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_2 = {_RANDOM[5'h5][31:28], _RANDOM[5'h6], _RANDOM[5'h7][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_3 = {_RANDOM[5'h7][31:28], _RANDOM[5'h8], _RANDOM[5'h9][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_4 = {_RANDOM[5'h9][31:28], _RANDOM[5'hA], _RANDOM[5'hB][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_5 = {_RANDOM[5'hB][31:28], _RANDOM[5'hC], _RANDOM[5'hD][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_6 = {_RANDOM[5'hD][31:28], _RANDOM[5'hE], _RANDOM[5'hF][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        wb_buffer_7 = {_RANDOM[5'hF][31:28], _RANDOM[5'h10], _RANDOM[5'h11][27:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22]
        acked = _RANDOM[5'h11][28];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :47:22, :48:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :81:15]
  assign io_meta_read_valid = io_data_req_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :55:22, :81:30, :89:41, :90:24]
  assign io_meta_read_bits_idx = req_idx;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
  assign io_meta_read_bits_tag = req_tag;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
  assign io_resp = ~io_req_ready_0 & _GEN_0 & r2_data_req_fired & _GEN_1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :41:34, :55:22, :59:22, :81:{15,30}, :89:{22,41}, :109:30, :111:{29,53}]
  assign io_idx_valid = |state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :39:22, :50:31]
  assign io_idx_bits = req_idx;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
  assign io_data_req_valid = io_data_req_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :55:22, :81:30, :89:41, :90:24]
  assign io_data_req_bits_way_en = req_way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
  assign io_data_req_bits_addr = {req_idx, data_req_cnt[2:0], 3'h0};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :44:29, :98:43]
  assign io_release_valid = io_release_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :52:22, :81:30, :89:41, :117:41, :123:36, :124:22]
  assign io_release_bits_opcode = {1'h1, req_voluntary, 1'h1};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16, :125:27]
  assign io_release_bits_param = req_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :37:16]
  assign io_release_bits_address = r_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :64:41]
  assign io_release_bits_data = _GEN[data_req_cnt[2:0]];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :44:29, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:441:15]
  assign io_lsu_release_valid = io_lsu_release_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :60:24, :81:30, :89:41, :117:41]
  assign io_lsu_release_bits_address = r_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:24:7, :64:41]
endmodule

