// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BoomProbeUnit(	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
  output        io_req_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_req_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [1:0]  io_req_bits_param,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [3:0]  io_req_bits_size,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [1:0]  io_req_bits_source,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [31:0] io_req_bits_address,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_rep_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_rep_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [2:0]  io_rep_bits_param,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [3:0]  io_rep_bits_size,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [1:0]  io_rep_bits_source,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [31:0] io_rep_bits_address,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_meta_read_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_meta_read_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_meta_read_bits_idx,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [24:0] io_meta_read_bits_tag,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_meta_write_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_meta_write_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_meta_write_bits_idx,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [1:0]  io_meta_write_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [1:0]  io_meta_write_bits_data_coh_state,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [24:0] io_meta_write_bits_data_tag,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_wb_req_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_wb_req_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [24:0] io_wb_req_bits_tag,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_wb_req_bits_idx,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [2:0]  io_wb_req_bits_param,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [1:0]  io_wb_req_bits_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [1:0]  io_way_en,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_wb_rdy,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_mshr_rdy,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_mshr_wb_rdy,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input  [1:0]  io_block_state_state,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  input         io_lsu_release_ready,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_lsu_release_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [31:0] io_lsu_release_bits_address,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output        io_state_valid,	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
  output [39:0] io_state_bits	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:147:14]
);

  reg  [3:0]       state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22]
  reg  [1:0]       req_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
  reg  [3:0]       req_size;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
  reg  [1:0]       req_source;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
  reg  [31:0]      req_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
  reg  [1:0]       way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:172:19]
  reg  [1:0]       old_coh_state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:174:20]
  wire [3:0]       _r_T = {req_param, (|way_en) ? old_coh_state : 2'h0};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :172:19, :173:28, :174:20, :176:22, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19]
  wire             _r_T_26 = _r_T == 4'hB;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_29 = _r_T == 4'h4;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_33 = _r_T == 4'h5;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_37 = _r_T == 4'h6;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_41 = _r_T == 4'h7;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_45 = _r_T == 4'h0;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_49 = _r_T == 4'h1;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_53 = _r_T == 4'h2;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _r_T_57 = _r_T == 4'h3;	// @[generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:56:20]
  wire             _GEN = _r_T_57 | _r_T_53;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire [2:0]       report_param = _GEN ? 3'h3 : _r_T_49 ? 3'h4 : _r_T_45 ? 3'h5 : _r_T_41 | _r_T_37 ? 3'h0 : _r_T_33 ? 3'h4 : _r_T_29 ? 3'h5 : _r_T_26 | _r_T == 4'hA ? 3'h1 : _r_T == 4'h9 ? 3'h2 : _r_T == 4'h8 ? 3'h5 : 3'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, generators/rocket-chip/src/main/scala/tilelink/Metadata.scala:120:19, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36, :56:20]
  wire             io_req_ready_0 = state == 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :182:25]
  wire             io_rep_valid_0 = state == 4'h6;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :183:25]
  wire             io_meta_read_valid_0 = state == 4'h1;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :189:31]
  wire             io_meta_write_valid_0 = state == 4'h9;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :194:32]
  wire             io_wb_req_valid_0 = state == 4'h7;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :201:28]
  wire             io_lsu_release_valid_0 = state == 4'h5;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :212:33]
  wire             _GEN_0 = io_req_ready_0 & io_req_valid;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:182:25, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  wire [15:0][3:0] _GEN_1 = {{state}, {state}, {state}, {state}, {state}, {4'h0}, {io_meta_write_ready & io_meta_write_valid_0 ? 4'hA : state}, {io_wb_req_ready ? 4'h9 : state}, {io_wb_req_ready & io_wb_req_valid_0 ? 4'h8 : state}, {io_rep_ready ? ((|way_en) ? 4'h9 : 4'h0) : state}, {io_lsu_release_ready & io_lsu_release_valid_0 ? 4'h6 : state}, {{2'h1, (|way_en) & (_r_T_57 | ~(_r_T_53 | _r_T_49 | _r_T_45) & (_r_T_41 | ~(_r_T_37 | _r_T_33 | _r_T_29) & _r_T_26)), 1'h1}}, {io_mshr_rdy & io_wb_rdy ? 4'h4 : 4'h1}, {4'h3}, {io_meta_read_ready & io_meta_read_valid_0 ? 4'h2 : state}, {_GEN_0 ? 4'h1 : state}};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :172:19, :173:28, :182:25, :183:25, :189:31, :194:32, :201:28, :212:33, :216:30, :217:24, :218:13, :221:39, :222:30, :223:13, :225:{22,39}, :227:11, :228:{22,38}, :232:{11,17,30}, :233:{22,39}, :234:{11,17,30}, :235:41, :236:32, :237:13, :239:37, :240:25, :241:{13,19}, :243:43, :244:27, :245:13, :247:44, :249:28, :250:13, :252:40, :253:31, :254:13, :256:45, :257:11, generators/rocket-chip/src/main/scala/util/Misc.scala:38:9, :56:20, generators/rocket-chip/src/main/scala/util/package.scala:16:47, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
    if (reset)	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      state <= 4'h0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22]
    else	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      state <= _GEN_1[state];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :182:25, :183:25, :189:31, :194:32, :201:28, :212:33, :216:30, :217:24, :221:39, :222:30, :225:{22,39}, :227:11, :228:{22,38}, :232:11, :233:{22,39}, :234:11, :235:41, :236:32, :239:37, :240:25, :243:43, :244:27, :247:44, :249:28, :252:40, :253:31, :256:45, :257:11, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
    if (_GEN_0) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      req_param <= io_req_bits_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
      req_size <= io_req_bits_size;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
      req_source <= io_req_bits_source;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
      req_address <= io_req_bits_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:168:16]
    end
    if (io_req_ready_0 | io_meta_read_valid_0 | state == 4'h2 | state != 4'h3) begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:166:22, :174:20, :182:25, :189:31, :216:30, :221:39, :225:{22,39}, :228:{22,38}]
    end
    else begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:174:20, :216:30, :221:39, :225:39, :228:38]
      way_en <= io_way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:172:19]
      old_coh_state <= io_block_state_state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:174:20]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:3];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
    initial begin	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
        for (logic [2:0] i = 3'h0; i < 3'h4; i += 3'h1) begin
          _RANDOM[i[1:0]] = `RANDOM;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
        end	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
        state = _RANDOM[2'h0][3:0];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22]
        req_param = _RANDOM[2'h0][8:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :168:16]
        req_size = _RANDOM[2'h0][12:9];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :168:16]
        req_source = _RANDOM[2'h0][14:13];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :168:16]
        req_address = {_RANDOM[2'h0][31:15], _RANDOM[2'h1][14:0]};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :168:16]
        way_en = _RANDOM[2'h3][25:24];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :172:19]
        old_coh_state = _RANDOM[2'h3][27:26];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :172:19, :174:20]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_req_ready = io_req_ready_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :182:25]
  assign io_rep_valid = io_rep_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :183:25]
  assign io_rep_bits_param = report_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_rep_bits_size = req_size;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16]
  assign io_rep_bits_source = req_source;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16]
  assign io_rep_bits_address = req_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16]
  assign io_meta_read_valid = io_meta_read_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :189:31]
  assign io_meta_read_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :169:28]
  assign io_meta_read_bits_tag = req_address[31:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :170:29]
  assign io_meta_write_valid = io_meta_write_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :194:32]
  assign io_meta_write_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :169:28]
  assign io_meta_write_bits_way_en = way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :172:19]
  assign io_meta_write_bits_data_coh_state = _GEN ? 2'h2 : _r_T_49 ? 2'h1 : _r_T_45 ? 2'h0 : {1'h0, _r_T_41 | _r_T_37 | _r_T_33};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, generators/rocket-chip/src/main/scala/util/Misc.scala:38:{36,63}, :56:20]
  assign io_meta_write_bits_data_tag = req_address[31:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :170:29]
  assign io_wb_req_valid = io_wb_req_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :201:28]
  assign io_wb_req_bits_tag = req_address[31:7];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :170:29]
  assign io_wb_req_bits_idx = req_address[6];	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :169:28]
  assign io_wb_req_bits_param = report_param;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, generators/rocket-chip/src/main/scala/util/Misc.scala:38:36]
  assign io_wb_req_bits_way_en = way_en;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :172:19]
  assign io_mshr_wb_rdy = ~(io_rep_valid_0 | io_wb_req_valid_0 | state == 4'h8 | io_meta_write_valid_0 | state == 4'hA);	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :183:25, :194:32, :201:28, :210:21, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  assign io_lsu_release_valid = io_lsu_release_valid_0;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :212:33]
  assign io_lsu_release_bits_address = req_address;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16]
  assign io_state_valid = |state;	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :166:22, :179:27]
  assign io_state_bits = {8'h0, req_address};	// @[generators/boom/src/main/scala/v3/lsu/dcache.scala:146:7, :168:16, :180:18]
endmodule

