// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Sodor_CtlPath(	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
  output        io_simulated_pipeline_buffer_enq_bits_was_write,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_simulated_pipeline_buffer_drain,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_imem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_dmem_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_dmem_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [2:0]  io_dmem_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dmem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input  [31:0] io_dat_inst,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_imiss,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_br_eq,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_br_lt,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_br_ltu,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_csr_eret,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_csr_interrupt,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_inst_misaligned,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_jump_target_too_high,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input  [2:0]  io_dat_mem_address_low,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_csr_read_illegal,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  input         io_dat_csr_system_illegal,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_ctl_stall,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_ctl_dmiss,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [2:0]  io_ctl_pc_sel,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [1:0]  io_ctl_op1_sel,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [1:0]  io_ctl_op2_sel,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [4:0]  io_ctl_alu_fun,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [1:0]  io_ctl_wb_sel,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_ctl_rf_wen,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [2:0]  io_ctl_csr_cmd,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output        io_ctl_exception,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [31:0] io_ctl_exception_cause,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
  output [2:0]  io_ctl_pc_sel_no_xept	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14]
);

  wire        io_ctl_exception_0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:253:{47,73,92}]
  wire        data_misaligned;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:241:70]
  wire [9:0]  _GEN = {io_dat_inst[14:12], io_dat_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_1 = _GEN == 10'h103;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_3 = _GEN == 10'h3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_5 = _GEN == 10'h203;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_7 = _GEN == 10'h83;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_9 = _GEN == 10'h283;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_11 = _GEN == 10'h123;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_13 = _GEN == 10'h23;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_15 = _GEN == 10'hA3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_17 = io_dat_inst[6:0] == 7'h17;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_19 = io_dat_inst[6:0] == 7'h37;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_21 = _GEN == 10'h13;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_23 = _GEN == 10'h393;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_25 = _GEN == 10'h313;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_27 = _GEN == 10'h213;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_29 = _GEN == 10'h113;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_31 = _GEN == 10'h193;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [16:0] _GEN_0 = {io_dat_inst[31:25], io_dat_inst[14:12], io_dat_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_33 = _GEN_0 == 17'h93;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_35 = _GEN_0 == 17'h8293;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_37 = _GEN_0 == 17'h293;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_39 = _GEN_0 == 17'hB3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_41 = _GEN_0 == 17'h33;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_43 = _GEN_0 == 17'h8033;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_45 = _GEN_0 == 17'h133;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_47 = _GEN_0 == 17'h1B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_49 = _GEN_0 == 17'h3B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_51 = _GEN_0 == 17'h333;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_53 = _GEN_0 == 17'h233;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_55 = _GEN_0 == 17'h82B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_57 = _GEN_0 == 17'h2B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_59 = io_dat_inst[6:0] == 7'h6F;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_61 = _GEN == 10'h67;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_63 = _GEN == 10'h63;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_65 = _GEN == 10'hE3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_67 = _GEN == 10'h2E3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_69 = _GEN == 10'h3E3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_71 = _GEN == 10'h263;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_73 = _GEN == 10'h363;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_75 = _GEN == 10'h2F3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_77 = _GEN == 10'h373;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_79 = _GEN == 10'h3F3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_81 = _GEN == 10'hF3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_83 = _GEN == 10'h173;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_85 = _GEN == 10'h1F3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_87 = io_dat_inst == 32'h73;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_89 = io_dat_inst == 32'h30200073;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_91 = io_dat_inst == 32'h7B200073;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_93 = io_dat_inst == 32'h100073;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_95 = io_dat_inst == 32'h10500073;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_97 = _GEN == 10'h8F;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_99 = _GEN == 10'hF;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_101 = _GEN_0 == 17'h433;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_103 = _GEN_0 == 17'h4B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_105 = _GEN_0 == 17'h533;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_107 = _GEN_0 == 17'h5B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_109 = _GEN_0 == 17'h633;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_111 = _GEN_0 == 17'h6B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_113 = _GEN_0 == 17'h733;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_115 = _GEN_0 == 17'h7B3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_117 = _GEN_0 == 17'h43B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_119 = _GEN_0 == 17'h63B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_121 = _GEN_0 == 17'h6BB;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_123 = _GEN_0 == 17'h73B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_125 = _GEN_0 == 17'h7BB;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire [15:0] _GEN_1 = {io_dat_inst[31:26], io_dat_inst[14:12], io_dat_inst[6:0]};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_127 = _GEN_1 == 16'h93;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_129 = _GEN == 10'h1B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_131 = _GEN_0 == 17'h9B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_133 = _GEN_0 == 17'h29B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_135 = _GEN_0 == 17'h829B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_137 = _GEN_0 == 17'h3B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_139 = _GEN_0 == 17'h803B;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_141 = _GEN_0 == 17'hBB;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_143 = _GEN_0 == 17'h2BB;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_145 = {io_dat_inst[31:25], io_dat_inst[14:12], io_dat_inst[6:0]} == 17'h82BB;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14, src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_147 = _GEN_1 == 16'h4293;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_149 = {io_dat_inst[31:26], io_dat_inst[14:12], io_dat_inst[6:0]} == 16'h293;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:47:14, src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_151 = _GEN == 10'h303;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_619 = _GEN == 10'h183;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _csignals_T_772 = _GEN == 10'h1A3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38]
  wire        _GEN_2 = _csignals_T_151 | _csignals_T_619;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_3 = _csignals_T_147 | _csignals_T_149 | _GEN_2;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_4 = _csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _csignals_T_59 | _csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69 | _csignals_T_71 | _csignals_T_73 | _csignals_T_75 | _csignals_T_77 | _csignals_T_79 | _csignals_T_81 | _csignals_T_83 | _csignals_T_85 | _csignals_T_87 | _csignals_T_89 | _csignals_T_91 | _csignals_T_93 | _csignals_T_95 | _csignals_T_97 | _csignals_T_99 | _csignals_T_101 | _csignals_T_103 | _csignals_T_105 | _csignals_T_107 | _csignals_T_109 | _csignals_T_111 | _csignals_T_113 | _csignals_T_115 | _csignals_T_117 | _csignals_T_119 | _csignals_T_121 | _csignals_T_123 | _csignals_T_125 | _csignals_T_127 | _csignals_T_129 | _csignals_T_131 | _csignals_T_133 | _csignals_T_135 | _csignals_T_137 | _csignals_T_139 | _csignals_T_141 | _csignals_T_143 | _csignals_T_145 | _GEN_3;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        csignals_0 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _GEN_4 | _csignals_T_772;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        valid_inst = csignals_0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:174:24, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire        _GEN_5 = _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_6 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _GEN_5;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [3:0]  csignals_1 = _GEN_6 ? 4'h0 : _csignals_T_59 ? 4'h7 : _csignals_T_61 ? 4'h8 : _csignals_T_63 ? 4'h2 : _csignals_T_65 ? 4'h1 : _csignals_T_67 ? 4'h3 : _csignals_T_69 ? 4'h4 : _csignals_T_71 ? 4'h5 : _csignals_T_73 ? 4'h6 : 4'h0;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_7 = _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69 | _csignals_T_71 | _csignals_T_73;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_8 = _csignals_T_59 | _csignals_T_61 | _GEN_7;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_9 = _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _GEN_8;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_10 = _csignals_T_11 | _csignals_T_13 | _csignals_T_15;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_11 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _GEN_10;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_12 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_13 = _csignals_T_619 | _csignals_T_772;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_14 = _csignals_T_87 | _csignals_T_89 | _csignals_T_91 | _csignals_T_93 | _csignals_T_95 | _csignals_T_97 | _csignals_T_99;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_15 = _csignals_T_75 | _csignals_T_77 | _csignals_T_79 | _csignals_T_81 | _csignals_T_83 | _csignals_T_85;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_16 = _csignals_T_87 | _csignals_T_89 | _csignals_T_91 | _csignals_T_93 | _csignals_T_95 | _csignals_T_97 | _csignals_T_99 | _csignals_T_101 | _csignals_T_103 | _csignals_T_105 | _csignals_T_107 | _csignals_T_109 | _csignals_T_111 | _csignals_T_113 | _csignals_T_115 | _csignals_T_117 | _csignals_T_119 | _csignals_T_121 | _csignals_T_123 | _csignals_T_125 | _csignals_T_127 | _csignals_T_129 | _csignals_T_131 | _csignals_T_133 | _csignals_T_135 | _csignals_T_137 | _csignals_T_139 | _csignals_T_141 | _csignals_T_143 | _csignals_T_145 | _csignals_T_147 | _csignals_T_149;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_17 = _csignals_T_59 | _csignals_T_61;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        csignals_6 = _GEN_12 | ~_GEN_10 & (_csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _GEN_17 | ~_GEN_7 & (_GEN_15 | ~_GEN_14 & (_csignals_T_101 | _csignals_T_103 | _csignals_T_105 | _csignals_T_107 | _csignals_T_109 | _csignals_T_111 | _csignals_T_113 | _csignals_T_115 | _csignals_T_117 | _csignals_T_119 | _csignals_T_121 | _csignals_T_123 | _csignals_T_125 | _csignals_T_127 | _csignals_T_129 | _csignals_T_131 | _csignals_T_133 | _csignals_T_135 | _csignals_T_137 | _csignals_T_139 | _csignals_T_141 | _csignals_T_143 | _csignals_T_145 | _csignals_T_147 | _csignals_T_149 | _csignals_T_151 | _csignals_T_619)));	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        _GEN_18 = _csignals_T_17 | _csignals_T_19 | _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 | _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _csignals_T_59 | _csignals_T_61 | _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69 | _csignals_T_71 | _csignals_T_73 | _csignals_T_75 | _csignals_T_77 | _csignals_T_79 | _csignals_T_81 | _csignals_T_83 | _csignals_T_85 | _GEN_16;	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        csignals_7 = _GEN_11 | ~_GEN_18 & (_GEN_2 | _csignals_T_772);	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        mem_store = ~_GEN_12 & (_GEN_10 | ~_GEN_4 & _csignals_T_772);	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [2:0]  csignals_9 = _csignals_T_1 ? 3'h3 : _csignals_T_3 ? 3'h1 : _csignals_T_5 ? 3'h5 : _csignals_T_7 ? 3'h2 : _csignals_T_9 ? 3'h6 : _csignals_T_11 ? 3'h3 : _csignals_T_13 ? 3'h1 : _csignals_T_15 ? 3'h2 : _GEN_18 ? 3'h0 : _csignals_T_151 ? 3'h7 : {_GEN_13, 2'h0};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire [2:0]  csignals_10 = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 | _csignals_T_19 | _GEN_9 ? 3'h0 : _csignals_T_75 ? 3'h5 : _csignals_T_77 ? 3'h6 : _csignals_T_79 ? 3'h7 : _csignals_T_81 ? 3'h5 : _csignals_T_83 ? 3'h6 : _csignals_T_85 ? 3'h7 : {_csignals_T_87 | _csignals_T_89 | _csignals_T_91 | _csignals_T_93, 2'h0};	// @[src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  wire        branching = |csignals_1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:170:{23,35}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire [2:0]  _ctrl_pc_sel_no_xept_T_26 = (|csignals_1) ? (csignals_1 == 4'h1 ? {2'h0, ~io_dat_br_eq} : csignals_1 == 4'h2 ? {2'h0, io_dat_br_eq} : csignals_1 == 4'h3 ? {2'h0, ~io_dat_br_lt} : csignals_1 == 4'h4 ? {2'h0, ~io_dat_br_ltu} : csignals_1 == 4'h5 ? {2'h0, io_dat_br_lt} : csignals_1 == 4'h6 ? {2'h0, io_dat_br_ltu} : csignals_1 == 4'h7 ? 3'h2 : csignals_1 == 4'h8 ? 3'h3 : 3'h0) : 3'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:170:35, :178:34, :179:{34,46,62,63}, :180:{34,46,62}, :181:{34,46,62,63}, :182:{34,46,62,63}, :183:{34,46,62}, :184:{34,46,62}, :185:{34,46}, :186:{34,46}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  reg         reg_mem_en;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:192:28]
  wire        mem_en = io_imem_resp_valid ? csignals_7 : reg_mem_en;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:192:28, :198:20, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire        _io_ctl_dmiss_T_3 = mem_en & (io_dmem_resp_valid | data_misaligned) | ~mem_en;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:198:20, :201:{30,53,74,77}, :241:70]
  wire        stall = io_dat_imiss | ~_io_ctl_dmiss_T_3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:201:{20,74}, :202:30]
  wire        my_commit_valid = ~stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:202:30, :215:26]
  wire [2:0]  csr_cmd = (csignals_10 == 3'h6 | (&csignals_10)) & io_dat_inst[19:15] == 5'h0 ? 3'h2 : csignals_10;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:221:30, :222:{30,40,54,65,77}, :223:21, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire        io_dmem_req_valid_0 = mem_en & ~io_ctl_exception_0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:198:20, :228:{35,38}, :253:{47,73,92}]
  wire        illegal = ~csignals_0 & io_imem_resp_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:174:37, :235:32, src/main/scala/chisel3/util/Lookup.scala:34:39]
  wire [5:0]  _misaligned_mask_T_3 = 6'h7 << csignals_9[1:0] - 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:240:{34,49}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign data_misaligned = (|(~(_misaligned_mask_T_3[2:0]) & io_dat_mem_address_low)) & mem_en;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:198:20, :240:{23,34}, :241:{40,66,70}]
  wire        csr_illegal = (|csr_cmd) & (io_dat_csr_read_illegal | io_dat_csr_system_illegal);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:223:21, :248:{31,42,70}]
  wire        _io_ctl_exception_cause_T = illegal | csr_illegal;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:235:32, :248:42, :253:32]
  assign io_ctl_exception_0 = _io_ctl_exception_cause_T | io_dat_inst_misaligned | data_misaligned | io_dat_jump_target_too_high;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:241:70, :253:{32,47,73,92}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:49:9]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:49:9]
      if ((`PRINTF_COND_) & ~reset) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:49:9, :254:10]
        $fwrite(32'h80000002, "Executing instruction: %x\n", io_dat_inst);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:49:9]
        $fwrite(32'h80000002, "MUL/DIV instructions are enabled.\n");	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:151:13]
        $fwrite(32'h80000002, "Stalling %x because imiss %x or dmiss %x \n", stall, io_dat_imiss, ~_io_ctl_dmiss_T_3);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:201:{20,74}, :202:30, :203:10]
        $fwrite(32'h80000002, "Dmiss reasons mem_en %x, io.dmem.resp.valid %x, data_misaligned %x \n", mem_en, io_dmem_resp_valid, data_misaligned);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:198:20, :204:10, :241:70]
        $fwrite(32'h80000002, "Sending memory request? io.ctl.exception %x mem_en %x io.dmem.req.valid %x \n", io_ctl_exception_0, mem_en, io_dmem_req_valid_0);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:198:20, :228:35, :231:10, :253:{47,73,92}]
        $fwrite(32'h80000002, "Exception in Sodor: %x cs_val_inst %x , inst_mis %x, csr_illegal %x\n", io_ctl_exception_0, csignals_0, io_dat_inst_misaligned, csr_illegal);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:248:42, :253:{47,73,92}, :254:10, src/main/scala/chisel3/util/Lookup.scala:34:39]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
    if (reset)	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      reg_mem_en <= 1'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :192:28]
    else	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      reg_mem_en <= ~io_dmem_resp_valid & (io_imem_resp_valid ? csignals_7 : reg_mem_en);	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:192:28, :193:30, :194:18, :195:37, :196:18, src/main/scala/chisel3/util/Lookup.scala:34:39]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
        `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
        reg_mem_en = _RANDOM[/*Zero width*/ 1'b0][0];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :192:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_simulated_pipeline_buffer_enq_bits_was_write = mem_store;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_simulated_pipeline_buffer_drain = (_GEN_6 ? 3'h0 : _GEN_8 ? 3'h1 : _GEN_15 ? 3'h0 : _csignals_T_87 | _csignals_T_89 ? 3'h1 : _csignals_T_91 | _csignals_T_93 | _csignals_T_95 ? 3'h0 : {2'h0, _csignals_T_97}) == 3'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :245:59, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_dmem_req_valid = io_dmem_req_valid_0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :228:35]
  assign io_dmem_req_bits_fcn = mem_store;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_dmem_req_bits_typ = csignals_9;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_ctl_stall = stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :202:30]
  assign io_ctl_dmiss = ~_io_ctl_dmiss_T_3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :201:{20,74}]
  assign io_ctl_pc_sel = io_ctl_exception_0 | io_dat_csr_eret | io_dat_csr_interrupt ? 3'h4 : _ctrl_pc_sel_no_xept_T_26;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :177:34, :178:34, :188:{25,43}, :253:{47,73,92}]
  assign io_ctl_op1_sel = _GEN_11 ? 2'h0 : _csignals_T_17 | _csignals_T_19 ? 2'h1 : _GEN_9 ? 2'h0 : {_csignals_T_75 | _csignals_T_77 | _csignals_T_79, 1'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_ctl_op2_sel = _GEN_12 ? 2'h1 : _GEN_10 ? 2'h2 : _csignals_T_17 ? 2'h3 : _csignals_T_19 ? 2'h0 : _csignals_T_21 | _csignals_T_23 | _csignals_T_25 | _csignals_T_27 | _csignals_T_29 | _csignals_T_31 | _csignals_T_33 | _csignals_T_35 | _csignals_T_37 ? 2'h1 : _csignals_T_39 | _csignals_T_41 | _csignals_T_43 | _csignals_T_45 | _csignals_T_47 | _csignals_T_49 | _csignals_T_51 | _csignals_T_53 | _csignals_T_55 | _csignals_T_57 | _csignals_T_59 ? 2'h0 : _csignals_T_61 ? 2'h1 : _csignals_T_63 | _csignals_T_65 | _csignals_T_67 | _csignals_T_69 | _csignals_T_71 | _csignals_T_73 | _csignals_T_75 | _csignals_T_77 | _csignals_T_79 | _csignals_T_81 | _csignals_T_83 | _csignals_T_85 | _csignals_T_87 | _csignals_T_89 | _csignals_T_91 | _csignals_T_93 | _csignals_T_95 | _csignals_T_97 | _csignals_T_99 | _csignals_T_101 | _csignals_T_103 | _csignals_T_105 | _csignals_T_107 | _csignals_T_109 | _csignals_T_111 | _csignals_T_113 | _csignals_T_115 | _csignals_T_117 | _csignals_T_119 | _csignals_T_121 | _csignals_T_123 | _csignals_T_125 ? 2'h0 : _csignals_T_127 | _csignals_T_129 | _csignals_T_131 | _csignals_T_133 | _csignals_T_135 ? 2'h1 : _csignals_T_137 | _csignals_T_139 | _csignals_T_141 | _csignals_T_143 | _csignals_T_145 ? 2'h0 : _GEN_3 ? 2'h1 : {_csignals_T_772, 1'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_ctl_alu_fun = _csignals_T_1 | _csignals_T_3 | _csignals_T_5 | _csignals_T_7 | _csignals_T_9 | _csignals_T_11 | _csignals_T_13 | _csignals_T_15 | _csignals_T_17 ? 5'h1 : _csignals_T_19 ? 5'hB : _csignals_T_21 ? 5'h1 : _csignals_T_23 ? 5'h6 : _csignals_T_25 ? 5'h7 : _csignals_T_27 ? 5'h8 : _csignals_T_29 ? 5'h9 : _csignals_T_31 ? 5'hA : _csignals_T_33 ? 5'h3 : _csignals_T_35 ? 5'h5 : _csignals_T_37 ? 5'h4 : _csignals_T_39 ? 5'h3 : _csignals_T_41 ? 5'h1 : _csignals_T_43 ? 5'h2 : _csignals_T_45 ? 5'h9 : _csignals_T_47 ? 5'hA : _csignals_T_49 ? 5'h6 : _csignals_T_51 ? 5'h7 : _csignals_T_53 ? 5'h8 : _csignals_T_55 ? 5'h5 : _csignals_T_57 ? 5'h4 : _GEN_8 ? 5'h0 : _GEN_15 ? 5'hB : _GEN_14 ? 5'h0 : _csignals_T_101 ? 5'hC : _csignals_T_103 ? 5'hD : _csignals_T_105 ? 5'hE : _csignals_T_107 ? 5'hF : _csignals_T_109 ? 5'h10 : _csignals_T_111 ? 5'h11 : _csignals_T_113 ? 5'h12 : _csignals_T_115 ? 5'h13 : _csignals_T_117 ? 5'h1A : _csignals_T_119 ? 5'h1B : _csignals_T_121 ? 5'h1C : _csignals_T_123 ? 5'h1D : _csignals_T_125 ? 5'h14 : _csignals_T_127 ? 5'h3 : _csignals_T_129 ? 5'h15 : _csignals_T_131 ? 5'h17 : _csignals_T_133 ? 5'h18 : _csignals_T_135 ? 5'h19 : _csignals_T_137 ? 5'h15 : _csignals_T_139 ? 5'h16 : _csignals_T_141 ? 5'h17 : _csignals_T_143 ? 5'h18 : _csignals_T_145 ? 5'h19 : _csignals_T_147 ? 5'h5 : _csignals_T_149 ? 5'h4 : {4'h0, _csignals_T_151 | _GEN_13};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:31:38, :34:39]
  assign io_ctl_wb_sel = _GEN_12 ? 2'h1 : _GEN_5 ? 2'h0 : _GEN_17 ? 2'h2 : _GEN_7 ? 2'h0 : _GEN_15 ? 2'h3 : _GEN_16 ? 2'h0 : {1'h0, _GEN_2};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_ctl_rf_wen = ~(stall | io_ctl_exception_0) & csignals_6;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :202:30, :214:{26,33}, :253:{47,73,92}, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_ctl_csr_cmd = stall ? 3'h0 : csr_cmd;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :202:30, :223:21, :225:26]
  assign io_ctl_exception = io_ctl_exception_0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :253:{47,73,92}]
  assign io_ctl_exception_cause = {29'h0, _io_ctl_exception_cause_T ? 3'h2 : io_dat_jump_target_too_high ? 3'h1 : io_dat_inst_misaligned ? 3'h0 : {1'h1, mem_store, 1'h0}};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :253:32, :255:{27,34}, :256:34, :257:34, :258:34, src/main/scala/chisel3/util/Lookup.scala:34:39]
  assign io_ctl_pc_sel_no_xept = io_dat_csr_interrupt ? 3'h4 : _ctrl_pc_sel_no_xept_T_26;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/cpath.scala:45:7, :177:34, :178:34]
endmodule

