// Generated by CIRCT firtool-1.75.0
// VCS coverage exclude_file
module Vincent_regfile_32x64(	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
  input  [4:0]  R0_addr,
  input         R0_en,
  input         R0_clk,
  output [63:0] R0_data,
  input  [4:0]  R1_addr,
  input         R1_en,
  input         R1_clk,
  output [63:0] R1_data,
  input  [4:0]  W0_addr,
  input         W0_en,
  input         W0_clk,
  input  [63:0] W0_data
);

  reg [63:0] Memory[0:31];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
  always @(posedge W0_clk) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
    if (W0_en & 1'h1)	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
      Memory[W0_addr] <= W0_data;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_MEM_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
    reg [63:0] _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
      `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
      `ifdef RANDOMIZE_MEM_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
        for (logic [5:0] i = 6'h0; i < 6'h20; i += 6'h1) begin
          for (logic [6:0] j = 7'h0; j < 7'h40; j += 7'h20) begin
            _RANDOM_MEM[j +: 32] = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
          end
          Memory[i[4:0]] = _RANDOM_MEM;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
        end
      `endif // RANDOMIZE_MEM_INIT
    end // initial
  `endif // ENABLE_INITIAL_MEM_
  assign R0_data = R0_en ? Memory[R0_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
  assign R1_data = R1_en ? Memory[R1_addr] : 64'bx;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/dpath.scala:146:21]
endmodule

