// Generated by CIRCT firtool-1.75.0
module Vincent_Core(	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7]
  output        io_imem_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [63:0] io_imem_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_imem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input  [63:0] io_imem_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output        io_dmem_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [63:0] io_dmem_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [63:0] io_dmem_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output        io_dmem_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [2:0]  io_dmem_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_dmem_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input  [63:0] io_dmem_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_interrupt_debug,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_interrupt_mtip,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_interrupt_msip,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_interrupt_meip,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  input         io_hartid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output        io_my_commit_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [63:0] io_my_commit_data,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [4:0]  io_my_commit_target,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [31:0] io_my_commit_pc,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [31:0] io_my_commit_pc_next,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
  output [63:0] io_my_commit_memaddr	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:47:14]
);

  wire        _simulated_pipeline_buffer_io_input_in_buffer;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:52:41]
  wire        _d_io_imem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [63:0] _d_io_imem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [63:0] _d_io_dmem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [63:0] _d_io_simulated_pipeline_buffer_enq_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [63:0] _d_io_simulated_pipeline_buffer_input_value;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_instruction_history_buffer_enq_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [31:0] _d_io_instruction_history_buffer_enq_bits_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [4:0]  _d_io_instruction_history_buffer_enq_bits_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [4:0]  _d_io_instruction_history_buffer_enq_bits_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [4:0]  _d_io_instruction_history_buffer_enq_bits_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [11:0] _d_io_instruction_history_buffer_enq_bits_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [11:0] _d_io_instruction_history_buffer_enq_bits_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [11:0] _d_io_instruction_history_buffer_enq_bits_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [19:0] _d_io_instruction_history_buffer_enq_bits_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [19:0] _d_io_instruction_history_buffer_enq_bits_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [31:0] _d_io_instruction_history_buffer_enq_bits_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [2:0]  _d_io_instruction_history_buffer_enq_bits_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [6:0]  _d_io_instruction_history_buffer_enq_bits_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [6:0]  _d_io_instruction_history_buffer_enq_bits_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [31:0] _d_io_dat_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_imiss;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_br_eq;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_br_lt;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_br_ltu;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_csr_eret;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_csr_interrupt;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _d_io_dat_inst_misaligned;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [2:0]  _d_io_dat_mem_address_low;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [63:0] _d_io_my_commit_data;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire [4:0]  _d_io_my_commit_target;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        _c_io_simulated_pipeline_buffer_enq_bits_was_write;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_simulated_pipeline_buffer_drain;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_dmem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_ctl_stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_ctl_dmiss;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [2:0]  _c_io_ctl_pc_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [1:0]  _c_io_ctl_op1_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [1:0]  _c_io_ctl_op2_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [3:0]  _c_io_ctl_alu_fun;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [1:0]  _c_io_ctl_wb_sel;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_ctl_rf_wen;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [2:0]  _c_io_ctl_csr_cmd;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire        _c_io_ctl_exception;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [31:0] _c_io_ctl_exception_cause;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [2:0]  _c_io_ctl_pc_sel_no_xept;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  Vincent_CtlPath c (	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .clock                                           (clock),
    .reset                                           (reset),
    .io_simulated_pipeline_buffer_enq_bits_was_write (_c_io_simulated_pipeline_buffer_enq_bits_was_write),
    .io_simulated_pipeline_buffer_drain              (_c_io_simulated_pipeline_buffer_drain),
    .io_imem_resp_valid                              (io_imem_resp_valid),
    .io_dmem_req_valid                               (_c_io_dmem_req_valid),
    .io_dmem_req_bits_fcn                            (io_dmem_req_bits_fcn),
    .io_dmem_req_bits_typ                            (io_dmem_req_bits_typ),
    .io_dmem_resp_valid                              (io_dmem_resp_valid),
    .io_dat_inst                                     (_d_io_dat_inst),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_imiss                                    (_d_io_dat_imiss),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_br_eq                                    (_d_io_dat_br_eq),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_br_lt                                    (_d_io_dat_br_lt),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_br_ltu                                   (_d_io_dat_br_ltu),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_csr_eret                                 (_d_io_dat_csr_eret),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_csr_interrupt                            (_d_io_dat_csr_interrupt),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_inst_misaligned                          (_d_io_dat_inst_misaligned),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_dat_mem_address_low                          (_d_io_dat_mem_address_low),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_ctl_stall                                    (_c_io_ctl_stall),
    .io_ctl_dmiss                                    (_c_io_ctl_dmiss),
    .io_ctl_pc_sel                                   (_c_io_ctl_pc_sel),
    .io_ctl_op1_sel                                  (_c_io_ctl_op1_sel),
    .io_ctl_op2_sel                                  (_c_io_ctl_op2_sel),
    .io_ctl_alu_fun                                  (_c_io_ctl_alu_fun),
    .io_ctl_wb_sel                                   (_c_io_ctl_wb_sel),
    .io_ctl_rf_wen                                   (_c_io_ctl_rf_wen),
    .io_ctl_csr_cmd                                  (_c_io_ctl_csr_cmd),
    .io_ctl_exception                                (_c_io_ctl_exception),
    .io_ctl_exception_cause                          (_c_io_ctl_exception_cause),
    .io_ctl_pc_sel_no_xept                           (_c_io_ctl_pc_sel_no_xept)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
  wire [2:0]  my_csr_cmd;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:113:27]
  assign my_csr_cmd = _c_io_ctl_csr_cmd;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18, :113:27]
  wire        my_dmem_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:116:27]
  assign my_dmem_valid = _c_io_dmem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18, :116:27]
  Vincent_DatPath d (	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .clock                                         (clock),
    .reset                                         (reset),
    .io_imem_req_valid                             (_d_io_imem_req_valid),
    .io_imem_req_bits_addr                         (_d_io_imem_req_bits_addr),
    .io_imem_resp_valid                            (io_imem_resp_valid),
    .io_imem_resp_bits_data                        (io_imem_resp_bits_data),
    .io_dmem_req_bits_addr                         (_d_io_dmem_req_bits_addr),
    .io_dmem_req_bits_data                         (io_dmem_req_bits_data),
    .io_dmem_resp_bits_data                        (io_dmem_resp_bits_data),
    .io_simulated_pipeline_buffer_enq_bits_addr    (_d_io_simulated_pipeline_buffer_enq_bits_addr),
    .io_simulated_pipeline_buffer_input_value      (_d_io_simulated_pipeline_buffer_input_value),
    .io_simulated_pipeline_buffer_input_in_buffer  (_simulated_pipeline_buffer_io_input_in_buffer),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:52:41]
    .io_instruction_history_buffer_enq_valid       (_d_io_instruction_history_buffer_enq_valid),
    .io_instruction_history_buffer_enq_bits_inst   (_d_io_instruction_history_buffer_enq_bits_inst),
    .io_instruction_history_buffer_enq_bits_wb     (_d_io_instruction_history_buffer_enq_bits_wb),
    .io_instruction_history_buffer_enq_bits_rs1    (_d_io_instruction_history_buffer_enq_bits_rs1),
    .io_instruction_history_buffer_enq_bits_rs2    (_d_io_instruction_history_buffer_enq_bits_rs2),
    .io_instruction_history_buffer_enq_bits_imm_i  (_d_io_instruction_history_buffer_enq_bits_imm_i),
    .io_instruction_history_buffer_enq_bits_imm_s  (_d_io_instruction_history_buffer_enq_bits_imm_s),
    .io_instruction_history_buffer_enq_bits_imm_b  (_d_io_instruction_history_buffer_enq_bits_imm_b),
    .io_instruction_history_buffer_enq_bits_imm_u  (_d_io_instruction_history_buffer_enq_bits_imm_u),
    .io_instruction_history_buffer_enq_bits_imm_j  (_d_io_instruction_history_buffer_enq_bits_imm_j),
    .io_instruction_history_buffer_enq_bits_imm_z  (_d_io_instruction_history_buffer_enq_bits_imm_z),
    .io_instruction_history_buffer_enq_bits_funct3 (_d_io_instruction_history_buffer_enq_bits_funct3),
    .io_instruction_history_buffer_enq_bits_funct7 (_d_io_instruction_history_buffer_enq_bits_funct7),
    .io_instruction_history_buffer_enq_bits_opcode (_d_io_instruction_history_buffer_enq_bits_opcode),
    .io_ctl_stall                                  (_c_io_ctl_stall),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_dmiss                                  (_c_io_ctl_dmiss),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_pc_sel                                 (_c_io_ctl_pc_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_op1_sel                                (_c_io_ctl_op1_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_op2_sel                                (_c_io_ctl_op2_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_alu_fun                                (_c_io_ctl_alu_fun),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_wb_sel                                 (_c_io_ctl_wb_sel),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_rf_wen                                 (_c_io_ctl_rf_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_csr_cmd                                (_c_io_ctl_csr_cmd),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_exception                              (_c_io_ctl_exception),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_exception_cause                        (_c_io_ctl_exception_cause),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_ctl_pc_sel_no_xept                         (_c_io_ctl_pc_sel_no_xept),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_dat_inst                                   (_d_io_dat_inst),
    .io_dat_imiss                                  (_d_io_dat_imiss),
    .io_dat_br_eq                                  (_d_io_dat_br_eq),
    .io_dat_br_lt                                  (_d_io_dat_br_lt),
    .io_dat_br_ltu                                 (_d_io_dat_br_ltu),
    .io_dat_csr_eret                               (_d_io_dat_csr_eret),
    .io_dat_csr_interrupt                          (_d_io_dat_csr_interrupt),
    .io_dat_inst_misaligned                        (_d_io_dat_inst_misaligned),
    .io_dat_mem_address_low                        (_d_io_dat_mem_address_low),
    .io_interrupt_debug                            (io_interrupt_debug),
    .io_interrupt_mtip                             (io_interrupt_mtip),
    .io_interrupt_msip                             (io_interrupt_msip),
    .io_interrupt_meip                             (io_interrupt_meip),
    .io_hartid                                     (io_hartid),
    .io_my_commit_data                             (_d_io_my_commit_data),
    .io_my_commit_target                           (_d_io_my_commit_target),
    .io_my_commit_pc                               (io_my_commit_pc),
    .io_my_commit_pc_next                          (io_my_commit_pc_next)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  wire        my_imem_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:114:27]
  assign my_imem_valid = _d_io_imem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18, :114:27]
  wire [63:0] my_imem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:115:27]
  assign my_imem_addr = _d_io_imem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18, :115:27]
  wire [63:0] my_dmem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:117:27]
  assign my_dmem_addr = _d_io_dmem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18, :117:27]
  Vincent_PipelineBuffer simulated_pipeline_buffer (	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:52:41]
    .clock                 (clock),
    .reset                 (reset),
    .io_enq_valid          (1'h1),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18, :50:18, :52:41, :53:42]
    .io_enq_bits_addr      (_d_io_simulated_pipeline_buffer_enq_bits_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_was_write (_c_io_simulated_pipeline_buffer_enq_bits_was_write),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_drain              (_c_io_simulated_pipeline_buffer_drain),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:49:18]
    .io_input_value        (_d_io_simulated_pipeline_buffer_input_value),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_input_in_buffer    (_simulated_pipeline_buffer_io_input_in_buffer)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:52:41]
  Vincent_CircularBufferNoReadOut instruction_history_buffer (	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:53:42]
    .clock              (clock),
    .reset              (reset),
    .io_enq_valid       (_d_io_instruction_history_buffer_enq_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_inst   (_d_io_instruction_history_buffer_enq_bits_inst),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_wb     (_d_io_instruction_history_buffer_enq_bits_wb),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_rs1    (_d_io_instruction_history_buffer_enq_bits_rs1),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_rs2    (_d_io_instruction_history_buffer_enq_bits_rs2),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_i  (_d_io_instruction_history_buffer_enq_bits_imm_i),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_s  (_d_io_instruction_history_buffer_enq_bits_imm_s),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_b  (_d_io_instruction_history_buffer_enq_bits_imm_b),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_u  (_d_io_instruction_history_buffer_enq_bits_imm_u),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_j  (_d_io_instruction_history_buffer_enq_bits_imm_j),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_imm_z  (_d_io_instruction_history_buffer_enq_bits_imm_z),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_funct3 (_d_io_instruction_history_buffer_enq_bits_funct3),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_funct7 (_d_io_instruction_history_buffer_enq_bits_funct7),	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
    .io_enq_bits_opcode (_d_io_instruction_history_buffer_enq_bits_opcode)	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:50:18]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:53:42]
  assign io_imem_req_valid = _d_io_imem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :50:18]
  assign io_imem_req_bits_addr = _d_io_imem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :50:18]
  assign io_dmem_req_valid = _c_io_dmem_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :49:18]
  assign io_dmem_req_bits_addr = _d_io_dmem_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :50:18]
  assign io_my_commit_valid = ~_c_io_ctl_stall;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :49:18, :98:27]
  assign io_my_commit_data = _c_io_ctl_stall ? 64'h0 : _d_io_my_commit_data;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :49:18, :50:18, :99:30]
  assign io_my_commit_target = _c_io_ctl_stall ? 5'h0 : _d_io_my_commit_target;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :49:18, :50:18, :100:30]
  assign io_my_commit_memaddr = ~_c_io_ctl_stall & _c_io_dmem_req_valid ? _d_io_dmem_req_bits_addr : 64'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/core.scala:45:7, :49:18, :50:18, :98:27, :101:{30,50}]
endmodule

