// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Vincent_AsyncScratchPadMemory(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  input         io_core_ports_0_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [63:0] io_core_ports_0_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [63:0] io_core_ports_0_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input         io_core_ports_0_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [2:0]  io_core_ports_0_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output        io_core_ports_0_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output [63:0] io_core_ports_0_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input         io_core_ports_1_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [63:0] io_core_ports_1_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [2:0]  io_core_ports_1_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output        io_core_ports_1_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output [63:0] io_core_ports_1_resp_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input         io_debug_port_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [63:0] io_debug_port_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [63:0] io_debug_port_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input         io_debug_port_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  input  [2:0]  io_debug_port_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output        io_debug_port_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
  output [63:0] io_debug_port_resp_bits_data	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:196:15]
);

  wire [5:0]  _memwriter_1_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_3;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_4;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_5;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_6;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_1_io_mem_data_7;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_3;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_4;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_5;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_6;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_1_io_mem_masks_7;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [63:0] _io_debug_port_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  _io_debug_port_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [63:0] _io_core_ports_1_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  _io_core_ports_1_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  _memwriter_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_3;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_4;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_5;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_6;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [7:0]  _memwriter_io_mem_data_7;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_3;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_4;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_5;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_6;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire        _memwriter_io_mem_masks_7;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  wire [63:0] _io_core_ports_0_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  _io_core_ports_0_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [63:0] _mem_ext_R0_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  wire [63:0] _mem_ext_R1_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  wire [63:0] _mem_ext_R2_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  wire        dport_wen = io_core_ports_0_req_valid & io_core_ports_0_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:215:51]
  wire [2:0]  _io_core_ports_0_resp_bits_data_T_3 = io_core_ports_0_req_bits_typ - 3'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24]
  wire [2:0]  _io_core_ports_1_resp_bits_data_T_3 = io_core_ports_1_req_bits_typ - 3'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24]
  wire        debug_port_wen = io_debug_port_req_valid & io_debug_port_req_bits_fcn;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:239:49]
  wire [2:0]  _io_debug_port_resp_bits_data_T_3 = io_debug_port_req_bits_typ - 3'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:216:10]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:216:10]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:216:10]
        $fwrite(32'h80000002, "\n Valid %x and fcn %x dport_wen %x \n", io_core_ports_0_req_valid, io_core_ports_0_req_bits_fcn, dport_wen);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:215:51, :216:10]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:145:13, :216:10]
        $fwrite(32'h80000002, "Read Mem addr %x io.addr %x addr %x data %x memreader.io.mem_data  \n", _io_core_ports_0_resp_bits_data_memreader_io_mem_addr, io_core_ports_0_req_bits_addr[8:0], io_core_ports_0_req_bits_addr, _io_core_ports_0_resp_bits_data_memreader_io_data);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :137:25, :145:13]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13, :216:10]
        $fwrite(32'h80000002, " memreader.io.mem_data = sodor.common.MemoryModule$MemReader$1@4e280414.io.mem_data \n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13]
      if ((`PRINTF_COND_) & io_core_ports_0_req_valid & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:216:10, :219:13]
        $fwrite(32'h80000002, "\n DPORT: Got request for addr %x will return data %x getTLSize %x, getTLSigned %x, type %x \n", io_core_ports_0_req_bits_addr, _io_core_ports_0_resp_bits_data_memreader_io_data, _io_core_ports_0_resp_bits_data_T_3[1:0], ~(_io_core_ports_0_resp_bits_data_T_3[2]), io_core_ports_0_req_bits_typ);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :61:{21,27,33}, :136:29, :219:13]
      if ((`PRINTF_COND_) & dport_wen & ~reset) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:183:16, :184:16, :215:51, :216:10]
        $fwrite(32'h80000002, "Vincent Write Mem index %d io.addr %x addrWidth %x\n", _memwriter_io_mem_addr, io_core_ports_0_req_bits_addr[8:0], 4'h9);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25, :176:29, :183:16]
        $fwrite(32'h80000002, "Vincent Write mem data=sodor.common.MemoryModule$MemWriter$1@651656b9.io.mem_data mask sodor.common.MemoryModule$MemWriter$1@651656b9.io.mem_masks \n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:184:16]
      end
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:145:13, :216:10]
        $fwrite(32'h80000002, "Read Mem addr %x io.addr %x addr %x data %x memreader.io.mem_data  \n", _io_core_ports_1_resp_bits_data_memreader_io_mem_addr, io_core_ports_1_req_bits_addr[8:0], io_core_ports_1_req_bits_addr, _io_core_ports_1_resp_bits_data_memreader_io_data);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :137:25, :145:13]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13, :216:10]
        $fwrite(32'h80000002, " memreader.io.mem_data = sodor.common.MemoryModule$MemReader$1@4ac25f57.io.mem_data \n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13]
      if ((`PRINTF_COND_) & io_core_ports_1_req_valid & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:216:10, :229:16]
        $fwrite(32'h80000002, "IPORT: Got request for addr %x will return data %x getTLSize %x, getTLSigned %x, type %x \n", io_core_ports_1_req_bits_addr, _io_core_ports_1_resp_bits_data_memreader_io_data, _io_core_ports_1_resp_bits_data_T_3[1:0], ~(_io_core_ports_1_resp_bits_data_T_3[2]), io_core_ports_1_req_bits_typ);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :61:{21,27,33}, :136:29, :229:16]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:145:13, :216:10]
        $fwrite(32'h80000002, "Read Mem addr %x io.addr %x addr %x data %x memreader.io.mem_data  \n", _io_debug_port_resp_bits_data_memreader_io_mem_addr, io_debug_port_req_bits_addr[8:0], io_debug_port_req_bits_addr, _io_debug_port_resp_bits_data_memreader_io_data);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :137:25, :145:13]
      if ((`PRINTF_COND_) & ~reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13, :216:10]
        $fwrite(32'h80000002, " memreader.io.mem_data = sodor.common.MemoryModule$MemReader$1@25745731.io.mem_data \n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:146:13]
      if ((`PRINTF_COND_) & debug_port_wen & ~reset) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:183:16, :184:16, :216:10, :239:49]
        $fwrite(32'h80000002, "Vincent Write Mem index %d io.addr %x addrWidth %x\n", _memwriter_1_io_mem_addr, io_debug_port_req_bits_addr[8:0], 4'h9);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25, :176:29, :183:16]
        $fwrite(32'h80000002, "Vincent Write mem data=sodor.common.MemoryModule$MemWriter$1@7b8e4501.io.mem_data mask sodor.common.MemoryModule$MemWriter$1@7b8e4501.io.mem_masks \n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:184:16]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  Vincent_mem_64x64 mem_ext (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .R0_addr (_io_debug_port_resp_bits_data_memreader_io_mem_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .R0_en   (1'h1),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
    .R0_clk  (clock),
    .R0_data (_mem_ext_R0_data),
    .R1_addr (_io_core_ports_1_resp_bits_data_memreader_io_mem_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .R1_en   (1'h1),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
    .R1_clk  (clock),
    .R1_data (_mem_ext_R1_data),
    .R2_addr (_io_core_ports_0_resp_bits_data_memreader_io_mem_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .R2_en   (1'h1),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
    .R2_clk  (clock),
    .R2_data (_mem_ext_R2_data),
    .W0_addr (_memwriter_1_io_mem_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
    .W0_en   (debug_port_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:239:49]
    .W0_clk  (clock),
    .W0_data ({_memwriter_1_io_mem_data_7, _memwriter_1_io_mem_data_6, _memwriter_1_io_mem_data_5, _memwriter_1_io_mem_data_4, _memwriter_1_io_mem_data_3, _memwriter_1_io_mem_data_2, _memwriter_1_io_mem_data_1, _memwriter_1_io_mem_data_0}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31, :176:29]
    .W0_mask ({_memwriter_1_io_mem_masks_7, _memwriter_1_io_mem_masks_6, _memwriter_1_io_mem_masks_5, _memwriter_1_io_mem_masks_4, _memwriter_1_io_mem_masks_3, _memwriter_1_io_mem_masks_2, _memwriter_1_io_mem_masks_1, _memwriter_1_io_mem_masks_0}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31, :176:29]
    .W1_addr (_memwriter_io_mem_addr),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
    .W1_en   (dport_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:215:51]
    .W1_clk  (clock),
    .W1_data ({_memwriter_io_mem_data_7, _memwriter_io_mem_data_6, _memwriter_io_mem_data_5, _memwriter_io_mem_data_4, _memwriter_io_mem_data_3, _memwriter_io_mem_data_2, _memwriter_io_mem_data_1, _memwriter_io_mem_data_0}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31, :176:29]
    .W1_mask ({_memwriter_io_mem_masks_7, _memwriter_io_mem_masks_6, _memwriter_io_mem_masks_5, _memwriter_io_mem_masks_4, _memwriter_io_mem_masks_3, _memwriter_io_mem_masks_2, _memwriter_io_mem_masks_1, _memwriter_io_mem_masks_0})	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31, :176:29]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  Vincent_MemReader io_core_ports_0_resp_bits_data_memreader (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .clock         (clock),
    .reset         (reset),
    .io_addr       (io_core_ports_0_req_bits_addr[8:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25]
    .io_size       ({1'h0, _io_core_ports_0_resp_bits_data_T_3[1:0]}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :138:25]
    .io_signed     (~(_io_core_ports_0_resp_bits_data_T_3[2])),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24, :61:{21,27,33}]
    .io_data       (_io_core_ports_0_resp_bits_data_memreader_io_data),
    .io_mem_addr   (_io_core_ports_0_resp_bits_data_memreader_io_mem_addr),
    .io_mem_data_0 (_mem_ext_R2_data[7:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_1 (_mem_ext_R2_data[15:8]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_2 (_mem_ext_R2_data[23:16]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_3 (_mem_ext_R2_data[31:24]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_4 (_mem_ext_R2_data[39:32]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_5 (_mem_ext_R2_data[47:40]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_6 (_mem_ext_R2_data[55:48]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_7 (_mem_ext_R2_data[63:56])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  io_core_ports_0_resp_bits_data_my_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:140:29]
  assign io_core_ports_0_resp_bits_data_my_mem_addr = _io_core_ports_0_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :140:29]
  Vincent_MemWriter memwriter (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
    .io_addr        (io_core_ports_0_req_bits_addr[8:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25]
    .io_data        (io_core_ports_0_req_bits_data),
    .io_size        ({1'h0, _io_core_ports_0_resp_bits_data_T_3[1:0]}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :179:25]
    .io_en          (dport_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:215:51]
    .io_mem_addr    (_memwriter_io_mem_addr),
    .io_mem_data_0  (_memwriter_io_mem_data_0),
    .io_mem_data_1  (_memwriter_io_mem_data_1),
    .io_mem_data_2  (_memwriter_io_mem_data_2),
    .io_mem_data_3  (_memwriter_io_mem_data_3),
    .io_mem_data_4  (_memwriter_io_mem_data_4),
    .io_mem_data_5  (_memwriter_io_mem_data_5),
    .io_mem_data_6  (_memwriter_io_mem_data_6),
    .io_mem_data_7  (_memwriter_io_mem_data_7),
    .io_mem_masks_0 (_memwriter_io_mem_masks_0),
    .io_mem_masks_1 (_memwriter_io_mem_masks_1),
    .io_mem_masks_2 (_memwriter_io_mem_masks_2),
    .io_mem_masks_3 (_memwriter_io_mem_masks_3),
    .io_mem_masks_4 (_memwriter_io_mem_masks_4),
    .io_mem_masks_5 (_memwriter_io_mem_masks_5),
    .io_mem_masks_6 (_memwriter_io_mem_masks_6),
    .io_mem_masks_7 (_memwriter_io_mem_masks_7)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  Vincent_MemReader io_core_ports_1_resp_bits_data_memreader (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .clock         (clock),
    .reset         (reset),
    .io_addr       (io_core_ports_1_req_bits_addr[8:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25]
    .io_size       ({1'h0, _io_core_ports_1_resp_bits_data_T_3[1:0]}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :138:25]
    .io_signed     (~(_io_core_ports_1_resp_bits_data_T_3[2])),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24, :61:{21,27,33}]
    .io_data       (_io_core_ports_1_resp_bits_data_memreader_io_data),
    .io_mem_addr   (_io_core_ports_1_resp_bits_data_memreader_io_mem_addr),
    .io_mem_data_0 (_mem_ext_R1_data[7:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_1 (_mem_ext_R1_data[15:8]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_2 (_mem_ext_R1_data[23:16]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_3 (_mem_ext_R1_data[31:24]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_4 (_mem_ext_R1_data[39:32]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_5 (_mem_ext_R1_data[47:40]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_6 (_mem_ext_R1_data[55:48]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_7 (_mem_ext_R1_data[63:56])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  io_core_ports_1_resp_bits_data_my_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:140:29]
  assign io_core_ports_1_resp_bits_data_my_mem_addr = _io_core_ports_1_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :140:29]
  Vincent_MemReader io_debug_port_resp_bits_data_memreader (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
    .clock         (clock),
    .reset         (reset),
    .io_addr       (io_debug_port_req_bits_addr[8:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25]
    .io_size       ({1'h0, _io_debug_port_resp_bits_data_T_3[1:0]}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :138:25]
    .io_signed     (~(_io_debug_port_resp_bits_data_T_3[2])),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:24, :61:{21,27,33}]
    .io_data       (_io_debug_port_resp_bits_data_memreader_io_data),
    .io_mem_addr   (_io_debug_port_resp_bits_data_memreader_io_mem_addr),
    .io_mem_data_0 (_mem_ext_R0_data[7:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_1 (_mem_ext_R0_data[15:8]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_2 (_mem_ext_R0_data[23:16]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_3 (_mem_ext_R0_data[31:24]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_4 (_mem_ext_R0_data[39:32]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_5 (_mem_ext_R0_data[47:40]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_6 (_mem_ext_R0_data[55:48]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
    .io_mem_data_7 (_mem_ext_R0_data[63:56])	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:81:31]
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29]
  wire [5:0]  io_debug_port_resp_bits_data_my_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:140:29]
  assign io_debug_port_resp_bits_data_my_mem_addr = _io_debug_port_resp_bits_data_memreader_io_mem_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :140:29]
  Vincent_MemWriter memwriter_1 (	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
    .io_addr        (io_debug_port_req_bits_addr[8:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:137:25]
    .io_data        (io_debug_port_req_bits_data),
    .io_size        ({1'h0, _io_debug_port_resp_bits_data_T_3[1:0]}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :179:25]
    .io_en          (debug_port_wen),	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:239:49]
    .io_mem_addr    (_memwriter_1_io_mem_addr),
    .io_mem_data_0  (_memwriter_1_io_mem_data_0),
    .io_mem_data_1  (_memwriter_1_io_mem_data_1),
    .io_mem_data_2  (_memwriter_1_io_mem_data_2),
    .io_mem_data_3  (_memwriter_1_io_mem_data_3),
    .io_mem_data_4  (_memwriter_1_io_mem_data_4),
    .io_mem_data_5  (_memwriter_1_io_mem_data_5),
    .io_mem_data_6  (_memwriter_1_io_mem_data_6),
    .io_mem_data_7  (_memwriter_1_io_mem_data_7),
    .io_mem_masks_0 (_memwriter_1_io_mem_masks_0),
    .io_mem_masks_1 (_memwriter_1_io_mem_masks_1),
    .io_mem_masks_2 (_memwriter_1_io_mem_masks_2),
    .io_mem_masks_3 (_memwriter_1_io_mem_masks_3),
    .io_mem_masks_4 (_memwriter_1_io_mem_masks_4),
    .io_mem_masks_5 (_memwriter_1_io_mem_masks_5),
    .io_mem_masks_6 (_memwriter_1_io_mem_masks_6),
    .io_mem_masks_7 (_memwriter_1_io_mem_masks_7)
  );	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:176:29]
  assign io_core_ports_0_resp_valid = io_core_ports_0_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  assign io_core_ports_0_resp_bits_data = _io_core_ports_0_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :244:7]
  assign io_core_ports_1_resp_valid = io_core_ports_1_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  assign io_core_ports_1_resp_bits_data = _io_core_ports_1_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :244:7]
  assign io_debug_port_resp_valid = io_debug_port_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:244:7]
  assign io_debug_port_resp_bits_data = _io_debug_port_resp_bits_data_memreader_io_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:136:29, :244:7]
endmodule

