// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Vincent_CircularBufferNoReadOut(	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
  input        clock,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
  input        reset,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
  input        io_enq_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [31:0] io_enq_bits_inst,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [4:0]  io_enq_bits_wb,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [4:0]  io_enq_bits_rs1,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [4:0]  io_enq_bits_rs2,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [11:0] io_enq_bits_imm_i,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [11:0] io_enq_bits_imm_s,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [11:0] io_enq_bits_imm_b,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [19:0] io_enq_bits_imm_u,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [19:0] io_enq_bits_imm_j,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [31:0] io_enq_bits_imm_z,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [2:0]  io_enq_bits_funct3,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [6:0]  io_enq_bits_funct7,	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
  input [6:0]  io_enq_bits_opcode	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
);

  reg  [31:0] buffer_0_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_0_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_0_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_0_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_0_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_0_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_0_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_0_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_0_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [31:0] buffer_0_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [2:0]  buffer_0_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_0_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_0_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [31:0] buffer_1_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_1_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_1_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_1_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_1_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_1_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_1_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_1_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_1_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [31:0] buffer_1_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [2:0]  buffer_1_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_1_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_1_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [31:0] buffer_2_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_2_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_2_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [4:0]  buffer_2_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_2_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_2_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [11:0] buffer_2_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_2_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [19:0] buffer_2_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [31:0] buffer_2_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [2:0]  buffer_2_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_2_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [6:0]  buffer_2_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
  reg  [1:0]  writePtr;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:18:25]
  wire [1:0]  _writePtr_T_3 = writePtr + 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:18:25, :24:30]
  always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
    if (io_enq_valid & writePtr == 2'h0) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19, :18:25, :22:21, :23:22]
      buffer_0_inst <= io_enq_bits_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_wb <= io_enq_bits_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_rs1 <= io_enq_bits_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_rs2 <= io_enq_bits_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_i <= io_enq_bits_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_s <= io_enq_bits_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_b <= io_enq_bits_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_u <= io_enq_bits_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_j <= io_enq_bits_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_imm_z <= io_enq_bits_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_funct3 <= io_enq_bits_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_funct7 <= io_enq_bits_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_0_opcode <= io_enq_bits_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
    end
    if (io_enq_valid & writePtr == 2'h1) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19, :18:25, :22:21, :23:22]
      buffer_1_inst <= io_enq_bits_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_wb <= io_enq_bits_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_rs1 <= io_enq_bits_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_rs2 <= io_enq_bits_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_i <= io_enq_bits_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_s <= io_enq_bits_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_b <= io_enq_bits_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_u <= io_enq_bits_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_j <= io_enq_bits_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_imm_z <= io_enq_bits_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_funct3 <= io_enq_bits_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_funct7 <= io_enq_bits_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_1_opcode <= io_enq_bits_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
    end
    if (io_enq_valid & writePtr == 2'h2) begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19, :18:25, :22:21, :23:22]
      buffer_2_inst <= io_enq_bits_inst;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_wb <= io_enq_bits_wb;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_rs1 <= io_enq_bits_rs1;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_rs2 <= io_enq_bits_rs2;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_i <= io_enq_bits_imm_i;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_s <= io_enq_bits_imm_s;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_b <= io_enq_bits_imm_b;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_u <= io_enq_bits_imm_u;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_j <= io_enq_bits_imm_j;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_imm_z <= io_enq_bits_imm_z;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_funct3 <= io_enq_bits_funct3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_funct7 <= io_enq_bits_funct7;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
      buffer_2_opcode <= io_enq_bits_opcode;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:17:19]
    end
    if (reset)	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
      writePtr <= 2'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:18:25]
    else if (io_enq_valid)	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:15:14]
      writePtr <= (&_writePtr_T_3) ? 2'h0 : _writePtr_T_3;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:18:25, :24:{20,30,36}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:16];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
        `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
        for (logic [4:0] i = 5'h0; i < 5'h11; i += 5'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
        end	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
        buffer_0_inst = _RANDOM[5'h0];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_wb = _RANDOM[5'h1][4:0];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_rs1 = _RANDOM[5'h1][9:5];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_rs2 = _RANDOM[5'h1][14:10];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_i = _RANDOM[5'h1][26:15];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_s = {_RANDOM[5'h1][31:27], _RANDOM[5'h2][6:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_b = _RANDOM[5'h2][18:7];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_u = {_RANDOM[5'h2][31:19], _RANDOM[5'h3][6:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_j = _RANDOM[5'h3][26:7];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_imm_z = {_RANDOM[5'h3][31:27], _RANDOM[5'h4][26:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_funct3 = _RANDOM[5'h4][29:27];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_funct7 = {_RANDOM[5'h4][31:30], _RANDOM[5'h5][4:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_0_opcode = _RANDOM[5'h5][11:5];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_inst = {_RANDOM[5'h5][31:12], _RANDOM[5'h6][11:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_wb = _RANDOM[5'h6][16:12];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_rs1 = _RANDOM[5'h6][21:17];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_rs2 = _RANDOM[5'h6][26:22];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_i = {_RANDOM[5'h6][31:27], _RANDOM[5'h7][6:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_s = _RANDOM[5'h7][18:7];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_b = _RANDOM[5'h7][30:19];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_u = {_RANDOM[5'h7][31], _RANDOM[5'h8][18:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_j = {_RANDOM[5'h8][31:19], _RANDOM[5'h9][6:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_imm_z = {_RANDOM[5'h9][31:7], _RANDOM[5'hA][6:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_funct3 = _RANDOM[5'hA][9:7];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_funct7 = _RANDOM[5'hA][16:10];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_1_opcode = _RANDOM[5'hA][23:17];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_inst = {_RANDOM[5'hA][31:24], _RANDOM[5'hB][23:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_wb = _RANDOM[5'hB][28:24];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_rs1 = {_RANDOM[5'hB][31:29], _RANDOM[5'hC][1:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_rs2 = _RANDOM[5'hC][6:2];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_i = _RANDOM[5'hC][18:7];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_s = _RANDOM[5'hC][30:19];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_b = {_RANDOM[5'hC][31], _RANDOM[5'hD][10:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_u = _RANDOM[5'hD][30:11];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_j = {_RANDOM[5'hD][31], _RANDOM[5'hE][18:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_imm_z = {_RANDOM[5'hE][31:19], _RANDOM[5'hF][18:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_funct3 = _RANDOM[5'hF][21:19];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_funct7 = _RANDOM[5'hF][28:22];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        buffer_2_opcode = {_RANDOM[5'hF][31:29], _RANDOM[5'h10][3:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19]
        writePtr = _RANDOM[5'h10][5:4];	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7, :17:19, :18:25]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/rvFlexible_1stage/circularbuffer.scala:12:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
endmodule

