// Generated by CIRCT firtool-1.75.0

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module BranchMaskGenerationLogic(	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
  input        clock,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
  input        reset,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
  input        io_is_branch_0,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  input        io_will_fire_0,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  output       io_br_tag_0,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  output [1:0] io_br_mask_0,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  output       io_is_full_0,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  input  [1:0] io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  input  [1:0] io_brupdate_b2_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  input        io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
  input        io_flush_pipeline	// @[generators/boom/src/main/scala/v3/exu/decode.scala:730:14]
);

  reg [1:0] branch_mask;	// @[generators/boom/src/main/scala/v3/exu/decode.scala:752:28]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
    if (reset)	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      branch_mask <= 2'h0;	// @[generators/boom/src/main/scala/v3/exu/decode.scala:752:28]
    else	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      branch_mask <= io_flush_pipeline ? 2'h0 : ({2{io_will_fire_0}} & (branch_mask[0] ? {~(branch_mask[1]), 1'h0} : 2'h1) | branch_mask) & ~io_brupdate_b1_resolve_mask & (io_brupdate_b2_mispredict ? io_brupdate_b2_uop_br_mask : 2'h3);	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7, :752:28, :767:18, :770:{13,27,32}, :772:22, :787:20, :793:28, :794:17, :796:19, :799:{17,57}, generators/boom/src/main/scala/v3/util/util.scala:89:{21,23}]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:0];	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
        _RANDOM[/*Zero width*/ 1'b0] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
        branch_mask = _RANDOM[/*Zero width*/ 1'b0][1:0];	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7, :752:28]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  assign io_br_tag_0 = branch_mask[0] & ~(branch_mask[1]);	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7, :752:28, :770:{13,27,32}, :771:20]
  assign io_br_mask_0 = branch_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7, :752:28, generators/boom/src/main/scala/v3/util/util.scala:89:{21,23}]
  assign io_is_full_0 = (&branch_mask) & io_is_branch_0;	// @[generators/boom/src/main/scala/v3/exu/decode.scala:728:7, :752:28, :762:{37,63}]
endmodule

