// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module ForwardingAgeLogic(	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1754:7]
  input        clock,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1754:7]
  input        reset,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1754:7]
  input  [3:0] io_addr_matches,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1756:15]
  input  [1:0] io_youngest_st_idx,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1756:15]
  output [1:0] io_forwarding_idx	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1756:15]
);

  wire [3:0] _matches_T_1 = io_addr_matches & {1'h0, &io_youngest_st_idx, io_youngest_st_idx[1], |io_youngest_st_idx};	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1770:19, :1771:17, :1772:7, :1773:22, :1779:{35,46}]
  wire [1:0] io_forwarding_idx_0 = io_addr_matches[0] ? 2'h0 : io_addr_matches[1] ? 2'h1 : io_addr_matches[2] ? 2'h2 : io_addr_matches[3] ? 2'h3 : _matches_T_1[0] ? 2'h0 : _matches_T_1[1] ? 2'h1 : _matches_T_1[2] ? 2'h2 : {2{_matches_T_1[3]}};	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1779:35, :1784:22, :1792:26, :1793:13, :1795:33]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1810:15]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1810:15]
      if ((`PRINTF_COND_) & (io_addr_matches[0] | io_addr_matches[1] | io_addr_matches[2] | io_addr_matches[3] | _matches_T_1[0] | _matches_T_1[1] | _matches_T_1[2] | _matches_T_1[3]) & ~reset) begin	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1779:35, :1792:26, :1793:13, :1794:27, :1810:15, :1813:15]
        $fwrite(32'h80000002, "BUG TRIGGERING: Disabling load-store forwarding \n");	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1810:15]
        $fwrite(32'h80000002, "  addr_matches: %b \n", io_addr_matches);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1811:15]
        $fwrite(32'h80000002, "  youngest_st_idx: %d \n", io_youngest_st_idx);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1812:15]
        $fwrite(32'h80000002, "  io.forwarding_idx: %d \n", io_forwarding_idx_0);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1793:13, :1795:33, :1813:15]
      end
      if ((`PRINTF_COND_) & ~reset) begin	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1810:15, :1815:15, :1818:15]
        $fwrite(32'h80000002, "BUG INJECTED: Disabling load-store forwarding \n");	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1815:15]
        $fwrite(32'h80000002, "  addr_matches: %b \n", io_addr_matches);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1816:15]
        $fwrite(32'h80000002, "  youngest_st_idx: %d \n", io_youngest_st_idx);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1817:15]
        $fwrite(32'h80000002, "  io.forwarding_idx: %d \n", io_forwarding_idx_0);	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1793:13, :1795:33, :1818:15]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  assign io_forwarding_idx = io_forwarding_idx_0;	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1754:7, :1793:13, :1795:33]
endmodule

