#!/usr/bin/env python3
import re
import sys
from pathlib import Path


def parse_verilog_value(value_str):
    """
    Parse a Verilog literal like:
      32'h00010000
      64'h00000000_00000003
      2'b11
      1'b0
    Return (width, base, int_value)
    """
    m = re.match(r"(\d+)'([hbdo])([0-9a-fA-F_xXzZ]+)", value_str.strip())
    if not m:
        raise ValueError(f"Unrecognized value format: {value_str}")
    width, base, val = m.groups()
    val = val.replace("_", "")
    if base.lower() == 'h':
        intval = int(val, 16)
    elif base.lower() == 'b':
        intval = int(val, 2)
    elif base.lower() == 'd':
        intval = int(val, 10)
    elif base.lower() == 'o':
        intval = int(val, 8)
    else:
        raise ValueError(f"Unsupported base: {base}")
    return int(width), base.lower(), intval


def parse_init_file(path):
    """
    Parse a .init file that alternates between signal name and value.
    Skip any names containing wildcards (*).
    Returns a list of (hierarchical_name, cpp_name, value_literal)
    """
    lines = [l.strip() for l in open(path) if l.strip()]
    if len(lines) % 2 != 0:
        raise ValueError("Malformed .init file (odd number of lines). Expected name/value pairs.")

    entries = []
    for i in range(0, len(lines), 2):
        name = lines[i]
        value = lines[i + 1]

        # ✅ Skip wildcard entries
        if "*" in name:
            print(f"[!] Skipping wildcard entry: {name}")
            continue

        cpp_name = name.replace('.', '__DOT__')
        cpp_name = "correctness__DOT__" + cpp_name
        width, base, intval = parse_verilog_value(value)

        # Generate proper C++ literal depending on width
        if width <= 32:
            literal = f"0x{intval:X}U"
        else:
            literal = f"0x{intval:X}ULL"

        entries.append((name, cpp_name, literal))
    return entries

def generate_cpp(entries, out_path="init_registers.cpp"):
    with open(out_path, "w") as f:
        f.write("// Auto-generated Verilator initialization file\n")
        f.write("// Generated by generate_init_cpp.py\n\n")
        f.write("#include \"Vcorrectness.h\"\n\n")
        f.write('#include "Vcorrectness___024root.h"\n\n')
        f.write('#include <iostream>\n\n')
        f.write("extern \"C\" void provide_additional_init_dut(Vcorrectness___024root *dut) {\n")
        f.write("    #if defined(DEBUG) && DEBUG != 0 \n")
        f.write("        std::cout << \"Executiong additional generated init DUT\" << std::endl;\n")
        f.write("    #endif\n")
        f.write("    // Automatically generated register initializations\n\n")
        for name, cpp_name, literal in entries:
            f.write(f"    // {name}\n")
            f.write(f"    dut->{cpp_name} = {literal};\n")
        f.write("}\n")

    print(f"[+] Generated {out_path} with {len(entries)} register assignments.")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_init_cpp.py <input.init> [output.cpp]")
        sys.exit(1)

    input_file = Path(sys.argv[1])
    output_file = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("init_registers.cpp")

    entries = parse_init_file(input_file)
    generate_cpp(entries, output_file)


if __name__ == "__main__":
    main()
