// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS


// Include rmemory initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_MEM_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_MEM_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_MEM_
    `define ENABLE_INITIAL_MEM_
  `endif // not def ENABLE_INITIAL_MEM_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module Rob(	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
  input         clock,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
  input         reset,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
  input         io_enq_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [6:0]  io_enq_uops_0_uopc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [31:0] io_enq_uops_0_debug_inst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [39:0] io_enq_uops_0_debug_pc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_br,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_jal,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_enq_uops_0_br_mask,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [3:0]  io_enq_uops_0_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [5:0]  io_enq_uops_0_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [5:0]  io_enq_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [5:0]  io_enq_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_exception,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_enq_uops_0_exc_cause,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_fence,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_fencei,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_sys_pc2epc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_is_unique,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_flush_on_commit,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [4:0]  io_enq_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_enq_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_uops_0_fp_val,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_enq_uops_0_debug_fsrc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_enq_partial_stall,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [39:0] io_xcpt_fetch_pc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_rob_tail_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_rob_head_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_brupdate_b1_resolve_mask,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_brupdate_b1_mispredict_mask,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_brupdate_b2_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_brupdate_b2_mispredict,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_wb_resps_0_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_wb_resps_0_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [5:0]  io_wb_resps_0_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_wb_resps_1_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_wb_resps_1_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [5:0]  io_wb_resps_1_bits_uop_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_lsu_clr_bsy_0_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_lsu_clr_bsy_0_bits,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_wb_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_wb_valids_1,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_wb_wdata_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_wb_wdata_1,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_rrd_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_rrd_valids_1,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_rrd_uops_0_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_debug_rrd_uops_1_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_rrd_rs1_data_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_rrd_rs1_data_1,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_rrd_rs2_data_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [63:0] io_debug_rrd_rs2_data_1,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_lxcpt_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [1:0]  io_lxcpt_bits_uop_br_mask,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_lxcpt_bits_uop_rob_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [4:0]  io_lxcpt_bits_cause,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input  [39:0] io_lxcpt_bits_badvaddr,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_arch_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_is_br,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_is_jalr,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_is_jal,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [3:0]  io_commit_uops_0_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [5:0]  io_commit_uops_0_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [5:0]  io_commit_uops_0_stale_pdst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_is_fencei,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_uses_ldq,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_uses_stq,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [4:0]  io_commit_uops_0_ldst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_uops_0_ldst_val,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [1:0]  io_commit_uops_0_dst_rtype,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [1:0]  io_commit_uops_0_debug_fsrc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_fflags_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_rbk_valids_0,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_commit_rollback,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_com_xcpt_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [3:0]  io_com_xcpt_bits_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_com_xcpt_bits_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [5:0]  io_com_xcpt_bits_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [63:0] io_com_xcpt_bits_cause,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [63:0] io_com_xcpt_bits_badvaddr,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  input         io_csr_stall,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_flush_valid,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [3:0]  io_flush_bits_ftq_idx,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_flush_bits_edge_inst,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_flush_bits_is_rvc,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [5:0]  io_flush_bits_pc_lob,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output [2:0]  io_flush_bits_flush_typ,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_empty,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_ready,	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
  output        io_flush_frontend	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
);

  wire [63:0]     my_commit_rs2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:310:27]
  wire [63:0]     my_commit_rs1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:309:27]
  wire [63:0]     my_commit_data;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:302:29]
  wire [31:0]     my_commit_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:304:28]
  wire            empty;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:890:41]
  wire            full;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:889:39]
  wire            io_com_xcpt_valid_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:634:41]
  wire            my_commit_valid;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:301:29]
  wire [4:0]      flush_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:478:25]
  wire            flush_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:478:25]
  wire            flush_uop_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:478:25]
  wire            flush_uop_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:478:25]
  wire            flush_uop_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:478:25]
  reg  [1:0]      rob_state;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26]
  reg             rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
  wire            my_ROB_head = rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :307:25]
  reg             rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
  wire            my_ROB_tail = rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :306:25]
  reg             rob_tail_lsb;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:237:29]
  reg             rob_pnr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:240:29]
  wire            io_commit_rollback_0 = rob_state == 2'h2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :244:31]
  wire            com_idx = io_commit_rollback_0 ? rob_tail : rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :236:29, :244:{20,31}]
  reg             maybe_full;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:247:29]
  reg             r_xcpt_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33]
  reg  [1:0]      r_xcpt_uop_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
  reg             r_xcpt_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
  reg  [63:0]     r_xcpt_uop_exc_cause;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
  reg  [39:0]     r_xcpt_badvaddr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:268:29]
  wire            my_commit_ld = my_commit_valid & flush_uop_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:300:26, :301:29, :313:39, :478:25]
  wire            my_commit_ismem = flush_uop_uses_ldq | flush_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:303:29, :315:49, :478:25]
  wire [4:0]      my_commit_target = flush_uop_is_fence | flush_uop_is_fencei ? 5'h0 : flush_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:305:30, :317:{36,68}, :318:22, :320:22, :478:25]
  wire [63:0]     my_commit_exception = io_com_xcpt_valid_0 ? r_xcpt_uop_exc_cause : 64'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29, :311:33, :329:29, :634:41]
  reg             rob_val_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32]
  reg             rob_val_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32]
  reg             rob_bsy_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28]
  reg             rob_bsy_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28]
  reg             rob_unsafe_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:366:28]
  reg             rob_unsafe_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:366:28]
  reg  [6:0]      rob_uop_0_uopc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [31:0]     rob_uop_0_debug_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_rvc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [39:0]     rob_uop_0_debug_pc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_jal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_0_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [3:0]      rob_uop_0_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_0_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_0_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_is_sys_pc2epc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_flush_on_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [4:0]      rob_uop_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_0_fp_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_0_debug_fsrc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [6:0]      rob_uop_1_uopc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [31:0]     rob_uop_1_debug_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_rvc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [39:0]     rob_uop_1_debug_pc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_br;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_jal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_1_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [3:0]      rob_uop_1_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_1_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_1_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [5:0]      rob_uop_1_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_is_sys_pc2epc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_flush_on_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [4:0]      rob_uop_1_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_1_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_uop_1_fp_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg  [1:0]      rob_uop_1_debug_fsrc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
  reg             rob_exception_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:368:28]
  reg             rob_exception_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:368:28]
  wire            _GEN = rob_tail ? rob_val_1 : rob_val_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :364:32, :382:31]
  wire            _GEN_0 = io_lxcpt_valid & io_lxcpt_bits_cause != 5'h10 & ~reset;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14, :455:{33,66}, :457:15]
  wire            _GEN_1 = io_lxcpt_bits_uop_rob_idx ? rob_unsafe_1 : rob_unsafe_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:366:28, :457:15]
  wire            rob_head_vals_0 = rob_head ? rob_val_1 : rob_val_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :364:32, :465:49]
  wire            can_throw_exception_0 = rob_head_vals_0 & (rob_head ? rob_exception_1 : rob_exception_0);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :368:28, :465:49]
  wire [39:0]     my_commit_PC = com_idx ? rob_uop_1_debug_pc : rob_uop_0_debug_pc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :308:26, :367:28, :478:25]
  wire [3:0]      flush_uop_ftq_idx = com_idx ? rob_uop_1_ftq_idx : rob_uop_0_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  wire            flush_uop_edge_inst = com_idx ? rob_uop_1_edge_inst : rob_uop_0_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  wire [5:0]      flush_uop_pc_lob = com_idx ? rob_uop_1_pc_lob : rob_uop_0_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  assign flush_uop_is_fence = com_idx ? rob_uop_1_is_fence : rob_uop_0_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  assign flush_uop_is_fencei = com_idx ? rob_uop_1_is_fencei : rob_uop_0_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  assign flush_uop_uses_ldq = com_idx ? rob_uop_1_uses_ldq : rob_uop_0_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  assign flush_uop_uses_stq = com_idx ? rob_uop_1_uses_stq : rob_uop_0_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  assign flush_uop_ldst = com_idx ? rob_uop_1_ldst : rob_uop_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :367:28, :478:25]
  wire            rbk_row = io_commit_rollback_0 & ~full;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:31, :492:{44,47}, :889:39]
  wire            io_commit_rbk_valids_0_0 = rbk_row & (com_idx ? rob_val_1 : rob_val_0);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :364:32, :492:44, :494:40]
  reg             block_commit_REG;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:94]
  reg             block_commit_REG_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:131]
  reg             block_commit_REG_2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:123]
  wire            block_commit = rob_state != 2'h1 & rob_state != 2'h3 | block_commit_REG | block_commit_REG_2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :617:{33,47,61,84,94,113,123}]
  wire            exception_thrown = can_throw_exception_0 & ~block_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:465:49, :617:{84,113}, :622:{52,55}]
  assign my_commit_valid = rob_head_vals_0 & ~(rob_head ? rob_bsy_1 : rob_bsy_0) & ~io_csr_stall & ~can_throw_exception_0 & ~block_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :301:29, :365:28, :465:49, :471:{40,43,64,67}, :617:{84,113}, :622:55, :624:{43,46,70}]
  wire            is_mini_exception = r_xcpt_uop_exc_cause == 64'h10 | r_xcpt_uop_exc_cause == 64'h11;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29, generators/rocket-chip/src/main/scala/util/package.scala:16:47, :81:59]
  assign io_com_xcpt_valid_0 = exception_thrown & ~is_mini_exception;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:622:52, :634:{41,44}, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
  wire            flush_commit_mask_0 = my_commit_valid & (com_idx ? rob_uop_1_flush_on_commit : rob_uop_0_flush_on_commit);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :301:29, :367:28, :478:25, :649:75]
  wire            flush_val = exception_thrown | flush_commit_mask_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:622:52, :649:75, :651:36]
  reg             r_partial_row;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:761:30]
  wire            _empty_T = rob_head == rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :236:29, :776:33]
  wire            finished_committing_row = my_commit_valid & (my_commit_valid ^ ~rob_head_vals_0) & ~(r_partial_row & _empty_T & ~maybe_full);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:247:29, :301:29, :465:49, :761:30, :774:39, :775:{26,50,59}, :776:{5,21,33,46,49}]
  reg             pnr_maybe_at_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:804:36]
  wire            _io_ready_T = rob_state == 2'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :806:33]
  `ifndef SYNTHESIS	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
    wire _GEN_2 = io_enq_valids_0 & ~reset;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
    wire _GEN_3 = io_lsu_clr_bsy_0_valid & ~reset;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14, :423:16]
    wire _GEN_4 = rob_pnr < rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :240:29, generators/boom/src/main/scala/v3/util/util.scala:364:52]
    wire _GEN_5 = (`PRINTF_COND_) & ~reset;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14, :446:13]
    always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
      if (_GEN_2 & _GEN) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:382:31, :391:14]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
          $error("Assertion failed: [rob] overwriting a valid entry.\n    at rob.scala:391 assert (rob_val(rob_tail) === false.B, \"[rob] overwriting a valid entry.\")\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:391:14]
      end
      if (_GEN_2 & io_enq_uops_0_rob_idx != rob_tail) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :391:14, :392:{14,63}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:392:14]
          $error("Assertion failed\n    at rob.scala:392 assert ((io.enq_uops(w).rob_idx >> log2Ceil(coreWidth)) === rob_tail)\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:392:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:392:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:392:14]
      end
      if (_GEN_3 & ~(io_lsu_clr_bsy_0_bits ? rob_val_1 : rob_val_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :423:{16,31}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:423:16]
          $error("Assertion failed: [rob] store writing back to invalid entry.\n    at rob.scala:423 assert (rob_val(cidx) === true.B, \"[rob] store writing back to invalid entry.\")\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:423:16]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:423:16]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:423:16]
      end
      if (_GEN_3 & ~(io_lsu_clr_bsy_0_bits ? rob_bsy_1 : rob_bsy_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28, :421:26, :423:16, :424:16]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:424:16]
          $error("Assertion failed: [rob] store writing back to a not-busy entry.\n    at rob.scala:424 assert (rob_bsy(cidx) === true.B, \"[rob] store writing back to a not-busy entry.\")\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:424:16]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:424:16]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:424:16]
      end
      if (_GEN_5) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:446:13]
        $fwrite(32'h80000002, "ROB bank %d row %d: valid=%d busy=%d unsafe=%d exc=%d pdst=%d pc_lob=%d inst=%x\n", 1'h0, 1'h0, rob_val_0, rob_bsy_0, rob_unsafe_0, rob_exception_0, rob_uop_0_pdst, rob_uop_0_pc_lob, rob_uop_0_debug_inst);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :365:28, :366:28, :367:28, :368:28, :446:13]
        $fwrite(32'h80000002, "ROB bank %d row %d: valid=%d busy=%d unsafe=%d exc=%d pdst=%d pc_lob=%d inst=%x\n", 1'h0, 1'h1, rob_val_1, rob_bsy_1, rob_unsafe_1, rob_exception_1, rob_uop_1_pdst, rob_uop_1_pc_lob, rob_uop_1_debug_inst);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :365:28, :366:28, :367:28, :368:28, :446:13]
      end
      if (_GEN_0 & ~_GEN_1) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:455:66, :457:15]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:457:15]
          $error("Assertion failed: An instruction marked as safe is causing an exception\n    at rob.scala:457 assert(rob_unsafe(GetRowIdx(io.lxcpt.bits.uop.rob_idx)),\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:457:15]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:457:15]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:457:15]
      end
      if (~reset & my_commit_valid & io_commit_rbk_valids_0_0) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:301:29, :391:14, :494:40, :497:{12,45}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:497:12]
          $error("Assertion failed: com_valids and rbk_valids are mutually exclusive\n    at rob.scala:497 assert (!(io.commit.valids.reduce(_||_) && io.commit.rbk_valids.reduce(_||_)),\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:497:12]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:497:12]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:497:12]
      end
      if (~reset & io_wb_resps_0_valid & ~(io_wb_resps_0_bits_uop_rob_idx ? rob_val_1 : rob_val_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :391:14, :581:{14,72}, :582:16]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
          $error("Assertion failed: [rob] writeback (0) occurred to an invalid ROB entry.\n    at rob.scala:581 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
      end
      if (~reset & io_wb_resps_0_valid & ~(io_wb_resps_0_bits_uop_rob_idx ? rob_bsy_1 : rob_bsy_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28, :391:14, :584:{14,72}, :585:16]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
          $error("Assertion failed: [rob] writeback (0) occurred to a not-busy ROB entry.\n    at rob.scala:584 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
      end
      if (~reset & io_wb_resps_0_valid & (io_wb_resps_0_bits_uop_rob_idx ? rob_uop_1_ldst_val : rob_uop_0_ldst_val) & (io_wb_resps_0_bits_uop_rob_idx ? rob_uop_1_pdst : rob_uop_0_pdst) != io_wb_resps_0_bits_uop_pdst) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, :391:14, :587:{14,72}, :588:{34,51}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
          $error("Assertion failed: [rob] writeback (0) occurred to the wrong pdst.\n    at rob.scala:587 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
      end
      if (~reset & io_wb_resps_1_valid & ~(io_wb_resps_1_bits_uop_rob_idx ? rob_val_1 : rob_val_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :391:14, :581:{14,72}, :582:16]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
          $error("Assertion failed: [rob] writeback (1) occurred to an invalid ROB entry.\n    at rob.scala:581 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:581:14]
      end
      if (~reset & io_wb_resps_1_valid & ~(io_wb_resps_1_bits_uop_rob_idx ? rob_bsy_1 : rob_bsy_0)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28, :391:14, :584:{14,72}, :585:16]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
          $error("Assertion failed: [rob] writeback (1) occurred to a not-busy ROB entry.\n    at rob.scala:584 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:584:14]
      end
      if (~reset & io_wb_resps_1_valid & (io_wb_resps_1_bits_uop_rob_idx ? rob_uop_1_ldst_val : rob_uop_0_ldst_val) & (io_wb_resps_1_bits_uop_rob_idx ? rob_uop_1_pdst : rob_uop_0_pdst) != io_wb_resps_1_bits_uop_pdst) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, :391:14, :587:{14,72}, :588:{34,51}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
          $error("Assertion failed: [rob] writeback (1) occurred to the wrong pdst.\n    at rob.scala:587 assert (!(io.wb_resps(i).valid && MatchBank(GetBankIdx(rob_idx)) &&\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:587:14]
      end
      if (~reset & exception_thrown & ~r_xcpt_val) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33, :391:14, :622:52, :742:{10,30,33}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:742:10]
          $error("Assertion failed: ROB trying to throw an exception, but it doesn't have a valid xcpt_cause\n    at rob.scala:742 assert (!(exception_thrown && !r_xcpt_val),\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:742:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:742:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:742:10]
      end
      if (~reset & empty & r_xcpt_val) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33, :391:14, :745:{10,19}, :890:41]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:745:10]
          $error("Assertion failed: ROB is empty, but believes it has an outstanding exception.\n    at rob.scala:745 assert (!(empty && r_xcpt_val),\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:745:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:745:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:745:10]
      end
      if (~reset & exception_thrown & r_xcpt_uop_rob_idx != rob_head) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :267:29, :391:14, :622:52, :748:{10,34,68}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:748:10]
          $error("Assertion failed: ROB is throwing an exception, but the stored exception information's rob_idx does not match the rob_head\n    at rob.scala:748 assert (!(will_throw_exception && (GetRowIdx(r_xcpt_uop.rob_idx) =/= rob_head)),\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:748:10]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:748:10]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:748:10]
      end
      if (_GEN_5)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:446:13, :766:9]
        $fwrite(32'h80000002, "r_partial row %d, ROB head: %d, head_lsb: %d, tail: %d, tail_lsb: %d, full: %d, empty: %d, state: %d\n", r_partial_row, rob_head, 1'h0, rob_tail, rob_tail_lsb, full, empty, rob_state);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :232:29, :236:29, :237:29, :761:30, :766:9, :889:39, :890:41]
      if (~reset & ~(_GEN_4 ^ rob_head < rob_tail ^ rob_pnr >= rob_tail | rob_pnr == rob_tail)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :236:29, :240:29, :391:14, :830:{9,10,60,75}, generators/boom/src/main/scala/v3/util/util.scala:364:{52,58,64,72,78}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:830:9]
          $error("Assertion failed\n    at rob.scala:830 assert(!IsOlder(rob_pnr_idx, rob_head_idx, rob_tail_idx) || rob_pnr_idx === rob_tail_idx)\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:830:9]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:830:9]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:830:9]
      end
      if (~reset & ~(rob_tail < rob_head ^ _GEN_4 ^ rob_tail >= rob_pnr | full)) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :236:29, :240:29, :391:14, :833:{9,10,60}, :889:39, generators/boom/src/main/scala/v3/util/util.scala:364:{52,58,64,72}]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:833:9]
          $error("Assertion failed\n    at rob.scala:833 assert(!IsOlder(rob_tail_idx, rob_pnr_idx, rob_head_idx) || full)\n");	// @[generators/boom/src/main/scala/v3/exu/rob.scala:833:9]
        if (`STOP_COND_)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:833:9]
          $fatal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:833:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire            _GEN_6 = io_commit_rollback_0 & (rob_tail != rob_head | maybe_full);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :236:29, :244:31, :247:29, :840:{34,47,60}]
  wire            rob_deq = _GEN_6 | finished_committing_row;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:774:39, :775:59, :778:34, :840:{34,76}, :844:13]
  assign full = _empty_T & maybe_full;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:247:29, :776:33, :889:39]
  assign empty = _empty_T & ~rob_head_vals_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:465:49, :776:33, :890:{41,66}]
  reg             REG;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:910:30]
  reg             REG_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:910:22]
  reg             REG_2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:926:22]
  wire            do_inc_row = ~((rob_pnr ? rob_val_1 : rob_val_0) & ((rob_pnr ? rob_unsafe_1 : rob_unsafe_0) | (rob_pnr ? rob_exception_1 : rob_exception_0))) & (rob_pnr != rob_tail | full & ~pnr_maybe_at_tail);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :240:29, :364:32, :366:28, :368:28, :560:{43,67}, :804:36, :807:{23,52,64,77,86,89}, :889:39]
  wire            _GEN_7 = io_commit_rollback_0 & _empty_T & ~maybe_full;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:31, :247:29, :776:{33,49}, :845:{41,68}]
  wire            _GEN_8 = io_enq_valids_0 & ~io_enq_partial_stall;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:856:{45,48}]
  wire [1:0]      _GEN_9 = empty ? 2'h1 : rob_state;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :890:41, :921:22, :922:21]
  wire [3:0][1:0] _GEN_10 = {{REG_2 ? 2'h2 : _GEN_9}, {_GEN_9}, {REG_1 ? 2'h2 : io_enq_valids_0 & io_enq_uops_0_is_unique ? 2'h3 : rob_state}, {2'h1}};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :244:31, :806:{33,59}, :904:24, :906:19, :910:{22,51}, :911:21, :914:{36,65}, :915:25, :921:22, :922:21, :926:{22,42}, :927:21, :928:29]
  wire            _GEN_11 = io_enq_valids_0 & ~rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :364:32, :381:29, :382:31]
  wire            _GEN_12 = io_enq_valids_0 & rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :364:32, :381:29, :382:31]
  wire            _rob_bsy_T = io_enq_uops_0_is_fence | io_enq_uops_0_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:383:60]
  wire            _GEN_13 = _GEN_11 ? ~_rob_bsy_T : rob_bsy_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :365:28, :381:29, :382:31, :383:{31,34,60}]
  wire            _GEN_14 = _GEN_12 ? ~_rob_bsy_T : rob_bsy_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :365:28, :381:29, :382:31, :383:{31,34,60}]
  wire            _rob_unsafe_T_4 = io_enq_uops_0_uses_ldq | io_enq_uops_0_uses_stq & ~io_enq_uops_0_is_fence | io_enq_uops_0_is_br | io_enq_uops_0_is_jalr;	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:152:{35,48,51,62,71}]
  wire            _GEN_15 = _GEN_11 ? _rob_unsafe_T_4 : rob_unsafe_0;	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:152:{35,62,71}, generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :366:28, :381:29, :382:31, :385:31]
  wire            _GEN_16 = _GEN_12 ? _rob_unsafe_T_4 : rob_unsafe_1;	// @[generators/boom/src/main/scala/v3/common/micro-op.scala:152:{35,62,71}, generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :366:28, :381:29, :382:31, :385:31]
  wire            _GEN_17 = io_enq_valids_0 & ~_GEN;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:382:31, :393:{44,47}]
  wire            _GEN_18 = io_wb_resps_0_valid & ~io_wb_resps_0_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :404:69, :405:31]
  wire            _GEN_19 = io_wb_resps_0_valid & io_wb_resps_0_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :404:69, :405:31]
  wire            _GEN_20 = ~io_wb_resps_1_bits_uop_rob_idx | _GEN_18;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :404:69, :405:31]
  wire            _GEN_21 = io_wb_resps_1_bits_uop_rob_idx | _GEN_19;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :404:69, :405:31]
  wire            _GEN_22 = io_lsu_clr_bsy_0_valid & ~io_lsu_clr_bsy_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:404:69, :419:75, :421:26]
  wire            _GEN_23 = io_lsu_clr_bsy_0_valid & io_lsu_clr_bsy_0_bits;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:404:69, :419:75, :421:26]
  wire            _GEN_24 = rbk_row & ~com_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :381:29, :492:44, :500:20, :501:30]
  wire            _GEN_25 = rbk_row & com_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:244:20, :381:29, :492:44, :500:20, :501:30]
  wire [1:0]      _GEN_26 = io_brupdate_b1_mispredict_mask & rob_uop_0_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, generators/boom/src/main/scala/v3/util/util.scala:118:51]
  wire [1:0]      _GEN_27 = io_brupdate_b1_mispredict_mask & rob_uop_1_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, generators/boom/src/main/scala/v3/util/util.scala:118:51]
  wire [2:0]      _GEN_28 = {~rob_head, _GEN_26};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :500:20, :522:7, :523:20, :543:25, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
  wire [2:0]      _GEN_29 = {rob_head, _GEN_27};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :500:20, :522:7, :523:20, :543:25, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
  wire            _GEN_30 = ~flush_val & rob_state != 2'h2;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :651:36, :712:{9,47,60}]
  wire            _GEN_31 = ~r_xcpt_val | io_lxcpt_bits_uop_rob_idx < r_xcpt_uop_rob_idx ^ io_lxcpt_bits_uop_rob_idx < rob_head ^ r_xcpt_uop_rob_idx < rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :266:33, :267:29, :719:{13,25}, generators/boom/src/main/scala/v3/util/util.scala:364:{52,58,64,72,78}]
  wire            _GEN_32 = ~r_xcpt_val & io_enq_valids_0 & io_enq_uops_0_exception;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33, :709:38, :719:13, :725:30]
  wire [1:0]      next_xcpt_uop_br_mask = _GEN_30 ? (io_lxcpt_valid ? (_GEN_31 ? io_lxcpt_bits_uop_br_mask : r_xcpt_uop_br_mask) : _GEN_32 ? io_enq_uops_0_br_mask : r_xcpt_uop_br_mask) : r_xcpt_uop_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29, :706:17, :709:38, :712:{47,76}, :718:27, :719:{25,93}, :721:33, :725:{30,56}, :730:23]
  wire            _GEN_33 = _GEN_11 | rob_val_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
  wire            _GEN_34 = _GEN_12 | rob_val_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
  always @(posedge clock) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
    if (_GEN_0)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:455:66, :457:15]
      assert__assert_6: assert(_GEN_1);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:457:15]
    if (reset) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      rob_state <= 2'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26]
      rob_head <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
      rob_tail <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
      rob_tail_lsb <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:237:29]
      rob_pnr <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:240:29]
      maybe_full <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:247:29]
      r_xcpt_val <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33]
      rob_val_0 <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32]
      rob_val_1 <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32]
      r_partial_row <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:761:30]
      pnr_maybe_at_tail <= 1'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:804:36]
    end
    else begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      rob_state <= _GEN_10[rob_state];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :244:31, :806:{33,59}, :904:24, :906:19, :910:51, :921:22, :926:42]
      if (finished_committing_row)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:774:39, :775:59]
        rob_head <= rob_head - 1'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, generators/boom/src/main/scala/v3/util/util.scala:204:14]
      if (_GEN_6)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:840:34]
        rob_tail <= rob_tail - 1'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, generators/boom/src/main/scala/v3/util/util.scala:221:14]
      else if (~_GEN_7) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:845:{41,68,84}, :851:20, :853:43]
        if (io_brupdate_b2_mispredict)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
          rob_tail <= io_brupdate_b2_uop_rob_idx - 1'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, generators/boom/src/main/scala/v3/util/util.scala:204:14]
        else if (_GEN_8)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:856:45]
          rob_tail <= rob_tail - 1'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, generators/boom/src/main/scala/v3/util/util.scala:204:14]
      end
      rob_tail_lsb <= ~_GEN_6 & ~_GEN_7 & ~(io_brupdate_b2_mispredict | _GEN_8 | io_enq_valids_0 & io_enq_partial_stall) & rob_tail_lsb;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:237:29, :840:{34,76}, :843:18, :845:{41,68,84}, :851:20, :853:43, :855:18, :856:{45,71}, :858:18, :860:{45,70}, :867:20]
      if (empty & io_enq_valids_0)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:808:17, :890:41]
        rob_pnr <= rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29, :240:29]
      else if ((_io_ready_T | (&rob_state)) & do_inc_row)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:229:26, :806:{33,46,59}, :807:52, :815:30]
        rob_pnr <= rob_pnr - 1'h1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:240:29, generators/boom/src/main/scala/v3/util/util.scala:204:14]
      maybe_full <= |{~rob_deq & (~(_GEN_6 | _GEN_7 | io_brupdate_b2_mispredict) & _GEN_8 | maybe_full), io_brupdate_b1_mispredict_mask};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:247:29, :778:34, :826:26, :838:25, :840:{34,76}, :844:13, :845:{41,68,84}, :853:43, :856:{45,71}, :888:{26,38,53,87}]
      r_xcpt_val <= {flush_val, io_brupdate_b1_mispredict_mask & next_xcpt_uop_br_mask} == 3'h0 & (_GEN_30 ? (io_lxcpt_valid ? _GEN_31 | r_xcpt_val : _GEN_32 | r_xcpt_val) : r_xcpt_val);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:266:33, :651:36, :706:17, :709:38, :712:{47,76}, :718:27, :719:{25,93}, :720:33, :725:{30,56}, :729:23, :738:{24,73}, :739:16, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      rob_val_0 <= my_commit_valid ? ~((|_GEN_28) | _GEN_24) & _GEN_33 : ~((|_GEN_26) | _GEN_24) & _GEN_33;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:301:29, :364:32, :381:29, :382:31, :500:20, :501:30, :522:7, :523:20, :542:27, :543:25, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      rob_val_1 <= my_commit_valid ? ~((|_GEN_29) | _GEN_25) & _GEN_34 : ~((|_GEN_27) | _GEN_25) & _GEN_34;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:301:29, :364:32, :381:29, :382:31, :500:20, :501:30, :522:7, :523:20, :542:27, :543:25, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      if (io_enq_valids_0)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
        r_partial_row <= io_enq_partial_stall;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:761:30]
      pnr_maybe_at_tail <= ~rob_deq & (do_inc_row | pnr_maybe_at_tail);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:778:34, :804:36, :807:52, :826:{26,35,50}, :840:76, :844:13]
    end
    r_xcpt_uop_br_mask <= next_xcpt_uop_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29, :706:17, :712:76, :718:27, generators/boom/src/main/scala/v3/util/util.scala:85:{25,27}]
    if (_GEN_30) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:712:47]
      if (io_lxcpt_valid) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
        if (_GEN_31) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:719:25]
          r_xcpt_uop_rob_idx <= io_lxcpt_bits_uop_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
          r_xcpt_uop_exc_cause <= {59'h0, io_lxcpt_bits_cause};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29, :722:33, generators/rocket-chip/src/main/scala/util/package.scala:16:47]
          r_xcpt_badvaddr <= io_lxcpt_bits_badvaddr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:268:29]
        end
      end
      else if (_GEN_32) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:709:38, :725:30]
        r_xcpt_uop_rob_idx <= io_enq_uops_0_rob_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
        r_xcpt_uop_exc_cause <= io_enq_uops_0_exc_cause;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:267:29]
        r_xcpt_badvaddr <= {io_xcpt_fetch_pc[39:6], io_enq_uops_0_pc_lob};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14, :268:29, :731:76]
      end
    end
    rob_bsy_0 <= ~_GEN_22 & (io_wb_resps_1_valid ? ~_GEN_20 & _GEN_13 : ~_GEN_18 & _GEN_13);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28, :381:29, :383:31, :404:69, :405:31, :419:75, :421:26]
    rob_bsy_1 <= ~_GEN_23 & (io_wb_resps_1_valid ? ~_GEN_21 & _GEN_14 : ~_GEN_19 & _GEN_14);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:365:28, :381:29, :383:31, :404:69, :405:31, :419:75, :421:26]
    rob_unsafe_0 <= ~_GEN_22 & (io_wb_resps_1_valid ? ~_GEN_20 & _GEN_15 : ~_GEN_18 & _GEN_15);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:366:28, :381:29, :385:31, :404:69, :405:31, :406:31, :419:75, :421:26, :422:26]
    rob_unsafe_1 <= ~_GEN_23 & (io_wb_resps_1_valid ? ~_GEN_21 & _GEN_16 : ~_GEN_19 & _GEN_16);	// @[generators/boom/src/main/scala/v3/exu/rob.scala:366:28, :381:29, :385:31, :404:69, :405:31, :406:31, :419:75, :421:26, :422:26]
    if (_GEN_11) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
      rob_uop_0_uopc <= io_enq_uops_0_uopc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_rvc <= io_enq_uops_0_is_rvc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_debug_pc <= io_enq_uops_0_debug_pc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_br <= io_enq_uops_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_jalr <= io_enq_uops_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_jal <= io_enq_uops_0_is_jal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_ftq_idx <= io_enq_uops_0_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_edge_inst <= io_enq_uops_0_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_pc_lob <= io_enq_uops_0_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_pdst <= io_enq_uops_0_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_stale_pdst <= io_enq_uops_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_fence <= io_enq_uops_0_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_fencei <= io_enq_uops_0_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_uses_ldq <= io_enq_uops_0_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_uses_stq <= io_enq_uops_0_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_is_sys_pc2epc <= io_enq_uops_0_is_sys_pc2epc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_flush_on_commit <= io_enq_uops_0_flush_on_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_ldst <= io_enq_uops_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_ldst_val <= io_enq_uops_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_dst_rtype <= io_enq_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_0_fp_val <= io_enq_uops_0_fp_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    if (my_commit_valid ? (|_GEN_28) : rbk_row ? (|{~rob_tail, _GEN_26}) : (|_GEN_26))	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :301:29, :381:29, :382:31, :492:44, :500:20, :522:7, :523:20, :524:33, :543:25, :564:27, :565:36, :567:5, :568:36, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      rob_uop_0_debug_inst <= 32'h4033;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    else if (io_enq_valids_0) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
      if (rob_tail) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
      end
      else	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
        rob_uop_0_debug_inst <= io_enq_uops_0_debug_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    else if (_GEN_17 & ~rob_tail)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :367:28, :382:31, :393:{44,67}, :394:36]
      rob_uop_0_debug_inst <= 32'h4033;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    if ((|_GEN_26) | ~rob_val_0) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :522:7, :525:32, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      if (_GEN_11)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
        rob_uop_0_br_mask <= io_enq_uops_0_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :522:7, :525:32]
      rob_uop_0_br_mask <= rob_uop_0_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, generators/boom/src/main/scala/v3/util/util.scala:89:{21,23}]
    if (io_brupdate_b2_mispredict & ~io_brupdate_b2_uop_rob_idx)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :535:58, :536:65]
      rob_uop_0_debug_fsrc <= 2'h3;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    else if (_GEN_11)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
      rob_uop_0_debug_fsrc <= io_enq_uops_0_debug_fsrc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    if (_GEN_12) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
      rob_uop_1_uopc <= io_enq_uops_0_uopc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_rvc <= io_enq_uops_0_is_rvc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_debug_pc <= io_enq_uops_0_debug_pc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_br <= io_enq_uops_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_jalr <= io_enq_uops_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_jal <= io_enq_uops_0_is_jal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_ftq_idx <= io_enq_uops_0_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_edge_inst <= io_enq_uops_0_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_pc_lob <= io_enq_uops_0_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_pdst <= io_enq_uops_0_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_stale_pdst <= io_enq_uops_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_fence <= io_enq_uops_0_is_fence;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_fencei <= io_enq_uops_0_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_uses_ldq <= io_enq_uops_0_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_uses_stq <= io_enq_uops_0_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_is_sys_pc2epc <= io_enq_uops_0_is_sys_pc2epc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_flush_on_commit <= io_enq_uops_0_flush_on_commit;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_ldst <= io_enq_uops_0_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_ldst_val <= io_enq_uops_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_dst_rtype <= io_enq_uops_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
      rob_uop_1_fp_val <= io_enq_uops_0_fp_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    if (my_commit_valid ? (|_GEN_29) : rbk_row ? (|{rob_tail, _GEN_27}) : (|_GEN_27))	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :301:29, :381:29, :492:44, :500:20, :522:7, :523:20, :524:33, :543:25, :564:27, :565:36, :567:5, :568:36, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      rob_uop_1_debug_inst <= 32'h4033;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    else if (io_enq_valids_0) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:225:14]
      if (rob_tail)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
        rob_uop_1_debug_inst <= io_enq_uops_0_debug_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    else if (_GEN_17 & rob_tail)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29, :367:28, :393:{44,67}, :394:36]
      rob_uop_1_debug_inst <= 32'h4033;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    if ((|_GEN_27) | ~rob_val_1) begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :522:7, :525:32, generators/boom/src/main/scala/v3/util/util.scala:118:{51,59}]
      if (_GEN_12)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
        rob_uop_1_br_mask <= io_enq_uops_0_br_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    end
    else	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :522:7, :525:32]
      rob_uop_1_br_mask <= rob_uop_1_br_mask & ~io_brupdate_b1_resolve_mask;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28, generators/boom/src/main/scala/v3/util/util.scala:89:{21,23}]
    if (io_brupdate_b2_mispredict & io_brupdate_b2_uop_rob_idx)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:381:29, :535:58, :536:65]
      rob_uop_1_debug_fsrc <= 2'h3;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    else if (_GEN_12)	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :381:29, :382:31]
      rob_uop_1_debug_fsrc <= io_enq_uops_0_debug_fsrc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:367:28]
    rob_exception_0 <= ~_GEN_24 & (io_lxcpt_valid & ~io_lxcpt_bits_uop_rob_idx | (_GEN_11 ? io_enq_uops_0_exception : rob_exception_0));	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :368:28, :381:29, :382:31, :387:31, :453:79, :454:59, :462:89, :500:20, :501:30, :502:30]
    rob_exception_1 <= ~_GEN_25 & (io_lxcpt_valid & io_lxcpt_bits_uop_rob_idx | (_GEN_12 ? io_enq_uops_0_exception : rob_exception_1));	// @[generators/boom/src/main/scala/v3/exu/rob.scala:364:32, :368:28, :381:29, :382:31, :387:31, :453:79, :454:59, :462:89, :500:20, :501:30, :502:30]
    block_commit_REG <= exception_thrown;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:94, :622:52]
    block_commit_REG_1 <= exception_thrown;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:131, :622:52]
    block_commit_REG_2 <= block_commit_REG_1;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:617:{123,131}]
    REG <= exception_thrown;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:622:52, :910:30]
    REG_1 <= REG;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:910:{22,30}]
    REG_2 <= exception_thrown;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:622:52, :926:22]
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:37];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
    initial begin	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
        `INIT_RANDOM_PROLOG_	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
        for (logic [5:0] i = 6'h0; i < 6'h26; i += 6'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
        end	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
        rob_state = _RANDOM[6'h0][1:0];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26]
        rob_head = _RANDOM[6'h0][2];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :232:29]
        rob_tail = _RANDOM[6'h0][4];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :236:29]
        rob_tail_lsb = _RANDOM[6'h0][5];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :237:29]
        rob_pnr = _RANDOM[6'h0][6];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :240:29]
        maybe_full = _RANDOM[6'h0][8];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :247:29]
        r_xcpt_val = _RANDOM[6'h0][9];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :229:26, :266:33]
        r_xcpt_uop_br_mask = _RANDOM[6'h5][8:7];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :267:29]
        r_xcpt_uop_rob_idx = _RANDOM[6'h6][22];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :267:29]
        r_xcpt_uop_exc_cause = {_RANDOM[6'h8][31:6], _RANDOM[6'h9], _RANDOM[6'hA][5:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :267:29]
        r_xcpt_badvaddr = {_RANDOM[6'hB][31], _RANDOM[6'hC], _RANDOM[6'hD][6:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29]
        rob_val_0 = _RANDOM[6'hD][17];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, :364:32]
        rob_val_1 = _RANDOM[6'hD][18];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, :364:32]
        rob_bsy_0 = _RANDOM[6'h25][13];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28]
        rob_bsy_1 = _RANDOM[6'hD][20];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, :365:28]
        rob_unsafe_0 = _RANDOM[6'h25][14];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :366:28]
        rob_unsafe_1 = _RANDOM[6'hD][22];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, :366:28]
        rob_uop_0_uopc = _RANDOM[6'hD][29:23];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, :367:28]
        rob_uop_0_debug_inst = {_RANDOM[6'hE][31:30], _RANDOM[6'hF][29:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_rvc = _RANDOM[6'hF][30];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_debug_pc = {_RANDOM[6'hF][31], _RANDOM[6'h10], _RANDOM[6'h11][6:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_br = _RANDOM[6'h12][16];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_jalr = _RANDOM[6'h12][17];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_jal = _RANDOM[6'h12][18];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_br_mask = _RANDOM[6'h12][21:20];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_ftq_idx = _RANDOM[6'h12][26:23];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_edge_inst = _RANDOM[6'h12][27];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_pc_lob = {_RANDOM[6'h12][31:28], _RANDOM[6'h13][1:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_pdst = _RANDOM[6'h14][17:12];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_stale_pdst = _RANDOM[6'h15][17:12];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_fence = _RANDOM[6'h17][28];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_fencei = _RANDOM[6'h17][29];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_uses_ldq = _RANDOM[6'h17][31];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_uses_stq = _RANDOM[6'h18][0];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_is_sys_pc2epc = _RANDOM[6'h18][1];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_flush_on_commit = _RANDOM[6'h18][3];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_ldst = _RANDOM[6'h18][9:5];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_ldst_val = _RANDOM[6'h18][25];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_dst_rtype = _RANDOM[6'h18][27:26];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_fp_val = _RANDOM[6'h19][1];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_0_debug_fsrc = _RANDOM[6'h19][9:8];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_uopc = _RANDOM[6'h19][18:12];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_debug_inst = {_RANDOM[6'h1A][31:19], _RANDOM[6'h1B][18:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_rvc = _RANDOM[6'h1B][19];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_debug_pc = {_RANDOM[6'h1B][31:20], _RANDOM[6'h1C][27:0]};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_br = _RANDOM[6'h1E][5];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_jalr = _RANDOM[6'h1E][6];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_jal = _RANDOM[6'h1E][7];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_br_mask = _RANDOM[6'h1E][10:9];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_ftq_idx = _RANDOM[6'h1E][15:12];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_edge_inst = _RANDOM[6'h1E][16];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_pc_lob = _RANDOM[6'h1E][22:17];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_pdst = _RANDOM[6'h20][6:1];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_stale_pdst = _RANDOM[6'h21][6:1];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_fence = _RANDOM[6'h23][17];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_fencei = _RANDOM[6'h23][18];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_uses_ldq = _RANDOM[6'h23][20];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_uses_stq = _RANDOM[6'h23][21];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_is_sys_pc2epc = _RANDOM[6'h23][22];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_flush_on_commit = _RANDOM[6'h23][24];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_ldst = _RANDOM[6'h23][30:26];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_ldst_val = _RANDOM[6'h24][14];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_dst_rtype = _RANDOM[6'h24][16:15];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_fp_val = _RANDOM[6'h24][22];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_uop_1_debug_fsrc = _RANDOM[6'h24][30:29];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :367:28]
        rob_exception_0 = _RANDOM[6'h25][1];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :368:28]
        rob_exception_1 = _RANDOM[6'h25][2];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :368:28]
        block_commit_REG = _RANDOM[6'h25][5];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :617:94]
        block_commit_REG_1 = _RANDOM[6'h25][6];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :617:131]
        block_commit_REG_2 = _RANDOM[6'h25][7];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :617:123]
        r_partial_row = _RANDOM[6'h25][8];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :761:30]
        pnr_maybe_at_tail = _RANDOM[6'h25][9];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :804:36]
        REG = _RANDOM[6'h25][10];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :910:30]
        REG_1 = _RANDOM[6'h25][11];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :910:22]
        REG_2 = _RANDOM[6'h25][12];	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :365:28, :926:22]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  my_ROB_inst_2x32 my_ROB_inst_ext (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:297:24]
    .R0_addr (rob_head),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (my_commit_inst),
    .W0_addr (rob_tail),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
    .W0_en   (io_enq_valids_0),
    .W0_clk  (clock),
    .W0_data (io_enq_uops_0_debug_inst)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:297:24]
  rob_debug_inst_mem_0 rob_debug_inst_mem_0 (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:352:41]
    .R0_addr (rob_head),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
    .R0_en   (my_commit_valid),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:301:29]
    .R0_clk  (clock),
    .W0_addr (rob_tail),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:236:29]
    .W0_en   (io_enq_valids_0),
    .W0_clk  (clock),
    .W0_data (io_enq_uops_0_debug_inst)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:352:41]
  rob_debug_2x64 rob_debug_wdata_ext (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:371:30]
    .R0_addr (rob_head),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (my_commit_data),
    .W0_addr (io_wb_resps_1_bits_uop_rob_idx),
    .W0_en   (io_debug_wb_valids_1),
    .W0_clk  (clock),
    .W0_data (io_debug_wb_wdata_1),
    .W1_addr (io_wb_resps_0_bits_uop_rob_idx),
    .W1_en   (io_debug_wb_valids_0),
    .W1_clk  (clock),
    .W1_data (io_debug_wb_wdata_0)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:371:30]
  rob_debug_2x64 rob_debug_rs1_data_ext (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:372:33]
    .R0_addr (rob_head),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (my_commit_rs1),
    .W0_addr (io_debug_rrd_uops_1_rob_idx),
    .W0_en   (io_debug_rrd_valids_1),
    .W0_clk  (clock),
    .W0_data (io_debug_rrd_rs1_data_1),
    .W1_addr (io_debug_rrd_uops_0_rob_idx),
    .W1_en   (io_debug_rrd_valids_0),
    .W1_clk  (clock),
    .W1_data (io_debug_rrd_rs1_data_0)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:372:33]
  rob_debug_2x64 rob_debug_rs2_data_ext (	// @[generators/boom/src/main/scala/v3/exu/rob.scala:373:33]
    .R0_addr (rob_head),	// @[generators/boom/src/main/scala/v3/exu/rob.scala:232:29]
    .R0_en   (1'h1),
    .R0_clk  (clock),
    .R0_data (my_commit_rs2),
    .W0_addr (io_debug_rrd_uops_1_rob_idx),
    .W0_en   (io_debug_rrd_valids_1),
    .W0_clk  (clock),
    .W0_data (io_debug_rrd_rs2_data_1),
    .W1_addr (io_debug_rrd_uops_0_rob_idx),
    .W1_en   (io_debug_rrd_valids_0),
    .W1_clk  (clock),
    .W1_data (io_debug_rrd_rs2_data_0)
  );	// @[generators/boom/src/main/scala/v3/exu/rob.scala:373:33]
  assign io_rob_tail_idx = rob_tail;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :236:29]
  assign io_rob_head_idx = rob_head;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :232:29]
  assign io_commit_valids_0 = my_commit_valid;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :301:29]
  assign io_commit_arch_valids_0 = my_commit_valid;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :301:29]
  assign io_commit_uops_0_is_br = com_idx ? rob_uop_1_is_br : rob_uop_0_is_br;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_is_jalr = com_idx ? rob_uop_1_is_jalr : rob_uop_0_is_jalr;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_is_jal = com_idx ? rob_uop_1_is_jal : rob_uop_0_is_jal;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_ftq_idx = flush_uop_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_commit_uops_0_pdst = com_idx ? rob_uop_1_pdst : rob_uop_0_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_stale_pdst = com_idx ? rob_uop_1_stale_pdst : rob_uop_0_stale_pdst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_is_fencei = flush_uop_is_fencei;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_commit_uops_0_uses_ldq = flush_uop_uses_ldq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_commit_uops_0_uses_stq = flush_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_commit_uops_0_ldst = flush_uop_ldst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_commit_uops_0_ldst_val = com_idx ? rob_uop_1_ldst_val : rob_uop_0_ldst_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_dst_rtype = com_idx ? rob_uop_1_dst_rtype : rob_uop_0_dst_rtype;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_commit_uops_0_debug_fsrc = io_brupdate_b2_mispredict & io_brupdate_b2_uop_rob_idx == com_idx ? 2'h3 : com_idx ? rob_uop_1_debug_fsrc : rob_uop_0_debug_fsrc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25, :484:57, :485:{45,58}, :486:36]
  assign io_commit_fflags_valid = my_commit_valid & (com_idx ? rob_uop_1_fp_val : rob_uop_0_fp_val) & ~flush_uop_uses_stq;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :301:29, :367:28, :478:25, :682:27, :683:32, :684:7]
  assign io_commit_rbk_valids_0 = io_commit_rbk_valids_0_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :494:40]
  assign io_commit_rollback = io_commit_rollback_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:31]
  assign io_com_xcpt_valid = io_com_xcpt_valid_0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :634:41]
  assign io_com_xcpt_bits_ftq_idx = flush_uop_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_com_xcpt_bits_edge_inst = flush_uop_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_com_xcpt_bits_pc_lob = flush_uop_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_com_xcpt_bits_cause = r_xcpt_uop_exc_cause;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :267:29]
  assign io_com_xcpt_bits_badvaddr = {{24{r_xcpt_badvaddr[39]}}, r_xcpt_badvaddr};	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :268:29, generators/boom/src/main/scala/v3/util/util.scala:262:{20,25,46}]
  assign io_flush_valid = flush_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :651:36]
  assign io_flush_bits_ftq_idx = flush_uop_ftq_idx;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_flush_bits_edge_inst = flush_uop_edge_inst;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_flush_bits_is_rvc = com_idx ? rob_uop_1_is_rvc : rob_uop_0_is_rvc;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :244:20, :367:28, :478:25]
  assign io_flush_bits_pc_lob = flush_uop_pc_lob;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :478:25]
  assign io_flush_bits_flush_typ = flush_val ? (flush_commit_mask_0 & (com_idx ? rob_uop_1_uopc : rob_uop_0_uopc) == 7'h6A ? 3'h3 : exception_thrown & ~is_mini_exception ? 3'h1 : exception_thrown | rob_head_vals_0 & (com_idx ? rob_uop_1_is_sys_pc2epc : rob_uop_0_is_sys_pc2epc) ? 3'h2 : 3'h4) : 3'h0;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:180:10, :181:10, :182:10, :183:10, :219:7, :244:20, :367:28, :465:49, :478:25, :622:52, :634:44, :640:31, :642:39, :649:75, :651:36, :666:66, :667:{62,80}, generators/rocket-chip/src/main/scala/util/package.scala:81:59]
  assign io_empty = empty;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :890:41]
  assign io_ready = _io_ready_T & ~full & ~r_xcpt_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :266:33, :492:47, :742:33, :806:33, :889:39, :896:{47,56}]
  assign io_flush_frontend = r_xcpt_val;	// @[generators/boom/src/main/scala/v3/exu/rob.scala:219:7, :266:33]
endmodule

