// Generated by CIRCT firtool-1.75.0
module ForwardingAgeLogic(	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1756:7]
  input  [4:0] io_addr_matches,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1758:15]
  input  [2:0] io_youngest_st_idx,	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1758:15]
  output [2:0] io_forwarding_idx	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1758:15]
);

  wire [4:0] _matches_T_1 = io_addr_matches & {io_youngest_st_idx > 3'h4, io_youngest_st_idx[2], io_youngest_st_idx > 3'h2, |(io_youngest_st_idx[2:1]), |io_youngest_st_idx};	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1772:19, :1773:17, :1774:7, :1775:22, :1781:{35,46}]
  assign io_forwarding_idx = _matches_T_1[4] ? 3'h4 : _matches_T_1[3] ? 3'h3 : _matches_T_1[2] ? 3'h2 : _matches_T_1[1] ? 3'h1 : _matches_T_1[0] ? 3'h0 : io_addr_matches[4] ? 3'h4 : io_addr_matches[3] ? 3'h3 : io_addr_matches[2] ? 3'h2 : {2'h0, io_addr_matches[1]};	// @[generators/boom/src/main/scala/v3/lsu/lsu.scala:1756:7, :1772:19, :1773:17, :1774:7, :1775:22, :1781:35, :1803:26, :1804:13, :1806:33]
endmodule

