// Generated by CIRCT firtool-1.75.0

// Users can define 'PRINTF_COND' to add an extra gate to prints.
`ifndef PRINTF_COND_
  `ifdef PRINTF_COND
    `define PRINTF_COND_ (`PRINTF_COND)
  `else  // PRINTF_COND
    `define PRINTF_COND_ 1
  `endif // PRINTF_COND
`endif // not def PRINTF_COND_
module MemReader(	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13]
  input  [20:0] io_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [2:0]  io_size,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input         io_signed,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  output [63:0] io_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  output [17:0] io_mem_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_0,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_1,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_2,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_3,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_4,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_5,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_6,	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
  input  [7:0]  io_mem_data_7	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:128:21]
);

  wire [63:0]     alignedWord = {io_mem_data_0, io_mem_data_1, io_mem_data_2, io_mem_data_3, io_mem_data_4, io_mem_data_5, io_mem_data_6, io_mem_data_7} >> {58'h0, io_addr[2:0], 3'h0};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:138:46, :149:{31,41}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16]
      if ((`PRINTF_COND_) & ~reset) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:150:16, :152:16]
        $fwrite(32'h80000002, "MemReader: addr %x size %d signed %d mem_addr %x mem_data %x alignedWord %x\n", io_addr, io_size, io_signed, io_addr[20:3], {io_mem_data_0, io_mem_data_1, io_mem_data_2, io_mem_data_3, io_mem_data_4, io_mem_data_5, io_mem_data_6, io_mem_data_7}, alignedWord);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:143:32, :149:41, :150:{16,143}]
        $fwrite(32'h80000002, "MemReader: alignedVec %x\n", alignedWord);	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:149:41, :152:16]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [2:0]      bytes = io_size == 3'h3 ? 3'h7 : io_size == 3'h2 ? 3'h3 : io_size == 3'h1 ? 3'h1 : io_size == 3'h0 ? 3'h0 : 3'h7;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:96:30]
  wire [7:0][7:0] _GEN = {{alignedWord[7:0]}, {alignedWord[15:8]}, {alignedWord[23:16]}, {alignedWord[31:24]}, {alignedWord[39:32]}, {alignedWord[47:40]}, {alignedWord[55:48]}, {alignedWord[63:56]}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:121:37, :149:41, :161:52]
  wire [22:0]     _masks_mask_T = 23'h1FF << bytes;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:96:30, :113:28]
  wire            _maskedVec_ext_bits_T_21 = io_signed & _GEN[bytes][7];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:96:30, :161:52, :175:46]
  assign io_data = {alignedWord[63:56] & {8{_masks_mask_T[14]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[14])}}, alignedWord[55:48] & {8{_masks_mask_T[13]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[13])}}, alignedWord[47:40] & {8{_masks_mask_T[12]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[12])}}, alignedWord[39:32] & {8{_masks_mask_T[11]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[11])}}, alignedWord[31:24] & {8{_masks_mask_T[10]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[10])}}, alignedWord[23:16] & {8{_masks_mask_T[9]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[9])}}, alignedWord[15:8] & {8{_masks_mask_T[8]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[8])}}, alignedWord[7:0] & {8{_masks_mask_T[7]}} | {8{_maskedVec_ext_bits_T_21 & ~(_masks_mask_T[7])}}};	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:113:{28,49}, :115:22, :121:37, :127:13, :149:41, :173:31, :174:34, :175:{33,46,54,57}, :176:23, :183:24]
  assign io_mem_addr = io_addr[20:3];	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:127:13, :143:32]
endmodule

