// Generated by CIRCT firtool-1.75.0

// Users can define 'STOP_COND' to add an extra gate to stop conditions.
`ifndef STOP_COND_
  `ifdef STOP_COND
    `define STOP_COND_ (`STOP_COND)
  `else  // STOP_COND
    `define STOP_COND_ 1
  `endif // STOP_COND
`endif // not def STOP_COND_

// Users can define 'ASSERT_VERBOSE_COND' to add an extra gate to assert error printing.
`ifndef ASSERT_VERBOSE_COND_
  `ifdef ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ (`ASSERT_VERBOSE_COND)
  `else  // ASSERT_VERBOSE_COND
    `define ASSERT_VERBOSE_COND_ 1
  `endif // ASSERT_VERBOSE_COND
`endif // not def ASSERT_VERBOSE_COND_

// Include register initializers in init blocks unless synthesis is set
`ifndef RANDOMIZE
  `ifdef RANDOMIZE_REG_INIT
    `define RANDOMIZE
  `endif // RANDOMIZE_REG_INIT
`endif // not def RANDOMIZE
`ifndef SYNTHESIS
  `ifndef ENABLE_INITIAL_REG_
    `define ENABLE_INITIAL_REG_
  `endif // not def ENABLE_INITIAL_REG_
`endif // not def SYNTHESIS

// Standard header to adapt well known macros for register randomization.

// RANDOM may be set to an expression that produces a 32-bit random unsigned value.
`ifndef RANDOM
  `define RANDOM $random
`endif // not def RANDOM

// Users can define INIT_RANDOM as general code that gets injected into the
// initializer block for modules with registers.
`ifndef INIT_RANDOM
  `define INIT_RANDOM
`endif // not def INIT_RANDOM

// If using random initialization, you can also define RANDOMIZE_DELAY to
// customize the delay used, otherwise 0.002 is used.
`ifndef RANDOMIZE_DELAY
  `define RANDOMIZE_DELAY 0.002
`endif // not def RANDOMIZE_DELAY

// Define INIT_RANDOM_PROLOG_ for use in our modules below.
`ifndef INIT_RANDOM_PROLOG_
  `ifdef RANDOMIZE
    `ifdef VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM
    `else  // VERILATOR
      `define INIT_RANDOM_PROLOG_ `INIT_RANDOM #`RANDOMIZE_DELAY begin end
    `endif // VERILATOR
  `else  // RANDOMIZE
    `define INIT_RANDOM_PROLOG_
  `endif // RANDOMIZE
`endif // not def INIT_RANDOM_PROLOG_
module SodorMasterAdapter(	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
  input         clock,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
  input         reset,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
  input         auto_out_a_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [2:0]  auto_out_a_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [3:0]  auto_out_a_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_bits_source,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [31:0] auto_out_a_bits_address,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [7:0]  auto_out_a_bits_mask,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output [63:0] auto_out_a_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_a_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  output        auto_out_d_ready,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_valid,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [2:0]  auto_out_d_bits_opcode,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [1:0]  auto_out_d_bits_param,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [3:0]  auto_out_d_bits_size,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_sink,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_denied,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input  [63:0] auto_out_d_bits_data,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         auto_out_d_bits_corrupt,	// @[generators/diplomacy/diplomacy/src/diplomacy/lazymodule/LazyModuleImp.scala:106:25]
  input         io_dport_req_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  input  [63:0] io_dport_req_bits_addr,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  input  [63:0] io_dport_req_bits_data,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  input         io_dport_req_bits_fcn,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  input  [2:0]  io_dport_req_bits_typ,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  output        io_dport_resp_valid,	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
  output [63:0] io_dport_resp_bits_data	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:41:14]
);

  wire        _buffer_auto_in_a_ready;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_valid;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [3:0]  _buffer_auto_in_d_bits_size;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_denied;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [63:0] _buffer_auto_in_d_bits_data;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire        _buffer_auto_in_d_bits_corrupt;	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  reg  [1:0]  state;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22]
  reg  [63:0] a_address_reg;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:52:26]
  reg         a_signed_reg;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:53:25]
  reg  [63:0] req_address_reg;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28]
  reg  [1:0]  req_size_reg;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25]
  reg  [63:0] req_data_reg;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:57:25]
  wire        masterNodeOut_a_valid = state == 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22, :69:15]
  wire        a_mask_sub_sub_size = req_size_reg == 2'h2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        a_mask_sub_sub_0_1 = (&req_size_reg) | a_mask_sub_sub_size & ~(req_address_reg[2]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, :56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        a_mask_sub_sub_1_1 = (&req_size_reg) | a_mask_sub_sub_size & req_address_reg[2];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, :56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        a_mask_sub_size = req_size_reg == 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        a_mask_sub_0_2 = ~(req_address_reg[2]) & ~(req_address_reg[1]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_0_1 = a_mask_sub_sub_0_1 | a_mask_sub_size & a_mask_sub_0_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_1_2 = ~(req_address_reg[2]) & req_address_reg[1];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_1_1 = a_mask_sub_sub_0_1 | a_mask_sub_size & a_mask_sub_1_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_2_2 = req_address_reg[2] & ~(req_address_reg[1]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_2_1 = a_mask_sub_sub_1_1 | a_mask_sub_size & a_mask_sub_2_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_3_2 = req_address_reg[2] & req_address_reg[1];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        a_mask_sub_3_1 = a_mask_sub_sub_1_1 | a_mask_sub_size & a_mask_sub_3_2;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_sub_size_1 = req_size_reg == 2'h2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        a_mask_sub_sub_0_1_1 = (&req_size_reg) | a_mask_sub_sub_size_1 & ~(req_address_reg[2]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, :56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :211:20, :215:{29,38}]
  wire        a_mask_sub_sub_1_1_1 = (&req_size_reg) | a_mask_sub_sub_size_1 & req_address_reg[2];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, :56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:206:21, :209:26, :210:26, :215:{29,38}]
  wire        a_mask_sub_size_1 = req_size_reg == 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/rocket-chip/src/main/scala/util/Misc.scala:209:26]
  wire        a_mask_sub_0_2_1 = ~(req_address_reg[2]) & ~(req_address_reg[1]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_0_1_1 = a_mask_sub_sub_0_1_1 | a_mask_sub_size_1 & a_mask_sub_0_2_1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_1_2_1 = ~(req_address_reg[2]) & req_address_reg[1];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_1_1_1 = a_mask_sub_sub_0_1_1 | a_mask_sub_size_1 & a_mask_sub_1_2_1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_2_2_1 = req_address_reg[2] & ~(req_address_reg[1]);	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27]
  wire        a_mask_sub_2_1_1 = a_mask_sub_sub_1_1_1 | a_mask_sub_size_1 & a_mask_sub_2_2_1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire        a_mask_sub_3_2_1 = req_address_reg[2] & req_address_reg[1];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :214:27]
  wire        a_mask_sub_3_1_1 = a_mask_sub_sub_1_1_1 | a_mask_sub_size_1 & a_mask_sub_3_2_1;	// @[generators/rocket-chip/src/main/scala/util/Misc.scala:209:26, :214:27, :215:{29,38}]
  wire [31:0] io_dport_resp_bits_data_zeroed = a_address_reg[2] ? _buffer_auto_in_d_bits_data[63:32] : _buffer_auto_in_d_bits_data[31:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:52:26, generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:42:{24,29,37,55}, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  wire [15:0] io_dport_resp_bits_data_zeroed_1 = a_address_reg[1] ? io_dport_resp_bits_data_zeroed[31:16] : io_dport_resp_bits_data_zeroed[15:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:52:26, generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:42:{24,29,37,55}]
  wire [7:0]  io_dport_resp_bits_data_zeroed_2 = a_address_reg[0] ? io_dport_resp_bits_data_zeroed_1[15:8] : io_dport_resp_bits_data_zeroed_1[7:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:52:26, generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:42:{24,29,37,55}]
  `ifndef SYNTHESIS	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
    wire [6:0] _GEN = {req_address_reg[31], req_address_reg[27], req_address_reg[25], req_address_reg[20], req_address_reg[16], ~(req_address_reg[13:12])};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [5:0] _GEN_0 = {req_address_reg[31], req_address_reg[27], req_address_reg[25], req_address_reg[20], req_address_reg[16], req_address_reg[13]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [4:0] _GEN_1 = {req_address_reg[31], req_address_reg[27], req_address_reg[25], req_address_reg[20], ~(req_address_reg[16])};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [5:0] _GEN_2 = {req_address_reg[31], req_address_reg[27], req_address_reg[25], ~(req_address_reg[20]), req_address_reg[13:12]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [4:0] _GEN_3 = {req_address_reg[31], req_address_reg[27], ~(req_address_reg[25]), req_address_reg[20], req_address_reg[16]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [1:0] _GEN_4 = {req_address_reg[31], ~(req_address_reg[27])};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    wire [6:0] _GEN_5 = {~(req_address_reg[31]), req_address_reg[27], req_address_reg[25], req_address_reg[20], req_address_reg[16], req_address_reg[13:12]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{31,41,46}]
    always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
      if (~reset & ~((io_dport_req_bits_fcn ? ~(|_GEN) | ~(|_GEN_0) | ~(|_GEN_1) | ~(|_GEN_2) | ~(|_GEN_3) | ~(|_GEN_4) | ~(|_GEN_5) : ~(|_GEN) | ~(|_GEN_0) | ~(|_GEN_1) | ~(|_GEN_2) | ~(|_GEN_3) | ~(|_GEN_4) | ~(|_GEN_5)) | ~masterNodeOut_a_valid)) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:69:15, :98:21, :101:{9,19,21}, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:{41,46,59}, generators/rocket-chip/src/main/scala/tilelink/Parameters.scala:685:42, :686:26]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
          $error("Assertion failed: Illegal operation\n    at master_adapter.scala:101 assert(legal_op | !tl_out.a.valid, \"Illegal operation\")\n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
        if (`STOP_COND_)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
          $fatal;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:101:9]
      end
      if (~reset & ~(~(_buffer_auto_in_d_bits_corrupt | _buffer_auto_in_d_bits_denied) | ~_buffer_auto_in_d_valid)) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:99:39, :101:9, :102:{9,10,19,21}, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
        if (`ASSERT_VERBOSE_COND_)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:102:9]
          $error("Assertion failed: Responds exception\n    at master_adapter.scala:102 assert(!resp_xp | !tl_out.d.valid, \"Responds exception\")\n");	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:102:9]
        if (`STOP_COND_)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:102:9]
          $fatal;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:102:9]
      end
    end // always @(posedge)
  `endif // not def SYNTHESIS
  wire [1:0]  _a_size_T = io_dport_req_bits_typ[1:0] - 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:61:27]
  wire        _GEN_6 = state == 2'h0 & io_dport_req_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22, :63:{15,27}]
  wire        _GEN_7 = _buffer_auto_in_a_ready & masterNodeOut_a_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:69:15, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28, src/main/scala/chisel3/util/Decoupled.scala:51:35]
  always @(posedge clock) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
    if (reset)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
      state <= 2'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22]
    else if (state == 2'h2 & _buffer_auto_in_d_valid)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22, :72:{15,30}, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
      state <= 2'h0;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22]
    else if (_GEN_7)	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      state <= 2'h2;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22]
    else if (_GEN_6)	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:63:27]
      state <= 2'h1;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:50:22]
    if (_GEN_7) begin	// @[src/main/scala/chisel3/util/Decoupled.scala:51:35]
      a_address_reg <= io_dport_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:52:26]
      a_signed_reg <= _a_size_T[0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:53:25, :83:18, generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:60:{24,30}, :61:27]
    end
    if (_GEN_6) begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:63:27]
      req_address_reg <= io_dport_req_bits_addr;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28]
      req_size_reg <= _a_size_T;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/riscv-sodor/src/main/scala/sodor/common/memory.scala:61:27]
      req_data_reg <= io_dport_req_bits_data;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:57:25]
    end
  end // always @(posedge)
  `ifdef ENABLE_INITIAL_REG_	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
    `ifdef FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
      `FIRRTL_BEFORE_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
    `endif // FIRRTL_BEFORE_INITIAL
    logic [31:0] _RANDOM[0:6];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
    initial begin	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
      `ifdef INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
        `INIT_RANDOM_PROLOG_	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
      `endif // INIT_RANDOM_PROLOG_
      `ifdef RANDOMIZE_REG_INIT	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
        for (logic [2:0] i = 3'h0; i < 3'h7; i += 3'h1) begin
          _RANDOM[i] = `RANDOM;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
        end	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
        state = _RANDOM[3'h0][1:0];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :50:22]
        a_address_reg = {_RANDOM[3'h0][31:2], _RANDOM[3'h1], _RANDOM[3'h2][1:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :50:22, :52:26]
        a_signed_reg = _RANDOM[3'h2][2];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :52:26, :53:25]
        req_address_reg = {_RANDOM[3'h2][31:3], _RANDOM[3'h3], _RANDOM[3'h4][2:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :52:26, :55:28]
        req_size_reg = _RANDOM[3'h4][4:3];	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :55:28, :56:25]
        req_data_reg = {_RANDOM[3'h4][31:5], _RANDOM[3'h5], _RANDOM[3'h6][4:0]};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :55:28, :57:25]
      `endif // RANDOMIZE_REG_INIT
    end // initial
    `ifdef FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
      `FIRRTL_AFTER_INITIAL	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7]
    `endif // FIRRTL_AFTER_INITIAL
  `endif // ENABLE_INITIAL_REG_
  TLBuffer_a32d64s1k1z4u buffer (	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
    .clock                   (clock),
    .reset                   (reset),
    .auto_in_a_ready         (_buffer_auto_in_a_ready),
    .auto_in_a_valid         (masterNodeOut_a_valid),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:69:15]
    .auto_in_a_bits_opcode   ({~io_dport_req_bits_fcn, 2'h0}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:92:{23,46}]
    .auto_in_a_bits_size     ({2'h0, req_size_reg}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:56:25, generators/rocket-chip/src/main/scala/tilelink/Edges.scala:463:15]
    .auto_in_a_bits_address  (req_address_reg[31:0]),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, generators/rocket-chip/src/main/scala/diplomacy/Parameters.scala:137:31]
    .auto_in_a_bits_mask     (io_dport_req_bits_fcn ? {a_mask_sub_3_1_1 | a_mask_sub_3_2_1 & req_address_reg[0], a_mask_sub_3_1_1 | a_mask_sub_3_2_1 & ~(req_address_reg[0]), a_mask_sub_2_1_1 | a_mask_sub_2_2_1 & req_address_reg[0], a_mask_sub_2_1_1 | a_mask_sub_2_2_1 & ~(req_address_reg[0]), a_mask_sub_1_1_1 | a_mask_sub_1_2_1 & req_address_reg[0], a_mask_sub_1_1_1 | a_mask_sub_1_2_1 & ~(req_address_reg[0]), a_mask_sub_0_1_1 | a_mask_sub_0_2_1 & req_address_reg[0], a_mask_sub_0_1_1 | a_mask_sub_0_2_1 & ~(req_address_reg[0])} : {a_mask_sub_3_1 | a_mask_sub_3_2 & req_address_reg[0], a_mask_sub_3_1 | a_mask_sub_3_2 & ~(req_address_reg[0]), a_mask_sub_2_1 | a_mask_sub_2_2 & req_address_reg[0], a_mask_sub_2_1 | a_mask_sub_2_2 & ~(req_address_reg[0]), a_mask_sub_1_1 | a_mask_sub_1_2 & req_address_reg[0], a_mask_sub_1_1 | a_mask_sub_1_2 & ~(req_address_reg[0]), a_mask_sub_0_1 | a_mask_sub_0_2 & req_address_reg[0], a_mask_sub_0_1 | a_mask_sub_0_2 & ~(req_address_reg[0])}),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:55:28, :92:23, generators/rocket-chip/src/main/scala/util/Misc.scala:210:26, :211:20, :214:27, :215:29, :222:10]
    .auto_in_a_bits_data     (io_dport_req_bits_fcn ? req_data_reg : 64'h0),	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:57:25, :92:23]
    .auto_in_d_valid         (_buffer_auto_in_d_valid),
    .auto_in_d_bits_size     (_buffer_auto_in_d_bits_size),
    .auto_in_d_bits_denied   (_buffer_auto_in_d_bits_denied),
    .auto_in_d_bits_data     (_buffer_auto_in_d_bits_data),
    .auto_in_d_bits_corrupt  (_buffer_auto_in_d_bits_corrupt),
    .auto_out_a_ready        (auto_out_a_ready),
    .auto_out_a_valid        (auto_out_a_valid),
    .auto_out_a_bits_opcode  (auto_out_a_bits_opcode),
    .auto_out_a_bits_param   (auto_out_a_bits_param),
    .auto_out_a_bits_size    (auto_out_a_bits_size),
    .auto_out_a_bits_source  (auto_out_a_bits_source),
    .auto_out_a_bits_address (auto_out_a_bits_address),
    .auto_out_a_bits_mask    (auto_out_a_bits_mask),
    .auto_out_a_bits_data    (auto_out_a_bits_data),
    .auto_out_a_bits_corrupt (auto_out_a_bits_corrupt),
    .auto_out_d_ready        (auto_out_d_ready),
    .auto_out_d_valid        (auto_out_d_valid),
    .auto_out_d_bits_opcode  (auto_out_d_bits_opcode),
    .auto_out_d_bits_param   (auto_out_d_bits_param),
    .auto_out_d_bits_size    (auto_out_d_bits_size),
    .auto_out_d_bits_sink    (auto_out_d_bits_sink),
    .auto_out_d_bits_denied  (auto_out_d_bits_denied),
    .auto_out_d_bits_data    (auto_out_d_bits_data),
    .auto_out_d_bits_corrupt (auto_out_d_bits_corrupt)
  );	// @[generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  assign io_dport_resp_valid = _buffer_auto_in_d_valid;	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
  assign io_dport_resp_bits_data = {_buffer_auto_in_d_bits_size[1:0] == 2'h0 ? {56{a_signed_reg & io_dport_resp_bits_data_zeroed_2[7]}} : {_buffer_auto_in_d_bits_size[1:0] == 2'h1 ? {48{a_signed_reg & io_dport_resp_bits_data_zeroed_1[15]}} : {_buffer_auto_in_d_bits_size[1:0] == 2'h2 ? {32{a_signed_reg & io_dport_resp_bits_data_zeroed[31]}} : _buffer_auto_in_d_bits_data[63:32], io_dport_resp_bits_data_zeroed[31:16]}, io_dport_resp_bits_data_zeroed_1[15:8]}, io_dport_resp_bits_data_zeroed_2};	// @[generators/riscv-sodor/src/main/scala/sodor/common/master_adapter.scala:38:7, :53:25, generators/rocket-chip/src/main/scala/rocket/AMOALU.scala:12:8, :42:{24,37}, :45:{16,20,26,49,72,81,94}, generators/rocket-chip/src/main/scala/tilelink/Buffer.scala:75:28]
endmodule

